package io.github.edadma.markdown

val emojiBlock10 = List(
  "clock530" -> "🕠",
  "six_o’clock" -> "🕕",
  "six-o’clock" -> "🕕",
  "six o’clock" -> "🕕",
  "clock6" -> "🕕",
  "six-thirty" -> "🕡",
  "clock630" -> "🕡",
  "seven_o’clock" -> "🕖",
  "seven-o’clock" -> "🕖",
  "seven o’clock" -> "🕖",
  "clock7" -> "🕖",
  "seven-thirty" -> "🕢",
  "clock730" -> "🕢",
  "eight_o’clock" -> "🕗",
  "eight-o’clock" -> "🕗",
  "eight o’clock" -> "🕗",
  "clock8" -> "🕗",
  "eight-thirty" -> "🕣",
  "clock830" -> "🕣",
  "nine_o’clock" -> "🕘",
  "nine-o’clock" -> "🕘",
  "nine o’clock" -> "🕘",
  "clock9" -> "🕘",
  "nine-thirty" -> "🕤",
  "clock930" -> "🕤",
  "ten_o’clock" -> "🕙",
  "ten-o’clock" -> "🕙",
  "ten o’clock" -> "🕙",
  "clock10" -> "🕙",
  "ten-thirty" -> "🕥",
  "clock1030" -> "🕥",
  "eleven_o’clock" -> "🕚",
  "eleven-o’clock" -> "🕚",
  "eleven o’clock" -> "🕚",
  "clock11" -> "🕚",
  "eleven-thirty" -> "🕦",
  "clock1130" -> "🕦",
  "new_moon" -> "🌑",
  "new-moon" -> "🌑",
  "new moon" -> "🌑",
  "waxing_crescent_moon" -> "🌒",
  "waxing-crescent-moon" -> "🌒",
  "waxing crescent moon" -> "🌒",
  "first_quarter_moon" -> "🌓",
  "first-quarter-moon" -> "🌓",
  "first quarter moon" -> "🌓",
  "waxing_gibbous_moon" -> "🌔",
  "waxing-gibbous-moon" -> "🌔",
  "waxing gibbous moon" -> "🌔",
  "moon" -> "🌔",
  "full_moon" -> "🌕",
  "full-moon" -> "🌕",
  "full moon" -> "🌕",
  "waning_gibbous_moon" -> "🌖",
  "waning-gibbous-moon" -> "🌖",
  "waning gibbous moon" -> "🌖",
  "last_quarter_moon" -> "🌗",
  "last-quarter-moon" -> "🌗",
  "last quarter moon" -> "🌗",
  "waning_crescent_moon" -> "🌘",
  "waning-crescent-moon" -> "🌘",
  "waning crescent moon" -> "🌘",
  "crescent_moon" -> "🌙",
  "crescent-moon" -> "🌙",
  "crescent moon" -> "🌙",
  "new_moon_face" -> "🌚",
  "new-moon-face" -> "🌚",
  "new moon face" -> "🌚",
  "new_moon_with_face" -> "🌚",
  "first_quarter_moon_face" -> "🌛",
  "first-quarter-moon-face" -> "🌛",
  "first quarter moon face" -> "🌛",
  "first_quarter_moon_with_face" -> "🌛",
  "last_quarter_moon_face" -> "🌜",
  "last-quarter-moon-face" -> "🌜",
  "last quarter moon face" -> "🌜",
  "last_quarter_moon_with_face" -> "🌜",
  "thermometer" -> "🌡️",
  "sun" -> "☀️",
  "sunny" -> "☀️",
  "full_moon_face" -> "🌝",
  "full-moon-face" -> "🌝",
  "full moon face" -> "🌝",
  "full_moon_with_face" -> "🌝",
  "sun_with_face" -> "🌞",
  "sun-with-face" -> "🌞",
  "sun with face" -> "🌞",
  "ringed_planet" -> "🪐",
  "ringed-planet" -> "🪐",
  "ringed planet" -> "🪐",
  "star" -> "⭐",
  "glowing_star" -> "🌟",
  "glowing-star" -> "🌟",
  "glowing star" -> "🌟",
  "star2" -> "🌟",
  "shooting_star" -> "🌠",
  "shooting-star" -> "🌠",
  "shooting star" -> "🌠",
  "stars" -> "🌠",
  "milky_way" -> "🌌",
  "milky-way" -> "🌌",
  "milky way" -> "🌌",
  "cloud" -> "☁️",
  "sun_behind_cloud" -> "⛅",
  "sun-behind-cloud" -> "⛅",
  "sun behind cloud" -> "⛅",
  "partly_sunny" -> "⛅",
  "cloud_with_lightning_and_rain" -> "⛈️",
  "cloud-with-lightning-and-rain" -> "⛈️",
  "cloud with lightning and rain" -> "⛈️",
  "sun_behind_small_cloud" -> "🌤️",
  "sun-behind-small-cloud" -> "🌤️",
  "sun behind small cloud" -> "🌤️",
  "sun_behind_large_cloud" -> "🌥️",
  "sun-behind-large-cloud" -> "🌥️",
  "sun behind large cloud" -> "🌥️",
  "sun_behind_rain_cloud" -> "🌦️",
  "sun-behind-rain-cloud" -> "🌦️",
  "sun behind rain cloud" -> "🌦️",
  "cloud_with_rain" -> "🌧️",
  "cloud-with-rain" -> "🌧️",
  "cloud with rain" -> "🌧️",
  "cloud_with_snow" -> "🌨️",
  "cloud-with-snow" -> "🌨️",
  "cloud with snow" -> "🌨️",
  "cloud_with_lightning" -> "🌩️",
  "cloud-with-lightning" -> "🌩️",
  "cloud with lightning" -> "🌩️",
  "tornado" -> "🌪️",
  "fog" -> "🌫️",
  "wind_face" -> "🌬️",
  "wind-face" -> "🌬️",
  "wind face" -> "🌬️",
  "cyclone" -> "🌀",
  "rainbow" -> "🌈",
  "closed_umbrella" -> "🌂",
  "closed-umbrella" -> "🌂",
  "closed umbrella" -> "🌂",
  "umbrella" -> "☂️",
  "open_umbrella" -> "☂️",
  "umbrella_with_rain_drops" -> "☔",
  "umbrella-with-rain-drops" -> "☔",
  "umbrella with rain drops" -> "☔",
  "umbrella" -> "☔",
  "umbrella_on_ground" -> "⛱️",
  "umbrella-on-ground" -> "⛱️",
  "umbrella on ground" -> "⛱️",
  "parasol_on_ground" -> "⛱️",
  "high_voltage" -> "⚡",
  "high-voltage" -> "⚡",
  "high voltage" -> "⚡",
  "zap" -> "⚡",
  "snowflake" -> "❄️",
  "snowman" -> "☃️",
  "snowman_with_snow" -> "☃️",
  "snowman_without_snow" -> "⛄",
  "snowman-without-snow" -> "⛄",
  "snowman without snow" -> "⛄",
  "snowman" -> "⛄",
  "comet" -> "☄️",
  "fire" -> "🔥",
  "droplet" -> "💧",
  "water_wave" -> "🌊",
  "water-wave" -> "🌊",
  "water wave" -> "🌊",
  "ocean" -> "🌊",
  "jack-o-lantern" -> "🎃",
  "jack_o_lantern" -> "🎃",
  "Christmas_tree" -> "🎄",
  "Christmas-tree" -> "🎄",
  "Christmas tree" -> "🎄",
  "christmas_tree" -> "🎄",
  "fireworks" -> "🎆",
  "sparkler" -> "🎇",
  "firecracker" -> "🧨",
  "sparkles" -> "✨",
  "balloon" -> "🎈",
  "party_popper" -> "🎉",
  "party-popper" -> "🎉",
  "party popper" -> "🎉",
  "tada" -> "🎉",
  "confetti_ball" -> "🎊",
  "confetti-ball" -> "🎊",
  "confetti ball" -> "🎊",
  "tanabata_tree" -> "🎋",
  "tanabata-tree" -> "🎋",
  "tanabata tree" -> "🎋",
  "pine_decoration" -> "🎍",
  "pine-decoration" -> "🎍",
  "pine decoration" -> "🎍",
  "bamboo" -> "🎍",
  "Japanese_dolls" -> "🎎",
  "Japanese-dolls" -> "🎎",
  "Japanese dolls" -> "🎎",
  "dolls" -> "🎎",
  "carp_streamer" -> "🎏",
  "carp-streamer" -> "🎏",
  "carp streamer" -> "🎏",
  "flags" -> "🎏",
  "wind_chime" -> "🎐",
  "wind-chime" -> "🎐",
  "wind chime" -> "🎐",
  "moon_viewing_ceremony" -> "🎑",
  "moon-viewing-ceremony" -> "🎑",
  "moon viewing ceremony" -> "🎑",
  "rice_scene" -> "🎑",
  "red_envelope" -> "🧧",
  "red-envelope" -> "🧧",
  "red envelope" -> "🧧",
  "ribbon" -> "🎀",
  "wrapped_gift" -> "🎁",
  "wrapped-gift" -> "🎁",
  "wrapped gift" -> "🎁",
  "gift" -> "🎁",
  "reminder_ribbon" -> "🎗️",
  "reminder-ribbon" -> "🎗️",
  "reminder ribbon" -> "🎗️",
  "admission_tickets" -> "🎟️",
  "admission-tickets" -> "🎟️",
  "admission tickets" -> "🎟️",
  "tickets" -> "🎟️",
  "ticket" -> "🎫",
  "military_medal" -> "🎖️",
  "military-medal" -> "🎖️",
  "military medal" -> "🎖️",
  "medal_military" -> "🎖️",
  "trophy" -> "🏆",
  "sports_medal" -> "🏅",
  "sports-medal" -> "🏅",
  "sports medal" -> "🏅",
  "medal_sports" -> "🏅",
  "1st_place_medal" -> "🥇",
  "1st-place-medal" -> "🥇",
  "1st place medal" -> "🥇",
  "2nd_place_medal" -> "🥈",
  "2nd-place-medal" -> "🥈",
  "2nd place medal" -> "🥈",
  "3rd_place_medal" -> "🥉",
  "3rd-place-medal" -> "🥉",
  "3rd place medal" -> "🥉",
  "soccer_ball" -> "⚽",
  "soccer-ball" -> "⚽",
  "soccer ball" -> "⚽",
  "soccer" -> "⚽",
  "baseball" -> "⚾",
  "softball" -> "🥎",
  "basketball" -> "🏀",
  "volleyball" -> "🏐",
  "american_football" -> "🏈",
  "american-football" -> "🏈",
  "american football" -> "🏈",
  "football" -> "🏈",
  "rugby_football" -> "🏉",
  "rugby-football" -> "🏉",
  "rugby football" -> "🏉",
  "tennis" -> "🎾",
  "flying_disc" -> "🥏",
  "flying-disc" -> "🥏",
  "flying disc" -> "🥏",
  "bowling" -> "🎳",
  "cricket_game" -> "🏏",
  "cricket-game" -> "🏏",
  "cricket game" -> "🏏",
  "field_hockey" -> "🏑",
  "field-hockey" -> "🏑",
  "field hockey" -> "🏑",
  "ice_hockey" -> "🏒",
  "ice-hockey" -> "🏒",
  "ice hockey" -> "🏒",
  "lacrosse" -> "🥍",
  "ping_pong" -> "🏓",
  "ping-pong" -> "🏓",
  "ping pong" -> "🏓",
  "badminton" -> "🏸",
  "boxing_glove" -> "🥊",
  "boxing-glove" -> "🥊",
  "boxing glove" -> "🥊",
  "martial_arts_uniform" -> "🥋",
  "martial-arts-uniform" -> "🥋",
  "martial arts uniform" -> "🥋",
  "goal_net" -> "🥅",
  "goal-net" -> "🥅",
  "goal net" -> "🥅",
  "flag_in_hole" -> "⛳",
  "flag-in-hole" -> "⛳",
  "flag in hole" -> "⛳",
  "golf" -> "⛳",
  "ice_skate" -> "⛸️",
  "ice-skate" -> "⛸️",
  "ice skate" -> "⛸️",
  "fishing_pole" -> "🎣",
  "fishing-pole" -> "🎣",
  "fishing pole" -> "🎣",
  "fishing_pole_and_fish" -> "🎣",
  "diving_mask" -> "🤿",
  "diving-mask" -> "🤿",
  "diving mask" -> "🤿",
  "running_shirt" -> "🎽",
  "running-shirt" -> "🎽",
  "running shirt" -> "🎽",
)
