package io.github.edadma.markdown

val emojiBlock4 = List(
  "ok_woman" -> "🙆‍♀️",
  "person_tipping_hand" -> "💁",
  "person-tipping-hand" -> "💁",
  "person tipping hand" -> "💁",
  "tipping_hand_person" -> "💁",
  "information_desk_person" -> "💁",
  "man_tipping_hand" -> "💁‍♂️",
  "man-tipping-hand" -> "💁‍♂️",
  "man tipping hand" -> "💁‍♂️",
  "tipping_hand_man" -> "💁‍♂️",
  "sassy_man" -> "💁‍♂️",
  "woman_tipping_hand" -> "💁‍♀️",
  "woman-tipping-hand" -> "💁‍♀️",
  "woman tipping hand" -> "💁‍♀️",
  "tipping_hand_woman" -> "💁‍♀️",
  "sassy_woman" -> "💁‍♀️",
  "person_raising_hand" -> "🙋",
  "person-raising-hand" -> "🙋",
  "person raising hand" -> "🙋",
  "raising_hand" -> "🙋",
  "man_raising_hand" -> "🙋‍♂️",
  "man-raising-hand" -> "🙋‍♂️",
  "man raising hand" -> "🙋‍♂️",
  "raising_hand_man" -> "🙋‍♂️",
  "woman_raising_hand" -> "🙋‍♀️",
  "woman-raising-hand" -> "🙋‍♀️",
  "woman raising hand" -> "🙋‍♀️",
  "raising_hand_woman" -> "🙋‍♀️",
  "deaf_person" -> "🧏",
  "deaf-person" -> "🧏",
  "deaf person" -> "🧏",
  "deaf_man" -> "🧏‍♂️",
  "deaf-man" -> "🧏‍♂️",
  "deaf man" -> "🧏‍♂️",
  "deaf_woman" -> "🧏‍♀️",
  "deaf-woman" -> "🧏‍♀️",
  "deaf woman" -> "🧏‍♀️",
  "person_bowing" -> "🙇",
  "person-bowing" -> "🙇",
  "person bowing" -> "🙇",
  "bow" -> "🙇",
  "man_bowing" -> "🙇‍♂️",
  "man-bowing" -> "🙇‍♂️",
  "man bowing" -> "🙇‍♂️",
  "bowing_man" -> "🙇‍♂️",
  "woman_bowing" -> "🙇‍♀️",
  "woman-bowing" -> "🙇‍♀️",
  "woman bowing" -> "🙇‍♀️",
  "bowing_woman" -> "🙇‍♀️",
  "person_facepalming" -> "🤦",
  "person-facepalming" -> "🤦",
  "person facepalming" -> "🤦",
  "facepalm" -> "🤦",
  "man_facepalming" -> "🤦‍♂️",
  "man-facepalming" -> "🤦‍♂️",
  "man facepalming" -> "🤦‍♂️",
  "woman_facepalming" -> "🤦‍♀️",
  "woman-facepalming" -> "🤦‍♀️",
  "woman facepalming" -> "🤦‍♀️",
  "person_shrugging" -> "🤷",
  "person-shrugging" -> "🤷",
  "person shrugging" -> "🤷",
  "shrug" -> "🤷",
  "man_shrugging" -> "🤷‍♂️",
  "man-shrugging" -> "🤷‍♂️",
  "man shrugging" -> "🤷‍♂️",
  "woman_shrugging" -> "🤷‍♀️",
  "woman-shrugging" -> "🤷‍♀️",
  "woman shrugging" -> "🤷‍♀️",
  "health_worker" -> "🧑‍⚕️",
  "health-worker" -> "🧑‍⚕️",
  "health worker" -> "🧑‍⚕️",
  "man_health_worker" -> "👨‍⚕️",
  "man-health-worker" -> "👨‍⚕️",
  "man health worker" -> "👨‍⚕️",
  "woman_health_worker" -> "👩‍⚕️",
  "woman-health-worker" -> "👩‍⚕️",
  "woman health worker" -> "👩‍⚕️",
  "student" -> "🧑‍🎓",
  "man_student" -> "👨‍🎓",
  "man-student" -> "👨‍🎓",
  "man student" -> "👨‍🎓",
  "woman_student" -> "👩‍🎓",
  "woman-student" -> "👩‍🎓",
  "woman student" -> "👩‍🎓",
  "teacher" -> "🧑‍🏫",
  "man_teacher" -> "👨‍🏫",
  "man-teacher" -> "👨‍🏫",
  "man teacher" -> "👨‍🏫",
  "woman_teacher" -> "👩‍🏫",
  "woman-teacher" -> "👩‍🏫",
  "woman teacher" -> "👩‍🏫",
  "judge" -> "🧑‍⚖️",
  "man_judge" -> "👨‍⚖️",
  "man-judge" -> "👨‍⚖️",
  "man judge" -> "👨‍⚖️",
  "woman_judge" -> "👩‍⚖️",
  "woman-judge" -> "👩‍⚖️",
  "woman judge" -> "👩‍⚖️",
  "farmer" -> "🧑‍🌾",
  "man_farmer" -> "👨‍🌾",
  "man-farmer" -> "👨‍🌾",
  "man farmer" -> "👨‍🌾",
  "woman_farmer" -> "👩‍🌾",
  "woman-farmer" -> "👩‍🌾",
  "woman farmer" -> "👩‍🌾",
  "cook" -> "🧑‍🍳",
  "man_cook" -> "👨‍🍳",
  "man-cook" -> "👨‍🍳",
  "man cook" -> "👨‍🍳",
  "woman_cook" -> "👩‍🍳",
  "woman-cook" -> "👩‍🍳",
  "woman cook" -> "👩‍🍳",
  "mechanic" -> "🧑‍🔧",
  "man_mechanic" -> "👨‍🔧",
  "man-mechanic" -> "👨‍🔧",
  "man mechanic" -> "👨‍🔧",
  "woman_mechanic" -> "👩‍🔧",
  "woman-mechanic" -> "👩‍🔧",
  "woman mechanic" -> "👩‍🔧",
  "factory_worker" -> "🧑‍🏭",
  "factory-worker" -> "🧑‍🏭",
  "factory worker" -> "🧑‍🏭",
  "man_factory_worker" -> "👨‍🏭",
  "man-factory-worker" -> "👨‍🏭",
  "man factory worker" -> "👨‍🏭",
  "woman_factory_worker" -> "👩‍🏭",
  "woman-factory-worker" -> "👩‍🏭",
  "woman factory worker" -> "👩‍🏭",
  "office_worker" -> "🧑‍💼",
  "office-worker" -> "🧑‍💼",
  "office worker" -> "🧑‍💼",
  "man_office_worker" -> "👨‍💼",
  "man-office-worker" -> "👨‍💼",
  "man office worker" -> "👨‍💼",
  "woman_office_worker" -> "👩‍💼",
  "woman-office-worker" -> "👩‍💼",
  "woman office worker" -> "👩‍💼",
  "scientist" -> "🧑‍🔬",
  "man_scientist" -> "👨‍🔬",
  "man-scientist" -> "👨‍🔬",
  "man scientist" -> "👨‍🔬",
  "woman_scientist" -> "👩‍🔬",
  "woman-scientist" -> "👩‍🔬",
  "woman scientist" -> "👩‍🔬",
  "technologist" -> "🧑‍💻",
  "man_technologist" -> "👨‍💻",
  "man-technologist" -> "👨‍💻",
  "man technologist" -> "👨‍💻",
  "woman_technologist" -> "👩‍💻",
  "woman-technologist" -> "👩‍💻",
  "woman technologist" -> "👩‍💻",
  "singer" -> "🧑‍🎤",
  "man_singer" -> "👨‍🎤",
  "man-singer" -> "👨‍🎤",
  "man singer" -> "👨‍🎤",
  "woman_singer" -> "👩‍🎤",
  "woman-singer" -> "👩‍🎤",
  "woman singer" -> "👩‍🎤",
  "artist" -> "🧑‍🎨",
  "man_artist" -> "👨‍🎨",
  "man-artist" -> "👨‍🎨",
  "man artist" -> "👨‍🎨",
  "woman_artist" -> "👩‍🎨",
  "woman-artist" -> "👩‍🎨",
  "woman artist" -> "👩‍🎨",
  "pilot" -> "🧑‍✈️",
  "man_pilot" -> "👨‍✈️",
  "man-pilot" -> "👨‍✈️",
  "man pilot" -> "👨‍✈️",
  "woman_pilot" -> "👩‍✈️",
  "woman-pilot" -> "👩‍✈️",
  "woman pilot" -> "👩‍✈️",
  "astronaut" -> "🧑‍🚀",
  "man_astronaut" -> "👨‍🚀",
  "man-astronaut" -> "👨‍🚀",
  "man astronaut" -> "👨‍🚀",
  "woman_astronaut" -> "👩‍🚀",
  "woman-astronaut" -> "👩‍🚀",
  "woman astronaut" -> "👩‍🚀",
  "firefighter" -> "🧑‍🚒",
  "man_firefighter" -> "👨‍🚒",
  "man-firefighter" -> "👨‍🚒",
  "man firefighter" -> "👨‍🚒",
  "woman_firefighter" -> "👩‍🚒",
  "woman-firefighter" -> "👩‍🚒",
  "woman firefighter" -> "👩‍🚒",
  "police_officer" -> "👮",
  "police-officer" -> "👮",
  "police officer" -> "👮",
  "cop" -> "👮",
  "man_police_officer" -> "👮‍♂️",
  "man-police-officer" -> "👮‍♂️",
  "man police officer" -> "👮‍♂️",
  "policeman" -> "👮‍♂️",
  "woman_police_officer" -> "👮‍♀️",
  "woman-police-officer" -> "👮‍♀️",
  "woman police officer" -> "👮‍♀️",
  "policewoman" -> "👮‍♀️",
  "detective" -> "🕵️",
  "man_detective" -> "🕵️‍♂️",
  "man-detective" -> "🕵️‍♂️",
  "man detective" -> "🕵️‍♂️",
  "male_detective" -> "🕵️‍♂️",
  "woman_detective" -> "🕵️‍♀️",
  "woman-detective" -> "🕵️‍♀️",
  "woman detective" -> "🕵️‍♀️",
  "female_detective" -> "🕵️‍♀️",
  "guard" -> "💂",
  "man_guard" -> "💂‍♂️",
  "man-guard" -> "💂‍♂️",
  "man guard" -> "💂‍♂️",
  "guardsman" -> "💂‍♂️",
  "woman_guard" -> "💂‍♀️",
  "woman-guard" -> "💂‍♀️",
  "woman guard" -> "💂‍♀️",
  "guardswoman" -> "💂‍♀️",
  "ninja" -> "🥷",
  "construction_worker" -> "👷",
  "construction-worker" -> "👷",
  "construction worker" -> "👷",
  "man_construction_worker" -> "👷‍♂️",
  "man-construction-worker" -> "👷‍♂️",
  "man construction worker" -> "👷‍♂️",
  "construction_worker_man" -> "👷‍♂️",
  "woman_construction_worker" -> "👷‍♀️",
  "woman-construction-worker" -> "👷‍♀️",
  "woman construction worker" -> "👷‍♀️",
  "construction_worker_woman" -> "👷‍♀️",
  "person_with_crown" -> "🫅",
  "person-with-crown" -> "🫅",
  "person with crown" -> "🫅",
  "prince" -> "🤴",
  "princess" -> "👸",
  "person_wearing_turban" -> "👳",
  "person-wearing-turban" -> "👳",
  "person wearing turban" -> "👳",
  "person_with_turban" -> "👳",
  "man_wearing_turban" -> "👳‍♂️",
  "man-wearing-turban" -> "👳‍♂️",
  "man wearing turban" -> "👳‍♂️",
  "man_with_turban" -> "👳‍♂️",
  "woman_wearing_turban" -> "👳‍♀️",
  "woman-wearing-turban" -> "👳‍♀️",
  "woman wearing turban" -> "👳‍♀️",
  "woman_with_turban" -> "👳‍♀️",
  "person_with_skullcap" -> "👲",
  "person-with-skullcap" -> "👲",
  "person with skullcap" -> "👲",
  "man_with_gua_pi_mao" -> "👲",
  "woman_with_headscarf" -> "🧕",
  "woman-with-headscarf" -> "🧕",
  "woman with headscarf" -> "🧕",
  "person_in_tuxedo" -> "🤵",
  "person-in-tuxedo" -> "🤵",
  "person in tuxedo" -> "🤵",
  "man_in_tuxedo" -> "🤵‍♂️",
  "man-in-tuxedo" -> "🤵‍♂️",
  "man in tuxedo" -> "🤵‍♂️",
  "woman_in_tuxedo" -> "🤵‍♀️",
  "woman-in-tuxedo" -> "🤵‍♀️",
  "woman in tuxedo" -> "🤵‍♀️",
  "person_with_veil" -> "👰",
  "person-with-veil" -> "👰",
  "person with veil" -> "👰",
  "man_with_veil" -> "👰‍♂️",
  "man-with-veil" -> "👰‍♂️",
  "man with veil" -> "👰‍♂️",
  "woman_with_veil" -> "👰‍♀️",
  "woman-with-veil" -> "👰‍♀️",
  "woman with veil" -> "👰‍♀️",
  "bride_with_veil" -> "👰‍♀️",
  "pregnant_woman" -> "🤰",
  "pregnant-woman" -> "🤰",
  "pregnant woman" -> "🤰",
  "pregnant_man" -> "🫃",
  "pregnant-man" -> "🫃",
  "pregnant man" -> "🫃",
  "pregnant_person" -> "🫄",
  "pregnant-person" -> "🫄",
  "pregnant person" -> "🫄",
  "breast-feeding" -> "🤱",
  "breast_feeding" -> "🤱",
  "woman_feeding_baby" -> "👩‍🍼",
  "woman-feeding-baby" -> "👩‍🍼",
  "woman feeding baby" -> "👩‍🍼",
  "man_feeding_baby" -> "👨‍🍼",
  "man-feeding-baby" -> "👨‍🍼",
  "man feeding baby" -> "👨‍🍼",
  "person_feeding_baby" -> "🧑‍🍼",
  "person-feeding-baby" -> "🧑‍🍼",
  "person feeding baby" -> "🧑‍🍼",
  "baby_angel" -> "👼",
  "baby-angel" -> "👼",
  "baby angel" -> "👼",
  "angel" -> "👼",
  "Santa_Claus" -> "🎅",
  "Santa-Claus" -> "🎅",
  "Santa Claus" -> "🎅",
  "santa" -> "🎅",
)
