package io.github.edadma.markdown

val emojiBlock1 = List(
  "grinning_face" -> "😀",
  "grinning-face" -> "😀",
  "grinning face" -> "😀",
  "grinning" -> "😀",
  "grinning_face_with_big_eyes" -> "😃",
  "grinning-face-with-big-eyes" -> "😃",
  "grinning face with big eyes" -> "😃",
  "smiley" -> "😃",
  "grinning_face_with_smiling_eyes" -> "😄",
  "grinning-face-with-smiling-eyes" -> "😄",
  "grinning face with smiling eyes" -> "😄",
  "smile" -> "😄",
  "beaming_face_with_smiling_eyes" -> "😁",
  "beaming-face-with-smiling-eyes" -> "😁",
  "beaming face with smiling eyes" -> "😁",
  "grin" -> "😁",
  "grinning_squinting_face" -> "😆",
  "grinning-squinting-face" -> "😆",
  "grinning squinting face" -> "😆",
  "laughing" -> "😆",
  "satisfied" -> "😆",
  "grinning_face_with_sweat" -> "😅",
  "grinning-face-with-sweat" -> "😅",
  "grinning face with sweat" -> "😅",
  "sweat_smile" -> "😅",
  "rolling_on_the_floor_laughing" -> "🤣",
  "rolling-on-the-floor-laughing" -> "🤣",
  "rolling on the floor laughing" -> "🤣",
  "rofl" -> "🤣",
  "face_with_tears_of_joy" -> "😂",
  "face-with-tears-of-joy" -> "😂",
  "face with tears of joy" -> "😂",
  "joy" -> "😂",
  "slightly_smiling_face" -> "🙂",
  "slightly-smiling-face" -> "🙂",
  "slightly smiling face" -> "🙂",
  "upside-down_face" -> "🙃",
  "upside-down-face" -> "🙃",
  "upside-down face" -> "🙃",
  "upside_down_face" -> "🙃",
  "melting_face" -> "🫠",
  "melting-face" -> "🫠",
  "melting face" -> "🫠",
  "winking_face" -> "😉",
  "winking-face" -> "😉",
  "winking face" -> "😉",
  "wink" -> "😉",
  "smiling_face_with_smiling_eyes" -> "😊",
  "smiling-face-with-smiling-eyes" -> "😊",
  "smiling face with smiling eyes" -> "😊",
  "blush" -> "😊",
  "smiling_face_with_halo" -> "😇",
  "smiling-face-with-halo" -> "😇",
  "smiling face with halo" -> "😇",
  "innocent" -> "😇",
  "smiling_face_with_hearts" -> "🥰",
  "smiling-face-with-hearts" -> "🥰",
  "smiling face with hearts" -> "🥰",
  "smiling_face_with_three_hearts" -> "🥰",
  "smiling_face_with_heart-eyes" -> "😍",
  "smiling-face-with-heart-eyes" -> "😍",
  "smiling face with heart-eyes" -> "😍",
  "heart_eyes" -> "😍",
  "star-struck" -> "🤩",
  "star_struck" -> "🤩",
  "face_blowing_a_kiss" -> "😘",
  "face-blowing-a-kiss" -> "😘",
  "face blowing a kiss" -> "😘",
  "kissing_heart" -> "😘",
  "kissing_face" -> "😗",
  "kissing-face" -> "😗",
  "kissing face" -> "😗",
  "kissing" -> "😗",
  "smiling_face" -> "☺️",
  "smiling-face" -> "☺️",
  "smiling face" -> "☺️",
  "relaxed" -> "☺️",
  "kissing_face_with_closed_eyes" -> "😚",
  "kissing-face-with-closed-eyes" -> "😚",
  "kissing face with closed eyes" -> "😚",
  "kissing_closed_eyes" -> "😚",
  "kissing_face_with_smiling_eyes" -> "😙",
  "kissing-face-with-smiling-eyes" -> "😙",
  "kissing face with smiling eyes" -> "😙",
  "kissing_smiling_eyes" -> "😙",
  "smiling_face_with_tear" -> "🥲",
  "smiling-face-with-tear" -> "🥲",
  "smiling face with tear" -> "🥲",
  "face_savoring_food" -> "😋",
  "face-savoring-food" -> "😋",
  "face savoring food" -> "😋",
  "yum" -> "😋",
  "face_with_tongue" -> "😛",
  "face-with-tongue" -> "😛",
  "face with tongue" -> "😛",
  "stuck_out_tongue" -> "😛",
  "winking_face_with_tongue" -> "😜",
  "winking-face-with-tongue" -> "😜",
  "winking face with tongue" -> "😜",
  "stuck_out_tongue_winking_eye" -> "😜",
  "zany_face" -> "🤪",
  "zany-face" -> "🤪",
  "zany face" -> "🤪",
  "squinting_face_with_tongue" -> "😝",
  "squinting-face-with-tongue" -> "😝",
  "squinting face with tongue" -> "😝",
  "stuck_out_tongue_closed_eyes" -> "😝",
  "money-mouth_face" -> "🤑",
  "money-mouth-face" -> "🤑",
  "money-mouth face" -> "🤑",
  "money_mouth_face" -> "🤑",
  "smiling_face_with_open_hands" -> "🤗",
  "smiling-face-with-open-hands" -> "🤗",
  "smiling face with open hands" -> "🤗",
  "hugs" -> "🤗",
  "face_with_hand_over_mouth" -> "🤭",
  "face-with-hand-over-mouth" -> "🤭",
  "face with hand over mouth" -> "🤭",
  "hand_over_mouth" -> "🤭",
  "face_with_open_eyes_and_hand_over_mouth" -> "🫢",
  "face-with-open-eyes-and-hand-over-mouth" -> "🫢",
  "face with open eyes and hand over mouth" -> "🫢",
  "face_with_peeking_eye" -> "🫣",
  "face-with-peeking-eye" -> "🫣",
  "face with peeking eye" -> "🫣",
  "shushing_face" -> "🤫",
  "shushing-face" -> "🤫",
  "shushing face" -> "🤫",
  "thinking_face" -> "🤔",
  "thinking-face" -> "🤔",
  "thinking face" -> "🤔",
  "thinking" -> "🤔",
  "saluting_face" -> "🫡",
  "saluting-face" -> "🫡",
  "saluting face" -> "🫡",
  "zipper-mouth_face" -> "🤐",
  "zipper-mouth-face" -> "🤐",
  "zipper-mouth face" -> "🤐",
  "zipper_mouth_face" -> "🤐",
  "face_with_raised_eyebrow" -> "🤨",
  "face-with-raised-eyebrow" -> "🤨",
  "face with raised eyebrow" -> "🤨",
  "raised_eyebrow" -> "🤨",
  "neutral_face" -> "😐",
  "neutral-face" -> "😐",
  "neutral face" -> "😐",
  "expressionless_face" -> "😑",
  "expressionless-face" -> "😑",
  "expressionless face" -> "😑",
  "expressionless" -> "😑",
  "face_without_mouth" -> "😶",
  "face-without-mouth" -> "😶",
  "face without mouth" -> "😶",
  "no_mouth" -> "😶",
  "dotted_line_face" -> "🫥",
  "dotted-line-face" -> "🫥",
  "dotted line face" -> "🫥",
  "face_in_clouds" -> "😶‍🌫️",
  "face-in-clouds" -> "😶‍🌫️",
  "face in clouds" -> "😶‍🌫️",
  "smirking_face" -> "😏",
  "smirking-face" -> "😏",
  "smirking face" -> "😏",
  "smirk" -> "😏",
  "unamused_face" -> "😒",
  "unamused-face" -> "😒",
  "unamused face" -> "😒",
  "unamused" -> "😒",
  "face_with_rolling_eyes" -> "🙄",
  "face-with-rolling-eyes" -> "🙄",
  "face with rolling eyes" -> "🙄",
  "roll_eyes" -> "🙄",
  "grimacing_face" -> "😬",
  "grimacing-face" -> "😬",
  "grimacing face" -> "😬",
  "grimacing" -> "😬",
  "face_exhaling" -> "😮‍💨",
  "face-exhaling" -> "😮‍💨",
  "face exhaling" -> "😮‍💨",
  "lying_face" -> "🤥",
  "lying-face" -> "🤥",
  "lying face" -> "🤥",
  "shaking_face" -> "🫨",
  "shaking-face" -> "🫨",
  "shaking face" -> "🫨",
  "relieved_face" -> "😌",
  "relieved-face" -> "😌",
  "relieved face" -> "😌",
  "relieved" -> "😌",
  "pensive_face" -> "😔",
  "pensive-face" -> "😔",
  "pensive face" -> "😔",
  "pensive" -> "😔",
  "sleepy_face" -> "😪",
  "sleepy-face" -> "😪",
  "sleepy face" -> "😪",
  "sleepy" -> "😪",
  "drooling_face" -> "🤤",
  "drooling-face" -> "🤤",
  "drooling face" -> "🤤",
  "sleeping_face" -> "😴",
  "sleeping-face" -> "😴",
  "sleeping face" -> "😴",
  "sleeping" -> "😴",
  "face_with_medical_mask" -> "😷",
  "face-with-medical-mask" -> "😷",
  "face with medical mask" -> "😷",
  "mask" -> "😷",
  "face_with_thermometer" -> "🤒",
  "face-with-thermometer" -> "🤒",
  "face with thermometer" -> "🤒",
  "face_with_head-bandage" -> "🤕",
  "face-with-head-bandage" -> "🤕",
  "face with head-bandage" -> "🤕",
  "face_with_head_bandage" -> "🤕",
  "nauseated_face" -> "🤢",
  "nauseated-face" -> "🤢",
  "nauseated face" -> "🤢",
  "face_vomiting" -> "🤮",
  "face-vomiting" -> "🤮",
  "face vomiting" -> "🤮",
  "vomiting_face" -> "🤮",
  "sneezing_face" -> "🤧",
  "sneezing-face" -> "🤧",
  "sneezing face" -> "🤧",
  "hot_face" -> "🥵",
  "hot-face" -> "🥵",
  "hot face" -> "🥵",
  "cold_face" -> "🥶",
  "cold-face" -> "🥶",
  "cold face" -> "🥶",
  "woozy_face" -> "🥴",
  "woozy-face" -> "🥴",
  "woozy face" -> "🥴",
  "face_with_crossed-out_eyes" -> "😵",
  "face-with-crossed-out-eyes" -> "😵",
  "face with crossed-out eyes" -> "😵",
  "dizzy_face" -> "😵",
  "face_with_spiral_eyes" -> "😵‍💫",
  "face-with-spiral-eyes" -> "😵‍💫",
  "face with spiral eyes" -> "😵‍💫",
  "exploding_head" -> "🤯",
  "exploding-head" -> "🤯",
  "exploding head" -> "🤯",
  "cowboy_hat_face" -> "🤠",
  "cowboy-hat-face" -> "🤠",
  "cowboy hat face" -> "🤠",
  "partying_face" -> "🥳",
  "partying-face" -> "🥳",
  "partying face" -> "🥳",
  "disguised_face" -> "🥸",
  "disguised-face" -> "🥸",
  "disguised face" -> "🥸",
  "smiling_face_with_sunglasses" -> "😎",
  "smiling-face-with-sunglasses" -> "😎",
  "smiling face with sunglasses" -> "😎",
  "sunglasses" -> "😎",
  "nerd_face" -> "🤓",
  "nerd-face" -> "🤓",
  "nerd face" -> "🤓",
  "face_with_monocle" -> "🧐",
  "face-with-monocle" -> "🧐",
  "face with monocle" -> "🧐",
  "monocle_face" -> "🧐",
  "confused_face" -> "😕",
  "confused-face" -> "😕",
  "confused face" -> "😕",
  "confused" -> "😕",
  "face_with_diagonal_mouth" -> "🫤",
  "face-with-diagonal-mouth" -> "🫤",
  "face with diagonal mouth" -> "🫤",
  "worried_face" -> "😟",
  "worried-face" -> "😟",
  "worried face" -> "😟",
  "worried" -> "😟",
  "slightly_frowning_face" -> "🙁",
  "slightly-frowning-face" -> "🙁",
  "slightly frowning face" -> "🙁",
  "frowning_face" -> "☹️",
  "frowning-face" -> "☹️",
  "frowning face" -> "☹️",
  "face_with_open_mouth" -> "😮",
  "face-with-open-mouth" -> "😮",
  "face with open mouth" -> "😮",
  "open_mouth" -> "😮",
  "hushed_face" -> "😯",
  "hushed-face" -> "😯",
  "hushed face" -> "😯",
  "hushed" -> "😯",
  "astonished_face" -> "😲",
  "astonished-face" -> "😲",
  "astonished face" -> "😲",
  "astonished" -> "😲",
  "flushed_face" -> "😳",
  "flushed-face" -> "😳",
  "flushed face" -> "😳",
  "flushed" -> "😳",
  "pleading_face" -> "🥺",
  "pleading-face" -> "🥺",
  "pleading face" -> "🥺",
)
