package io.github.edadma.markdown

val emojiBlock15 = List(
  "A button (blood type)" -> "🅰️",
  "a" -> "🅰️",
  "AB_button_(blood_type)" -> "🆎",
  "AB-button-(blood-type)" -> "🆎",
  "AB button (blood type)" -> "🆎",
  "ab" -> "🆎",
  "B_button_(blood_type)" -> "🅱️",
  "B-button-(blood-type)" -> "🅱️",
  "B button (blood type)" -> "🅱️",
  "b" -> "🅱️",
  "CL_button" -> "🆑",
  "CL-button" -> "🆑",
  "CL button" -> "🆑",
  "cl" -> "🆑",
  "COOL_button" -> "🆒",
  "COOL-button" -> "🆒",
  "COOL button" -> "🆒",
  "cool" -> "🆒",
  "FREE_button" -> "🆓",
  "FREE-button" -> "🆓",
  "FREE button" -> "🆓",
  "free" -> "🆓",
  "information" -> "ℹ️",
  "information_source" -> "ℹ️",
  "ID_button" -> "🆔",
  "ID-button" -> "🆔",
  "ID button" -> "🆔",
  "id" -> "🆔",
  "circled_M" -> "Ⓜ️",
  "circled-M" -> "Ⓜ️",
  "circled M" -> "Ⓜ️",
  "m" -> "Ⓜ️",
  "NEW_button" -> "🆕",
  "NEW-button" -> "🆕",
  "NEW button" -> "🆕",
  "new" -> "🆕",
  "NG_button" -> "🆖",
  "NG-button" -> "🆖",
  "NG button" -> "🆖",
  "ng" -> "🆖",
  "O_button_(blood_type)" -> "🅾️",
  "O-button-(blood-type)" -> "🅾️",
  "O button (blood type)" -> "🅾️",
  "o2" -> "🅾️",
  "OK_button" -> "🆗",
  "OK-button" -> "🆗",
  "OK button" -> "🆗",
  "ok" -> "🆗",
  "P_button" -> "🅿️",
  "P-button" -> "🅿️",
  "P button" -> "🅿️",
  "parking" -> "🅿️",
  "SOS_button" -> "🆘",
  "SOS-button" -> "🆘",
  "SOS button" -> "🆘",
  "sos" -> "🆘",
  "UP!_button" -> "🆙",
  "UP!-button" -> "🆙",
  "UP! button" -> "🆙",
  "up" -> "🆙",
  "VS_button" -> "🆚",
  "VS-button" -> "🆚",
  "VS button" -> "🆚",
  "vs" -> "🆚",
  "Japanese_“here”_button" -> "🈁",
  "Japanese-“here”-button" -> "🈁",
  "Japanese “here” button" -> "🈁",
  "koko" -> "🈁",
  "Japanese_“service_charge”_button" -> "🈂️",
  "Japanese-“service-charge”-button" -> "🈂️",
  "Japanese “service charge” button" -> "🈂️",
  "sa" -> "🈂️",
  "Japanese_“monthly_amount”_button" -> "🈷️",
  "Japanese-“monthly-amount”-button" -> "🈷️",
  "Japanese “monthly amount” button" -> "🈷️",
  "u6708" -> "🈷️",
  "Japanese_“not_free_of_charge”_button" -> "🈶",
  "Japanese-“not-free-of-charge”-button" -> "🈶",
  "Japanese “not free of charge” button" -> "🈶",
  "u6709" -> "🈶",
  "Japanese_“reserved”_button" -> "🈯",
  "Japanese-“reserved”-button" -> "🈯",
  "Japanese “reserved” button" -> "🈯",
  "u6307" -> "🈯",
  "Japanese_“bargain”_button" -> "🉐",
  "Japanese-“bargain”-button" -> "🉐",
  "Japanese “bargain” button" -> "🉐",
  "ideograph_advantage" -> "🉐",
  "Japanese_“discount”_button" -> "🈹",
  "Japanese-“discount”-button" -> "🈹",
  "Japanese “discount” button" -> "🈹",
  "u5272" -> "🈹",
  "Japanese_“free_of_charge”_button" -> "🈚",
  "Japanese-“free-of-charge”-button" -> "🈚",
  "Japanese “free of charge” button" -> "🈚",
  "u7121" -> "🈚",
  "Japanese_“prohibited”_button" -> "🈲",
  "Japanese-“prohibited”-button" -> "🈲",
  "Japanese “prohibited” button" -> "🈲",
  "u7981" -> "🈲",
  "Japanese_“acceptable”_button" -> "🉑",
  "Japanese-“acceptable”-button" -> "🉑",
  "Japanese “acceptable” button" -> "🉑",
  "accept" -> "🉑",
  "Japanese_“application”_button" -> "🈸",
  "Japanese-“application”-button" -> "🈸",
  "Japanese “application” button" -> "🈸",
  "u7533" -> "🈸",
  "Japanese_“passing_grade”_button" -> "🈴",
  "Japanese-“passing-grade”-button" -> "🈴",
  "Japanese “passing grade” button" -> "🈴",
  "u5408" -> "🈴",
  "Japanese_“vacancy”_button" -> "🈳",
  "Japanese-“vacancy”-button" -> "🈳",
  "Japanese “vacancy” button" -> "🈳",
  "u7a7a" -> "🈳",
  "Japanese_“congratulations”_button" -> "㊗️",
  "Japanese-“congratulations”-button" -> "㊗️",
  "Japanese “congratulations” button" -> "㊗️",
  "congratulations" -> "㊗️",
  "Japanese_“secret”_button" -> "㊙️",
  "Japanese-“secret”-button" -> "㊙️",
  "Japanese “secret” button" -> "㊙️",
  "secret" -> "㊙️",
  "Japanese_“open_for_business”_button" -> "🈺",
  "Japanese-“open-for-business”-button" -> "🈺",
  "Japanese “open for business” button" -> "🈺",
  "u55b6" -> "🈺",
  "Japanese_“no_vacancy”_button" -> "🈵",
  "Japanese-“no-vacancy”-button" -> "🈵",
  "Japanese “no vacancy” button" -> "🈵",
  "u6e80" -> "🈵",
  "red_circle" -> "🔴",
  "red-circle" -> "🔴",
  "red circle" -> "🔴",
  "orange_circle" -> "🟠",
  "orange-circle" -> "🟠",
  "orange circle" -> "🟠",
  "yellow_circle" -> "🟡",
  "yellow-circle" -> "🟡",
  "yellow circle" -> "🟡",
  "green_circle" -> "🟢",
  "green-circle" -> "🟢",
  "green circle" -> "🟢",
  "blue_circle" -> "🔵",
  "blue-circle" -> "🔵",
  "blue circle" -> "🔵",
  "large_blue_circle" -> "🔵",
  "purple_circle" -> "🟣",
  "purple-circle" -> "🟣",
  "purple circle" -> "🟣",
  "brown_circle" -> "🟤",
  "brown-circle" -> "🟤",
  "brown circle" -> "🟤",
  "black_circle" -> "⚫",
  "black-circle" -> "⚫",
  "black circle" -> "⚫",
  "white_circle" -> "⚪",
  "white-circle" -> "⚪",
  "white circle" -> "⚪",
  "red_square" -> "🟥",
  "red-square" -> "🟥",
  "red square" -> "🟥",
  "orange_square" -> "🟧",
  "orange-square" -> "🟧",
  "orange square" -> "🟧",
  "yellow_square" -> "🟨",
  "yellow-square" -> "🟨",
  "yellow square" -> "🟨",
  "green_square" -> "🟩",
  "green-square" -> "🟩",
  "green square" -> "🟩",
  "blue_square" -> "🟦",
  "blue-square" -> "🟦",
  "blue square" -> "🟦",
  "purple_square" -> "🟪",
  "purple-square" -> "🟪",
  "purple square" -> "🟪",
  "brown_square" -> "🟫",
  "brown-square" -> "🟫",
  "brown square" -> "🟫",
  "black_large_square" -> "⬛",
  "black-large-square" -> "⬛",
  "black large square" -> "⬛",
  "white_large_square" -> "⬜",
  "white-large-square" -> "⬜",
  "white large square" -> "⬜",
  "black_medium_square" -> "◼️",
  "black-medium-square" -> "◼️",
  "black medium square" -> "◼️",
  "white_medium_square" -> "◻️",
  "white-medium-square" -> "◻️",
  "white medium square" -> "◻️",
  "black_medium-small_square" -> "◾",
  "black-medium-small-square" -> "◾",
  "black medium-small square" -> "◾",
  "black_medium_small_square" -> "◾",
  "white_medium-small_square" -> "◽",
  "white-medium-small-square" -> "◽",
  "white medium-small square" -> "◽",
  "white_medium_small_square" -> "◽",
  "black_small_square" -> "▪️",
  "black-small-square" -> "▪️",
  "black small square" -> "▪️",
  "white_small_square" -> "▫️",
  "white-small-square" -> "▫️",
  "white small square" -> "▫️",
  "large_orange_diamond" -> "🔶",
  "large-orange-diamond" -> "🔶",
  "large orange diamond" -> "🔶",
  "large_blue_diamond" -> "🔷",
  "large-blue-diamond" -> "🔷",
  "large blue diamond" -> "🔷",
  "small_orange_diamond" -> "🔸",
  "small-orange-diamond" -> "🔸",
  "small orange diamond" -> "🔸",
  "small_blue_diamond" -> "🔹",
  "small-blue-diamond" -> "🔹",
  "small blue diamond" -> "🔹",
  "red_triangle_pointed_up" -> "🔺",
  "red-triangle-pointed-up" -> "🔺",
  "red triangle pointed up" -> "🔺",
  "small_red_triangle" -> "🔺",
  "red_triangle_pointed_down" -> "🔻",
  "red-triangle-pointed-down" -> "🔻",
  "red triangle pointed down" -> "🔻",
  "small_red_triangle_down" -> "🔻",
  "diamond_with_a_dot" -> "💠",
  "diamond-with-a-dot" -> "💠",
  "diamond with a dot" -> "💠",
  "diamond_shape_with_a_dot_inside" -> "💠",
  "radio_button" -> "🔘",
  "radio-button" -> "🔘",
  "radio button" -> "🔘",
  "white_square_button" -> "🔳",
  "white-square-button" -> "🔳",
  "white square button" -> "🔳",
  "black_square_button" -> "🔲",
  "black-square-button" -> "🔲",
  "black square button" -> "🔲",
  "chequered_flag" -> "🏁",
  "chequered-flag" -> "🏁",
  "chequered flag" -> "🏁",
  "checkered_flag" -> "🏁",
  "triangular_flag" -> "🚩",
  "triangular-flag" -> "🚩",
  "triangular flag" -> "🚩",
  "triangular_flag_on_post" -> "🚩",
  "crossed_flags" -> "🎌",
  "crossed-flags" -> "🎌",
  "crossed flags" -> "🎌",
  "black_flag" -> "🏴",
  "black-flag" -> "🏴",
  "black flag" -> "🏴",
  "white_flag" -> "🏳️",
  "white-flag" -> "🏳️",
  "white flag" -> "🏳️",
  "rainbow_flag" -> "🏳️‍🌈",
  "rainbow-flag" -> "🏳️‍🌈",
  "rainbow flag" -> "🏳️‍🌈",
  "transgender_flag" -> "🏳️‍⚧️",
  "transgender-flag" -> "🏳️‍⚧️",
  "transgender flag" -> "🏳️‍⚧️",
  "pirate_flag" -> "🏴‍☠️",
  "pirate-flag" -> "🏴‍☠️",
  "pirate flag" -> "🏴‍☠️",
  "flag_Ascension_Island" -> "🇦🇨",
  "flag-Ascension-Island" -> "🇦🇨",
  "flag Ascension Island" -> "🇦🇨",
  "ascension_island" -> "🇦🇨",
  "flag_Andorra" -> "🇦🇩",
  "flag-Andorra" -> "🇦🇩",
  "flag Andorra" -> "🇦🇩",
  "andorra" -> "🇦🇩",
  "flag_United_Arab_Emirates" -> "🇦🇪",
  "flag-United-Arab-Emirates" -> "🇦🇪",
  "flag United Arab Emirates" -> "🇦🇪",
  "united_arab_emirates" -> "🇦🇪",
  "flag_Afghanistan" -> "🇦🇫",
  "flag-Afghanistan" -> "🇦🇫",
  "flag Afghanistan" -> "🇦🇫",
  "afghanistan" -> "🇦🇫",
  "flag_Antigua_&_Barbuda" -> "🇦🇬",
  "flag-Antigua-&-Barbuda" -> "🇦🇬",
  "flag Antigua & Barbuda" -> "🇦🇬",
  "antigua_barbuda" -> "🇦🇬",
  "flag_Anguilla" -> "🇦🇮",
  "flag-Anguilla" -> "🇦🇮",
  "flag Anguilla" -> "🇦🇮",
  "anguilla" -> "🇦🇮",
  "flag_Albania" -> "🇦🇱",
  "flag-Albania" -> "🇦🇱",
  "flag Albania" -> "🇦🇱",
  "albania" -> "🇦🇱",
  "flag_Armenia" -> "🇦🇲",
  "flag-Armenia" -> "🇦🇲",
  "flag Armenia" -> "🇦🇲",
  "armenia" -> "🇦🇲",
  "flag_Angola" -> "🇦🇴",
  "flag-Angola" -> "🇦🇴",
)
