package io.github.edadma.markdown

val emojiBlock13 = List(
  "clamp" -> "🗜️",
  "balance_scale" -> "⚖️",
  "balance-scale" -> "⚖️",
  "balance scale" -> "⚖️",
  "white_cane" -> "🦯",
  "white-cane" -> "🦯",
  "white cane" -> "🦯",
  "probing_cane" -> "🦯",
  "link" -> "🔗",
  "chains" -> "⛓️",
  "hook" -> "🪝",
  "toolbox" -> "🧰",
  "magnet" -> "🧲",
  "ladder" -> "🪜",
  "alembic" -> "⚗️",
  "test_tube" -> "🧪",
  "test-tube" -> "🧪",
  "test tube" -> "🧪",
  "petri_dish" -> "🧫",
  "petri-dish" -> "🧫",
  "petri dish" -> "🧫",
  "dna" -> "🧬",
  "microscope" -> "🔬",
  "telescope" -> "🔭",
  "satellite_antenna" -> "📡",
  "satellite-antenna" -> "📡",
  "satellite antenna" -> "📡",
  "satellite" -> "📡",
  "syringe" -> "💉",
  "drop_of_blood" -> "🩸",
  "drop-of-blood" -> "🩸",
  "drop of blood" -> "🩸",
  "pill" -> "💊",
  "adhesive_bandage" -> "🩹",
  "adhesive-bandage" -> "🩹",
  "adhesive bandage" -> "🩹",
  "crutch" -> "🩼",
  "stethoscope" -> "🩺",
  "x-ray" -> "🩻",
  "x_ray" -> "🩻",
  "door" -> "🚪",
  "elevator" -> "🛗",
  "mirror" -> "🪞",
  "window" -> "🪟",
  "bed" -> "🛏️",
  "couch_and_lamp" -> "🛋️",
  "couch-and-lamp" -> "🛋️",
  "couch and lamp" -> "🛋️",
  "chair" -> "🪑",
  "toilet" -> "🚽",
  "plunger" -> "🪠",
  "shower" -> "🚿",
  "bathtub" -> "🛁",
  "mouse_trap" -> "🪤",
  "mouse-trap" -> "🪤",
  "mouse trap" -> "🪤",
  "razor" -> "🪒",
  "lotion_bottle" -> "🧴",
  "lotion-bottle" -> "🧴",
  "lotion bottle" -> "🧴",
  "safety_pin" -> "🧷",
  "safety-pin" -> "🧷",
  "safety pin" -> "🧷",
  "broom" -> "🧹",
  "basket" -> "🧺",
  "roll_of_paper" -> "🧻",
  "roll-of-paper" -> "🧻",
  "roll of paper" -> "🧻",
  "bucket" -> "🪣",
  "soap" -> "🧼",
  "bubbles" -> "🫧",
  "toothbrush" -> "🪥",
  "sponge" -> "🧽",
  "fire_extinguisher" -> "🧯",
  "fire-extinguisher" -> "🧯",
  "fire extinguisher" -> "🧯",
  "shopping_cart" -> "🛒",
  "shopping-cart" -> "🛒",
  "shopping cart" -> "🛒",
  "cigarette" -> "🚬",
  "smoking" -> "🚬",
  "coffin" -> "⚰️",
  "headstone" -> "🪦",
  "funeral_urn" -> "⚱️",
  "funeral-urn" -> "⚱️",
  "funeral urn" -> "⚱️",
  "nazar_amulet" -> "🧿",
  "nazar-amulet" -> "🧿",
  "nazar amulet" -> "🧿",
  "hamsa" -> "🪬",
  "moai" -> "🗿",
  "moyai" -> "🗿",
  "placard" -> "🪧",
  "identification_card" -> "🪪",
  "identification-card" -> "🪪",
  "identification card" -> "🪪",
  "ATM_sign" -> "🏧",
  "ATM-sign" -> "🏧",
  "ATM sign" -> "🏧",
  "atm" -> "🏧",
  "litter_in_bin_sign" -> "🚮",
  "litter-in-bin-sign" -> "🚮",
  "litter in bin sign" -> "🚮",
  "put_litter_in_its_place" -> "🚮",
  "potable_water" -> "🚰",
  "potable-water" -> "🚰",
  "potable water" -> "🚰",
  "wheelchair_symbol" -> "♿",
  "wheelchair-symbol" -> "♿",
  "wheelchair symbol" -> "♿",
  "wheelchair" -> "♿",
  "men’s_room" -> "🚹",
  "men’s-room" -> "🚹",
  "men’s room" -> "🚹",
  "mens" -> "🚹",
  "women’s_room" -> "🚺",
  "women’s-room" -> "🚺",
  "women’s room" -> "🚺",
  "womens" -> "🚺",
  "restroom" -> "🚻",
  "baby_symbol" -> "🚼",
  "baby-symbol" -> "🚼",
  "baby symbol" -> "🚼",
  "water_closet" -> "🚾",
  "water-closet" -> "🚾",
  "water closet" -> "🚾",
  "wc" -> "🚾",
  "passport_control" -> "🛂",
  "passport-control" -> "🛂",
  "passport control" -> "🛂",
  "customs" -> "🛃",
  "baggage_claim" -> "🛄",
  "baggage-claim" -> "🛄",
  "baggage claim" -> "🛄",
  "left_luggage" -> "🛅",
  "left-luggage" -> "🛅",
  "left luggage" -> "🛅",
  "warning" -> "⚠️",
  "children_crossing" -> "🚸",
  "children-crossing" -> "🚸",
  "children crossing" -> "🚸",
  "no_entry" -> "⛔",
  "no-entry" -> "⛔",
  "no entry" -> "⛔",
  "prohibited" -> "🚫",
  "no_entry_sign" -> "🚫",
  "no_bicycles" -> "🚳",
  "no-bicycles" -> "🚳",
  "no bicycles" -> "🚳",
  "no_smoking" -> "🚭",
  "no-smoking" -> "🚭",
  "no smoking" -> "🚭",
  "no_littering" -> "🚯",
  "no-littering" -> "🚯",
  "no littering" -> "🚯",
  "do_not_litter" -> "🚯",
  "non-potable_water" -> "🚱",
  "non-potable-water" -> "🚱",
  "non-potable water" -> "🚱",
  "no_pedestrians" -> "🚷",
  "no-pedestrians" -> "🚷",
  "no pedestrians" -> "🚷",
  "no_mobile_phones" -> "📵",
  "no-mobile-phones" -> "📵",
  "no mobile phones" -> "📵",
  "no_one_under_eighteen" -> "🔞",
  "no-one-under-eighteen" -> "🔞",
  "no one under eighteen" -> "🔞",
  "underage" -> "🔞",
  "radioactive" -> "☢️",
  "biohazard" -> "☣️",
  "up_arrow" -> "⬆️",
  "up-arrow" -> "⬆️",
  "up arrow" -> "⬆️",
  "arrow_up" -> "⬆️",
  "up-right_arrow" -> "↗️",
  "up-right-arrow" -> "↗️",
  "up-right arrow" -> "↗️",
  "arrow_upper_right" -> "↗️",
  "right_arrow" -> "➡️",
  "right-arrow" -> "➡️",
  "right arrow" -> "➡️",
  "arrow_right" -> "➡️",
  "down-right_arrow" -> "↘️",
  "down-right-arrow" -> "↘️",
  "down-right arrow" -> "↘️",
  "arrow_lower_right" -> "↘️",
  "down_arrow" -> "⬇️",
  "down-arrow" -> "⬇️",
  "down arrow" -> "⬇️",
  "arrow_down" -> "⬇️",
  "down-left_arrow" -> "↙️",
  "down-left-arrow" -> "↙️",
  "down-left arrow" -> "↙️",
  "arrow_lower_left" -> "↙️",
  "left_arrow" -> "⬅️",
  "left-arrow" -> "⬅️",
  "left arrow" -> "⬅️",
  "arrow_left" -> "⬅️",
  "up-left_arrow" -> "↖️",
  "up-left-arrow" -> "↖️",
  "up-left arrow" -> "↖️",
  "arrow_upper_left" -> "↖️",
  "up-down_arrow" -> "↕️",
  "up-down-arrow" -> "↕️",
  "up-down arrow" -> "↕️",
  "arrow_up_down" -> "↕️",
  "left-right_arrow" -> "↔️",
  "left-right-arrow" -> "↔️",
  "left-right arrow" -> "↔️",
  "left_right_arrow" -> "↔️",
  "right_arrow_curving_left" -> "↩️",
  "right-arrow-curving-left" -> "↩️",
  "right arrow curving left" -> "↩️",
  "leftwards_arrow_with_hook" -> "↩️",
  "left_arrow_curving_right" -> "↪️",
  "left-arrow-curving-right" -> "↪️",
  "left arrow curving right" -> "↪️",
  "arrow_right_hook" -> "↪️",
  "right_arrow_curving_up" -> "⤴️",
  "right-arrow-curving-up" -> "⤴️",
  "right arrow curving up" -> "⤴️",
  "arrow_heading_up" -> "⤴️",
  "right_arrow_curving_down" -> "⤵️",
  "right-arrow-curving-down" -> "⤵️",
  "right arrow curving down" -> "⤵️",
  "arrow_heading_down" -> "⤵️",
  "clockwise_vertical_arrows" -> "🔃",
  "clockwise-vertical-arrows" -> "🔃",
  "clockwise vertical arrows" -> "🔃",
  "arrows_clockwise" -> "🔃",
  "counterclockwise_arrows_button" -> "🔄",
  "counterclockwise-arrows-button" -> "🔄",
  "counterclockwise arrows button" -> "🔄",
  "arrows_counterclockwise" -> "🔄",
  "BACK_arrow" -> "🔙",
  "BACK-arrow" -> "🔙",
  "BACK arrow" -> "🔙",
  "back" -> "🔙",
  "END_arrow" -> "🔚",
  "END-arrow" -> "🔚",
  "END arrow" -> "🔚",
  "end" -> "🔚",
  "ON!_arrow" -> "🔛",
  "ON!-arrow" -> "🔛",
  "ON! arrow" -> "🔛",
  "on" -> "🔛",
  "SOON_arrow" -> "🔜",
  "SOON-arrow" -> "🔜",
  "SOON arrow" -> "🔜",
  "soon" -> "🔜",
  "TOP_arrow" -> "🔝",
  "TOP-arrow" -> "🔝",
  "TOP arrow" -> "🔝",
  "top" -> "🔝",
  "place_of_worship" -> "🛐",
  "place-of-worship" -> "🛐",
  "place of worship" -> "🛐",
  "atom_symbol" -> "⚛️",
  "atom-symbol" -> "⚛️",
  "atom symbol" -> "⚛️",
  "om" -> "🕉️",
  "star_of_David" -> "✡️",
  "star-of-David" -> "✡️",
  "star of David" -> "✡️",
  "star_of_david" -> "✡️",
  "wheel_of_dharma" -> "☸️",
  "wheel-of-dharma" -> "☸️",
  "wheel of dharma" -> "☸️",
  "yin_yang" -> "☯️",
  "yin-yang" -> "☯️",
  "yin yang" -> "☯️",
  "latin_cross" -> "✝️",
  "latin-cross" -> "✝️",
  "latin cross" -> "✝️",
  "orthodox_cross" -> "☦️",
  "orthodox-cross" -> "☦️",
  "orthodox cross" -> "☦️",
  "star_and_crescent" -> "☪️",
  "star-and-crescent" -> "☪️",
  "star and crescent" -> "☪️",
  "peace_symbol" -> "☮️",
  "peace-symbol" -> "☮️",
  "peace symbol" -> "☮️",
  "menorah" -> "🕎",
  "dotted_six-pointed_star" -> "🔯",
  "dotted-six-pointed-star" -> "🔯",
  "dotted six-pointed star" -> "🔯",
  "six_pointed_star" -> "🔯",
  "khanda" -> "🪯",
  "Aries" -> "♈",
  "aries" -> "♈",
  "Taurus" -> "♉",
  "taurus" -> "♉",
  "Gemini" -> "♊",
  "gemini" -> "♊",
  "Cancer" -> "♋",
  "cancer" -> "♋",
  "Leo" -> "♌",
  "leo" -> "♌",
)
