package io.github.edadma.markdown

val emojiBlock3 = List(
  "leftwards_hand" -> "🫲",
  "leftwards-hand" -> "🫲",
  "leftwards hand" -> "🫲",
  "palm_down_hand" -> "🫳",
  "palm-down-hand" -> "🫳",
  "palm down hand" -> "🫳",
  "palm_up_hand" -> "🫴",
  "palm-up-hand" -> "🫴",
  "palm up hand" -> "🫴",
  "leftwards_pushing_hand" -> "🫷",
  "leftwards-pushing-hand" -> "🫷",
  "leftwards pushing hand" -> "🫷",
  "rightwards_pushing_hand" -> "🫸",
  "rightwards-pushing-hand" -> "🫸",
  "rightwards pushing hand" -> "🫸",
  "OK_hand" -> "👌",
  "OK-hand" -> "👌",
  "OK hand" -> "👌",
  "ok_hand" -> "👌",
  "pinched_fingers" -> "🤌",
  "pinched-fingers" -> "🤌",
  "pinched fingers" -> "🤌",
  "pinching_hand" -> "🤏",
  "pinching-hand" -> "🤏",
  "pinching hand" -> "🤏",
  "victory_hand" -> "✌️",
  "victory-hand" -> "✌️",
  "victory hand" -> "✌️",
  "v" -> "✌️",
  "crossed_fingers" -> "🤞",
  "crossed-fingers" -> "🤞",
  "crossed fingers" -> "🤞",
  "hand_with_index_finger_and_thumb_crossed" -> "🫰",
  "hand-with-index-finger-and-thumb-crossed" -> "🫰",
  "hand with index finger and thumb crossed" -> "🫰",
  "love-you_gesture" -> "🤟",
  "love-you-gesture" -> "🤟",
  "love-you gesture" -> "🤟",
  "love_you_gesture" -> "🤟",
  "sign_of_the_horns" -> "🤘",
  "sign-of-the-horns" -> "🤘",
  "sign of the horns" -> "🤘",
  "metal" -> "🤘",
  "call_me_hand" -> "🤙",
  "call-me-hand" -> "🤙",
  "call me hand" -> "🤙",
  "backhand_index_pointing_left" -> "👈",
  "backhand-index-pointing-left" -> "👈",
  "backhand index pointing left" -> "👈",
  "point_left" -> "👈",
  "backhand_index_pointing_right" -> "👉",
  "backhand-index-pointing-right" -> "👉",
  "backhand index pointing right" -> "👉",
  "point_right" -> "👉",
  "backhand_index_pointing_up" -> "👆",
  "backhand-index-pointing-up" -> "👆",
  "backhand index pointing up" -> "👆",
  "point_up_2" -> "👆",
  "middle_finger" -> "🖕",
  "middle-finger" -> "🖕",
  "middle finger" -> "🖕",
  "fu" -> "🖕",
  "backhand_index_pointing_down" -> "👇",
  "backhand-index-pointing-down" -> "👇",
  "backhand index pointing down" -> "👇",
  "point_down" -> "👇",
  "index_pointing_up" -> "☝️",
  "index-pointing-up" -> "☝️",
  "index pointing up" -> "☝️",
  "point_up" -> "☝️",
  "index_pointing_at_the_viewer" -> "🫵",
  "index-pointing-at-the-viewer" -> "🫵",
  "index pointing at the viewer" -> "🫵",
  "thumbs_up" -> "👍",
  "thumbs-up" -> "👍",
  "thumbs up" -> "👍",
  "+1" -> "👍",
  "thumbsup" -> "👍",
  "thumbs_down" -> "👎",
  "thumbs-down" -> "👎",
  "thumbs down" -> "👎",
  "-1" -> "👎",
  "thumbsdown" -> "👎",
  "raised_fist" -> "✊",
  "raised-fist" -> "✊",
  "raised fist" -> "✊",
  "fist_raised" -> "✊",
  "fist" -> "✊",
  "oncoming_fist" -> "👊",
  "oncoming-fist" -> "👊",
  "oncoming fist" -> "👊",
  "fist_oncoming" -> "👊",
  "facepunch" -> "👊",
  "punch" -> "👊",
  "left-facing_fist" -> "🤛",
  "left-facing-fist" -> "🤛",
  "left-facing fist" -> "🤛",
  "fist_left" -> "🤛",
  "right-facing_fist" -> "🤜",
  "right-facing-fist" -> "🤜",
  "right-facing fist" -> "🤜",
  "fist_right" -> "🤜",
  "clapping_hands" -> "👏",
  "clapping-hands" -> "👏",
  "clapping hands" -> "👏",
  "clap" -> "👏",
  "raising_hands" -> "🙌",
  "raising-hands" -> "🙌",
  "raising hands" -> "🙌",
  "raised_hands" -> "🙌",
  "heart_hands" -> "🫶",
  "heart-hands" -> "🫶",
  "heart hands" -> "🫶",
  "open_hands" -> "👐",
  "open-hands" -> "👐",
  "open hands" -> "👐",
  "palms_up_together" -> "🤲",
  "palms-up-together" -> "🤲",
  "palms up together" -> "🤲",
  "handshake" -> "🤝",
  "folded_hands" -> "🙏",
  "folded-hands" -> "🙏",
  "folded hands" -> "🙏",
  "pray" -> "🙏",
  "writing_hand" -> "✍️",
  "writing-hand" -> "✍️",
  "writing hand" -> "✍️",
  "nail_polish" -> "💅",
  "nail-polish" -> "💅",
  "nail polish" -> "💅",
  "nail_care" -> "💅",
  "selfie" -> "🤳",
  "flexed_biceps" -> "💪",
  "flexed-biceps" -> "💪",
  "flexed biceps" -> "💪",
  "muscle" -> "💪",
  "mechanical_arm" -> "🦾",
  "mechanical-arm" -> "🦾",
  "mechanical arm" -> "🦾",
  "mechanical_leg" -> "🦿",
  "mechanical-leg" -> "🦿",
  "mechanical leg" -> "🦿",
  "leg" -> "🦵",
  "foot" -> "🦶",
  "ear" -> "👂",
  "ear_with_hearing_aid" -> "🦻",
  "ear-with-hearing-aid" -> "🦻",
  "ear with hearing aid" -> "🦻",
  "nose" -> "👃",
  "brain" -> "🧠",
  "anatomical_heart" -> "🫀",
  "anatomical-heart" -> "🫀",
  "anatomical heart" -> "🫀",
  "lungs" -> "🫁",
  "tooth" -> "🦷",
  "bone" -> "🦴",
  "eyes" -> "👀",
  "eye" -> "👁️",
  "tongue" -> "👅",
  "mouth" -> "👄",
  "lips" -> "👄",
  "biting_lip" -> "🫦",
  "biting-lip" -> "🫦",
  "biting lip" -> "🫦",
  "baby" -> "👶",
  "child" -> "🧒",
  "boy" -> "👦",
  "girl" -> "👧",
  "person" -> "🧑",
  "adult" -> "🧑",
  "person_blond_hair" -> "👱",
  "person-blond-hair" -> "👱",
  "person blond hair" -> "👱",
  "blond_haired_person" -> "👱",
  "man" -> "👨",
  "person_beard" -> "🧔",
  "person-beard" -> "🧔",
  "person beard" -> "🧔",
  "bearded_person" -> "🧔",
  "man_beard" -> "🧔‍♂️",
  "man-beard" -> "🧔‍♂️",
  "man beard" -> "🧔‍♂️",
  "woman_beard" -> "🧔‍♀️",
  "woman-beard" -> "🧔‍♀️",
  "woman beard" -> "🧔‍♀️",
  "man_red_hair" -> "👨‍🦰",
  "man-red-hair" -> "👨‍🦰",
  "man red hair" -> "👨‍🦰",
  "red_haired_man" -> "👨‍🦰",
  "man_curly_hair" -> "👨‍🦱",
  "man-curly-hair" -> "👨‍🦱",
  "man curly hair" -> "👨‍🦱",
  "curly_haired_man" -> "👨‍🦱",
  "man_white_hair" -> "👨‍🦳",
  "man-white-hair" -> "👨‍🦳",
  "man white hair" -> "👨‍🦳",
  "white_haired_man" -> "👨‍🦳",
  "man_bald" -> "👨‍🦲",
  "man-bald" -> "👨‍🦲",
  "man bald" -> "👨‍🦲",
  "bald_man" -> "👨‍🦲",
  "woman" -> "👩",
  "woman_red_hair" -> "👩‍🦰",
  "woman-red-hair" -> "👩‍🦰",
  "woman red hair" -> "👩‍🦰",
  "red_haired_woman" -> "👩‍🦰",
  "person_red_hair" -> "🧑‍🦰",
  "person-red-hair" -> "🧑‍🦰",
  "person red hair" -> "🧑‍🦰",
  "woman_curly_hair" -> "👩‍🦱",
  "woman-curly-hair" -> "👩‍🦱",
  "woman curly hair" -> "👩‍🦱",
  "curly_haired_woman" -> "👩‍🦱",
  "person_curly_hair" -> "🧑‍🦱",
  "person-curly-hair" -> "🧑‍🦱",
  "person curly hair" -> "🧑‍🦱",
  "woman_white_hair" -> "👩‍🦳",
  "woman-white-hair" -> "👩‍🦳",
  "woman white hair" -> "👩‍🦳",
  "white_haired_woman" -> "👩‍🦳",
  "person_white_hair" -> "🧑‍🦳",
  "person-white-hair" -> "🧑‍🦳",
  "person white hair" -> "🧑‍🦳",
  "woman_bald" -> "👩‍🦲",
  "woman-bald" -> "👩‍🦲",
  "woman bald" -> "👩‍🦲",
  "bald_woman" -> "👩‍🦲",
  "person_bald" -> "🧑‍🦲",
  "person-bald" -> "🧑‍🦲",
  "person bald" -> "🧑‍🦲",
  "woman_blond_hair" -> "👱‍♀️",
  "woman-blond-hair" -> "👱‍♀️",
  "woman blond hair" -> "👱‍♀️",
  "blond_haired_woman" -> "👱‍♀️",
  "blonde_woman" -> "👱‍♀️",
  "man_blond_hair" -> "👱‍♂️",
  "man-blond-hair" -> "👱‍♂️",
  "man blond hair" -> "👱‍♂️",
  "blond_haired_man" -> "👱‍♂️",
  "older_person" -> "🧓",
  "older-person" -> "🧓",
  "older person" -> "🧓",
  "older_adult" -> "🧓",
  "old_man" -> "👴",
  "old-man" -> "👴",
  "old man" -> "👴",
  "older_man" -> "👴",
  "old_woman" -> "👵",
  "old-woman" -> "👵",
  "old woman" -> "👵",
  "older_woman" -> "👵",
  "person_frowning" -> "🙍",
  "person-frowning" -> "🙍",
  "person frowning" -> "🙍",
  "frowning_person" -> "🙍",
  "man_frowning" -> "🙍‍♂️",
  "man-frowning" -> "🙍‍♂️",
  "man frowning" -> "🙍‍♂️",
  "frowning_man" -> "🙍‍♂️",
  "woman_frowning" -> "🙍‍♀️",
  "woman-frowning" -> "🙍‍♀️",
  "woman frowning" -> "🙍‍♀️",
  "frowning_woman" -> "🙍‍♀️",
  "person_pouting" -> "🙎",
  "person-pouting" -> "🙎",
  "person pouting" -> "🙎",
  "pouting_face" -> "🙎",
  "man_pouting" -> "🙎‍♂️",
  "man-pouting" -> "🙎‍♂️",
  "man pouting" -> "🙎‍♂️",
  "pouting_man" -> "🙎‍♂️",
  "woman_pouting" -> "🙎‍♀️",
  "woman-pouting" -> "🙎‍♀️",
  "woman pouting" -> "🙎‍♀️",
  "pouting_woman" -> "🙎‍♀️",
  "person_gesturing_NO" -> "🙅",
  "person-gesturing-NO" -> "🙅",
  "person gesturing NO" -> "🙅",
  "no_good" -> "🙅",
  "man_gesturing_NO" -> "🙅‍♂️",
  "man-gesturing-NO" -> "🙅‍♂️",
  "man gesturing NO" -> "🙅‍♂️",
  "no_good_man" -> "🙅‍♂️",
  "ng_man" -> "🙅‍♂️",
  "woman_gesturing_NO" -> "🙅‍♀️",
  "woman-gesturing-NO" -> "🙅‍♀️",
  "woman gesturing NO" -> "🙅‍♀️",
  "no_good_woman" -> "🙅‍♀️",
  "ng_woman" -> "🙅‍♀️",
  "person_gesturing_OK" -> "🙆",
  "person-gesturing-OK" -> "🙆",
  "person gesturing OK" -> "🙆",
  "ok_person" -> "🙆",
  "man_gesturing_OK" -> "🙆‍♂️",
  "man-gesturing-OK" -> "🙆‍♂️",
  "man gesturing OK" -> "🙆‍♂️",
  "ok_man" -> "🙆‍♂️",
  "woman_gesturing_OK" -> "🙆‍♀️",
  "woman-gesturing-OK" -> "🙆‍♀️",
  "woman gesturing OK" -> "🙆‍♀️",
)
