package io.github.edadma.markdown

val emojiBlock9 = List(
  "department store" -> "🏬",
  "factory" -> "🏭",
  "Japanese_castle" -> "🏯",
  "Japanese-castle" -> "🏯",
  "Japanese castle" -> "🏯",
  "japanese_castle" -> "🏯",
  "castle" -> "🏰",
  "european_castle" -> "🏰",
  "wedding" -> "💒",
  "Tokyo_tower" -> "🗼",
  "Tokyo-tower" -> "🗼",
  "Tokyo tower" -> "🗼",
  "tokyo_tower" -> "🗼",
  "Statue_of_Liberty" -> "🗽",
  "Statue-of-Liberty" -> "🗽",
  "Statue of Liberty" -> "🗽",
  "statue_of_liberty" -> "🗽",
  "church" -> "⛪",
  "mosque" -> "🕌",
  "hindu_temple" -> "🛕",
  "hindu-temple" -> "🛕",
  "hindu temple" -> "🛕",
  "synagogue" -> "🕍",
  "shinto_shrine" -> "⛩️",
  "shinto-shrine" -> "⛩️",
  "shinto shrine" -> "⛩️",
  "kaaba" -> "🕋",
  "fountain" -> "⛲",
  "tent" -> "⛺",
  "foggy" -> "🌁",
  "night_with_stars" -> "🌃",
  "night-with-stars" -> "🌃",
  "night with stars" -> "🌃",
  "cityscape" -> "🏙️",
  "sunrise_over_mountains" -> "🌄",
  "sunrise-over-mountains" -> "🌄",
  "sunrise over mountains" -> "🌄",
  "sunrise" -> "🌅",
  "cityscape_at_dusk" -> "🌆",
  "cityscape-at-dusk" -> "🌆",
  "cityscape at dusk" -> "🌆",
  "city_sunset" -> "🌆",
  "sunset" -> "🌇",
  "city_sunrise" -> "🌇",
  "bridge_at_night" -> "🌉",
  "bridge-at-night" -> "🌉",
  "bridge at night" -> "🌉",
  "hot_springs" -> "♨️",
  "hot-springs" -> "♨️",
  "hot springs" -> "♨️",
  "hotsprings" -> "♨️",
  "carousel_horse" -> "🎠",
  "carousel-horse" -> "🎠",
  "carousel horse" -> "🎠",
  "playground_slide" -> "🛝",
  "playground-slide" -> "🛝",
  "playground slide" -> "🛝",
  "ferris_wheel" -> "🎡",
  "ferris-wheel" -> "🎡",
  "ferris wheel" -> "🎡",
  "roller_coaster" -> "🎢",
  "roller-coaster" -> "🎢",
  "roller coaster" -> "🎢",
  "barber_pole" -> "💈",
  "barber-pole" -> "💈",
  "barber pole" -> "💈",
  "barber" -> "💈",
  "circus_tent" -> "🎪",
  "circus-tent" -> "🎪",
  "circus tent" -> "🎪",
  "locomotive" -> "🚂",
  "steam_locomotive" -> "🚂",
  "railway_car" -> "🚃",
  "railway-car" -> "🚃",
  "railway car" -> "🚃",
  "high-speed_train" -> "🚄",
  "high-speed-train" -> "🚄",
  "high-speed train" -> "🚄",
  "bullettrain_side" -> "🚄",
  "bullet_train" -> "🚅",
  "bullet-train" -> "🚅",
  "bullet train" -> "🚅",
  "bullettrain_front" -> "🚅",
  "train" -> "🚆",
  "train2" -> "🚆",
  "metro" -> "🚇",
  "light_rail" -> "🚈",
  "light-rail" -> "🚈",
  "light rail" -> "🚈",
  "station" -> "🚉",
  "tram" -> "🚊",
  "monorail" -> "🚝",
  "mountain_railway" -> "🚞",
  "mountain-railway" -> "🚞",
  "mountain railway" -> "🚞",
  "tram_car" -> "🚋",
  "tram-car" -> "🚋",
  "tram car" -> "🚋",
  "train" -> "🚋",
  "bus" -> "🚌",
  "oncoming_bus" -> "🚍",
  "oncoming-bus" -> "🚍",
  "oncoming bus" -> "🚍",
  "trolleybus" -> "🚎",
  "minibus" -> "🚐",
  "ambulance" -> "🚑",
  "fire_engine" -> "🚒",
  "fire-engine" -> "🚒",
  "fire engine" -> "🚒",
  "police_car" -> "🚓",
  "police-car" -> "🚓",
  "police car" -> "🚓",
  "oncoming_police_car" -> "🚔",
  "oncoming-police-car" -> "🚔",
  "oncoming police car" -> "🚔",
  "taxi" -> "🚕",
  "oncoming_taxi" -> "🚖",
  "oncoming-taxi" -> "🚖",
  "oncoming taxi" -> "🚖",
  "automobile" -> "🚗",
  "car" -> "🚗",
  "red_car" -> "🚗",
  "oncoming_automobile" -> "🚘",
  "oncoming-automobile" -> "🚘",
  "oncoming automobile" -> "🚘",
  "sport_utility_vehicle" -> "🚙",
  "sport-utility-vehicle" -> "🚙",
  "sport utility vehicle" -> "🚙",
  "blue_car" -> "🚙",
  "pickup_truck" -> "🛻",
  "pickup-truck" -> "🛻",
  "pickup truck" -> "🛻",
  "delivery_truck" -> "🚚",
  "delivery-truck" -> "🚚",
  "delivery truck" -> "🚚",
  "truck" -> "🚚",
  "articulated_lorry" -> "🚛",
  "articulated-lorry" -> "🚛",
  "articulated lorry" -> "🚛",
  "tractor" -> "🚜",
  "racing_car" -> "🏎️",
  "racing-car" -> "🏎️",
  "racing car" -> "🏎️",
  "motorcycle" -> "🏍️",
  "motor_scooter" -> "🛵",
  "motor-scooter" -> "🛵",
  "motor scooter" -> "🛵",
  "manual_wheelchair" -> "🦽",
  "manual-wheelchair" -> "🦽",
  "manual wheelchair" -> "🦽",
  "motorized_wheelchair" -> "🦼",
  "motorized-wheelchair" -> "🦼",
  "motorized wheelchair" -> "🦼",
  "auto_rickshaw" -> "🛺",
  "auto-rickshaw" -> "🛺",
  "auto rickshaw" -> "🛺",
  "bicycle" -> "🚲",
  "bike" -> "🚲",
  "kick_scooter" -> "🛴",
  "kick-scooter" -> "🛴",
  "kick scooter" -> "🛴",
  "skateboard" -> "🛹",
  "roller_skate" -> "🛼",
  "roller-skate" -> "🛼",
  "roller skate" -> "🛼",
  "bus_stop" -> "🚏",
  "bus-stop" -> "🚏",
  "bus stop" -> "🚏",
  "busstop" -> "🚏",
  "motorway" -> "🛣️",
  "railway_track" -> "🛤️",
  "railway-track" -> "🛤️",
  "railway track" -> "🛤️",
  "oil_drum" -> "🛢️",
  "oil-drum" -> "🛢️",
  "oil drum" -> "🛢️",
  "fuel_pump" -> "⛽",
  "fuel-pump" -> "⛽",
  "fuel pump" -> "⛽",
  "fuelpump" -> "⛽",
  "wheel" -> "🛞",
  "police_car_light" -> "🚨",
  "police-car-light" -> "🚨",
  "police car light" -> "🚨",
  "rotating_light" -> "🚨",
  "horizontal_traffic_light" -> "🚥",
  "horizontal-traffic-light" -> "🚥",
  "horizontal traffic light" -> "🚥",
  "traffic_light" -> "🚥",
  "vertical_traffic_light" -> "🚦",
  "vertical-traffic-light" -> "🚦",
  "vertical traffic light" -> "🚦",
  "stop_sign" -> "🛑",
  "stop-sign" -> "🛑",
  "stop sign" -> "🛑",
  "construction" -> "🚧",
  "anchor" -> "⚓",
  "ring_buoy" -> "🛟",
  "ring-buoy" -> "🛟",
  "ring buoy" -> "🛟",
  "sailboat" -> "⛵",
  "boat" -> "⛵",
  "canoe" -> "🛶",
  "speedboat" -> "🚤",
  "passenger_ship" -> "🛳️",
  "passenger-ship" -> "🛳️",
  "passenger ship" -> "🛳️",
  "ferry" -> "⛴️",
  "motor_boat" -> "🛥️",
  "motor-boat" -> "🛥️",
  "motor boat" -> "🛥️",
  "ship" -> "🚢",
  "airplane" -> "✈️",
  "small_airplane" -> "🛩️",
  "small-airplane" -> "🛩️",
  "small airplane" -> "🛩️",
  "airplane_departure" -> "🛫",
  "airplane-departure" -> "🛫",
  "airplane departure" -> "🛫",
  "flight_departure" -> "🛫",
  "airplane_arrival" -> "🛬",
  "airplane-arrival" -> "🛬",
  "airplane arrival" -> "🛬",
  "flight_arrival" -> "🛬",
  "parachute" -> "🪂",
  "seat" -> "💺",
  "helicopter" -> "🚁",
  "suspension_railway" -> "🚟",
  "suspension-railway" -> "🚟",
  "suspension railway" -> "🚟",
  "mountain_cableway" -> "🚠",
  "mountain-cableway" -> "🚠",
  "mountain cableway" -> "🚠",
  "aerial_tramway" -> "🚡",
  "aerial-tramway" -> "🚡",
  "aerial tramway" -> "🚡",
  "satellite" -> "🛰️",
  "artificial_satellite" -> "🛰️",
  "rocket" -> "🚀",
  "flying_saucer" -> "🛸",
  "flying-saucer" -> "🛸",
  "flying saucer" -> "🛸",
  "bellhop_bell" -> "🛎️",
  "bellhop-bell" -> "🛎️",
  "bellhop bell" -> "🛎️",
  "luggage" -> "🧳",
  "hourglass_done" -> "⌛",
  "hourglass-done" -> "⌛",
  "hourglass done" -> "⌛",
  "hourglass" -> "⌛",
  "hourglass_not_done" -> "⏳",
  "hourglass-not-done" -> "⏳",
  "hourglass not done" -> "⏳",
  "hourglass_flowing_sand" -> "⏳",
  "watch" -> "⌚",
  "alarm_clock" -> "⏰",
  "alarm-clock" -> "⏰",
  "alarm clock" -> "⏰",
  "stopwatch" -> "⏱️",
  "timer_clock" -> "⏲️",
  "timer-clock" -> "⏲️",
  "timer clock" -> "⏲️",
  "mantelpiece_clock" -> "🕰️",
  "mantelpiece-clock" -> "🕰️",
  "mantelpiece clock" -> "🕰️",
  "twelve_o’clock" -> "🕛",
  "twelve-o’clock" -> "🕛",
  "twelve o’clock" -> "🕛",
  "clock12" -> "🕛",
  "twelve-thirty" -> "🕧",
  "clock1230" -> "🕧",
  "one_o’clock" -> "🕐",
  "one-o’clock" -> "🕐",
  "one o’clock" -> "🕐",
  "clock1" -> "🕐",
  "one-thirty" -> "🕜",
  "clock130" -> "🕜",
  "two_o’clock" -> "🕑",
  "two-o’clock" -> "🕑",
  "two o’clock" -> "🕑",
  "clock2" -> "🕑",
  "two-thirty" -> "🕝",
  "clock230" -> "🕝",
  "three_o’clock" -> "🕒",
  "three-o’clock" -> "🕒",
  "three o’clock" -> "🕒",
  "clock3" -> "🕒",
  "three-thirty" -> "🕞",
  "clock330" -> "🕞",
  "four_o’clock" -> "🕓",
  "four-o’clock" -> "🕓",
  "four o’clock" -> "🕓",
  "clock4" -> "🕓",
  "four-thirty" -> "🕟",
  "clock430" -> "🕟",
  "five_o’clock" -> "🕔",
  "five-o’clock" -> "🕔",
  "five o’clock" -> "🕔",
  "clock5" -> "🕔",
  "five-thirty" -> "🕠",
)
