package io.github.edadma.markdown

val emojiBlock8 = List(
  "cheese_wedge" -> "🧀",
  "cheese-wedge" -> "🧀",
  "cheese wedge" -> "🧀",
  "cheese" -> "🧀",
  "meat_on_bone" -> "🍖",
  "meat-on-bone" -> "🍖",
  "meat on bone" -> "🍖",
  "poultry_leg" -> "🍗",
  "poultry-leg" -> "🍗",
  "poultry leg" -> "🍗",
  "cut_of_meat" -> "🥩",
  "cut-of-meat" -> "🥩",
  "cut of meat" -> "🥩",
  "bacon" -> "🥓",
  "hamburger" -> "🍔",
  "french_fries" -> "🍟",
  "french-fries" -> "🍟",
  "french fries" -> "🍟",
  "fries" -> "🍟",
  "pizza" -> "🍕",
  "hot_dog" -> "🌭",
  "hot-dog" -> "🌭",
  "hot dog" -> "🌭",
  "hotdog" -> "🌭",
  "sandwich" -> "🥪",
  "taco" -> "🌮",
  "burrito" -> "🌯",
  "tamale" -> "🫔",
  "stuffed_flatbread" -> "🥙",
  "stuffed-flatbread" -> "🥙",
  "stuffed flatbread" -> "🥙",
  "falafel" -> "🧆",
  "egg" -> "🥚",
  "cooking" -> "🍳",
  "fried_egg" -> "🍳",
  "shallow_pan_of_food" -> "🥘",
  "shallow-pan-of-food" -> "🥘",
  "shallow pan of food" -> "🥘",
  "pot_of_food" -> "🍲",
  "pot-of-food" -> "🍲",
  "pot of food" -> "🍲",
  "stew" -> "🍲",
  "fondue" -> "🫕",
  "bowl_with_spoon" -> "🥣",
  "bowl-with-spoon" -> "🥣",
  "bowl with spoon" -> "🥣",
  "green_salad" -> "🥗",
  "green-salad" -> "🥗",
  "green salad" -> "🥗",
  "popcorn" -> "🍿",
  "butter" -> "🧈",
  "salt" -> "🧂",
  "canned_food" -> "🥫",
  "canned-food" -> "🥫",
  "canned food" -> "🥫",
  "bento_box" -> "🍱",
  "bento-box" -> "🍱",
  "bento box" -> "🍱",
  "bento" -> "🍱",
  "rice_cracker" -> "🍘",
  "rice-cracker" -> "🍘",
  "rice cracker" -> "🍘",
  "rice_ball" -> "🍙",
  "rice-ball" -> "🍙",
  "rice ball" -> "🍙",
  "cooked_rice" -> "🍚",
  "cooked-rice" -> "🍚",
  "cooked rice" -> "🍚",
  "rice" -> "🍚",
  "curry_rice" -> "🍛",
  "curry-rice" -> "🍛",
  "curry rice" -> "🍛",
  "curry" -> "🍛",
  "steaming_bowl" -> "🍜",
  "steaming-bowl" -> "🍜",
  "steaming bowl" -> "🍜",
  "ramen" -> "🍜",
  "spaghetti" -> "🍝",
  "roasted_sweet_potato" -> "🍠",
  "roasted-sweet-potato" -> "🍠",
  "roasted sweet potato" -> "🍠",
  "sweet_potato" -> "🍠",
  "oden" -> "🍢",
  "sushi" -> "🍣",
  "fried_shrimp" -> "🍤",
  "fried-shrimp" -> "🍤",
  "fried shrimp" -> "🍤",
  "fish_cake_with_swirl" -> "🍥",
  "fish-cake-with-swirl" -> "🍥",
  "fish cake with swirl" -> "🍥",
  "fish_cake" -> "🍥",
  "moon_cake" -> "🥮",
  "moon-cake" -> "🥮",
  "moon cake" -> "🥮",
  "dango" -> "🍡",
  "dumpling" -> "🥟",
  "fortune_cookie" -> "🥠",
  "fortune-cookie" -> "🥠",
  "fortune cookie" -> "🥠",
  "takeout_box" -> "🥡",
  "takeout-box" -> "🥡",
  "takeout box" -> "🥡",
  "crab" -> "🦀",
  "lobster" -> "🦞",
  "shrimp" -> "🦐",
  "squid" -> "🦑",
  "oyster" -> "🦪",
  "soft_ice_cream" -> "🍦",
  "soft-ice-cream" -> "🍦",
  "soft ice cream" -> "🍦",
  "icecream" -> "🍦",
  "shaved_ice" -> "🍧",
  "shaved-ice" -> "🍧",
  "shaved ice" -> "🍧",
  "ice_cream" -> "🍨",
  "ice-cream" -> "🍨",
  "ice cream" -> "🍨",
  "doughnut" -> "🍩",
  "cookie" -> "🍪",
  "birthday_cake" -> "🎂",
  "birthday-cake" -> "🎂",
  "birthday cake" -> "🎂",
  "birthday" -> "🎂",
  "shortcake" -> "🍰",
  "cake" -> "🍰",
  "cupcake" -> "🧁",
  "pie" -> "🥧",
  "chocolate_bar" -> "🍫",
  "chocolate-bar" -> "🍫",
  "chocolate bar" -> "🍫",
  "candy" -> "🍬",
  "lollipop" -> "🍭",
  "custard" -> "🍮",
  "honey_pot" -> "🍯",
  "honey-pot" -> "🍯",
  "honey pot" -> "🍯",
  "baby_bottle" -> "🍼",
  "baby-bottle" -> "🍼",
  "baby bottle" -> "🍼",
  "glass_of_milk" -> "🥛",
  "glass-of-milk" -> "🥛",
  "glass of milk" -> "🥛",
  "milk_glass" -> "🥛",
  "hot_beverage" -> "☕",
  "hot-beverage" -> "☕",
  "hot beverage" -> "☕",
  "coffee" -> "☕",
  "teapot" -> "🫖",
  "teacup_without_handle" -> "🍵",
  "teacup-without-handle" -> "🍵",
  "teacup without handle" -> "🍵",
  "tea" -> "🍵",
  "sake" -> "🍶",
  "bottle_with_popping_cork" -> "🍾",
  "bottle-with-popping-cork" -> "🍾",
  "bottle with popping cork" -> "🍾",
  "champagne" -> "🍾",
  "wine_glass" -> "🍷",
  "wine-glass" -> "🍷",
  "wine glass" -> "🍷",
  "cocktail_glass" -> "🍸",
  "cocktail-glass" -> "🍸",
  "cocktail glass" -> "🍸",
  "cocktail" -> "🍸",
  "tropical_drink" -> "🍹",
  "tropical-drink" -> "🍹",
  "tropical drink" -> "🍹",
  "beer_mug" -> "🍺",
  "beer-mug" -> "🍺",
  "beer mug" -> "🍺",
  "beer" -> "🍺",
  "clinking_beer_mugs" -> "🍻",
  "clinking-beer-mugs" -> "🍻",
  "clinking beer mugs" -> "🍻",
  "beers" -> "🍻",
  "clinking_glasses" -> "🥂",
  "clinking-glasses" -> "🥂",
  "clinking glasses" -> "🥂",
  "tumbler_glass" -> "🥃",
  "tumbler-glass" -> "🥃",
  "tumbler glass" -> "🥃",
  "pouring_liquid" -> "🫗",
  "pouring-liquid" -> "🫗",
  "pouring liquid" -> "🫗",
  "cup_with_straw" -> "🥤",
  "cup-with-straw" -> "🥤",
  "cup with straw" -> "🥤",
  "bubble_tea" -> "🧋",
  "bubble-tea" -> "🧋",
  "bubble tea" -> "🧋",
  "beverage_box" -> "🧃",
  "beverage-box" -> "🧃",
  "beverage box" -> "🧃",
  "mate" -> "🧉",
  "ice" -> "🧊",
  "ice_cube" -> "🧊",
  "chopsticks" -> "🥢",
  "fork_and_knife_with_plate" -> "🍽️",
  "fork-and-knife-with-plate" -> "🍽️",
  "fork and knife with plate" -> "🍽️",
  "plate_with_cutlery" -> "🍽️",
  "fork_and_knife" -> "🍴",
  "fork-and-knife" -> "🍴",
  "fork and knife" -> "🍴",
  "spoon" -> "🥄",
  "kitchen_knife" -> "🔪",
  "kitchen-knife" -> "🔪",
  "kitchen knife" -> "🔪",
  "hocho" -> "🔪",
  "knife" -> "🔪",
  "jar" -> "🫙",
  "amphora" -> "🏺",
  "globe_showing_Europe-Africa" -> "🌍",
  "globe-showing-Europe-Africa" -> "🌍",
  "globe showing Europe-Africa" -> "🌍",
  "earth_africa" -> "🌍",
  "globe_showing_Americas" -> "🌎",
  "globe-showing-Americas" -> "🌎",
  "globe showing Americas" -> "🌎",
  "earth_americas" -> "🌎",
  "globe_showing_Asia-Australia" -> "🌏",
  "globe-showing-Asia-Australia" -> "🌏",
  "globe showing Asia-Australia" -> "🌏",
  "earth_asia" -> "🌏",
  "globe_with_meridians" -> "🌐",
  "globe-with-meridians" -> "🌐",
  "globe with meridians" -> "🌐",
  "world_map" -> "🗺️",
  "world-map" -> "🗺️",
  "world map" -> "🗺️",
  "map_of_Japan" -> "🗾",
  "map-of-Japan" -> "🗾",
  "map of Japan" -> "🗾",
  "japan" -> "🗾",
  "compass" -> "🧭",
  "snow-capped_mountain" -> "🏔️",
  "snow-capped-mountain" -> "🏔️",
  "snow-capped mountain" -> "🏔️",
  "mountain_snow" -> "🏔️",
  "mountain" -> "⛰️",
  "volcano" -> "🌋",
  "mount_fuji" -> "🗻",
  "mount-fuji" -> "🗻",
  "mount fuji" -> "🗻",
  "camping" -> "🏕️",
  "beach_with_umbrella" -> "🏖️",
  "beach-with-umbrella" -> "🏖️",
  "beach with umbrella" -> "🏖️",
  "beach_umbrella" -> "🏖️",
  "desert" -> "🏜️",
  "desert_island" -> "🏝️",
  "desert-island" -> "🏝️",
  "desert island" -> "🏝️",
  "national_park" -> "🏞️",
  "national-park" -> "🏞️",
  "national park" -> "🏞️",
  "stadium" -> "🏟️",
  "classical_building" -> "🏛️",
  "classical-building" -> "🏛️",
  "classical building" -> "🏛️",
  "building_construction" -> "🏗️",
  "building-construction" -> "🏗️",
  "building construction" -> "🏗️",
  "brick" -> "🧱",
  "bricks" -> "🧱",
  "rock" -> "🪨",
  "wood" -> "🪵",
  "hut" -> "🛖",
  "houses" -> "🏘️",
  "derelict_house" -> "🏚️",
  "derelict-house" -> "🏚️",
  "derelict house" -> "🏚️",
  "house" -> "🏠",
  "house_with_garden" -> "🏡",
  "house-with-garden" -> "🏡",
  "house with garden" -> "🏡",
  "office_building" -> "🏢",
  "office-building" -> "🏢",
  "office building" -> "🏢",
  "office" -> "🏢",
  "Japanese_post_office" -> "🏣",
  "Japanese-post-office" -> "🏣",
  "Japanese post office" -> "🏣",
  "post_office" -> "🏣",
  "post_office" -> "🏤",
  "post-office" -> "🏤",
  "post office" -> "🏤",
  "european_post_office" -> "🏤",
  "hospital" -> "🏥",
  "bank" -> "🏦",
  "hotel" -> "🏨",
  "love_hotel" -> "🏩",
  "love-hotel" -> "🏩",
  "love hotel" -> "🏩",
  "convenience_store" -> "🏪",
  "convenience-store" -> "🏪",
  "convenience store" -> "🏪",
  "school" -> "🏫",
  "department_store" -> "🏬",
  "department-store" -> "🏬",
)
