package io.github.edadma.markdown

val emojiBlock6 = List(
  "woman bouncing ball" -> "⛹️‍♀️",
  "bouncing_ball_woman" -> "⛹️‍♀️",
  "basketball_woman" -> "⛹️‍♀️",
  "person_lifting_weights" -> "🏋️",
  "person-lifting-weights" -> "🏋️",
  "person lifting weights" -> "🏋️",
  "weight_lifting" -> "🏋️",
  "man_lifting_weights" -> "🏋️‍♂️",
  "man-lifting-weights" -> "🏋️‍♂️",
  "man lifting weights" -> "🏋️‍♂️",
  "weight_lifting_man" -> "🏋️‍♂️",
  "woman_lifting_weights" -> "🏋️‍♀️",
  "woman-lifting-weights" -> "🏋️‍♀️",
  "woman lifting weights" -> "🏋️‍♀️",
  "weight_lifting_woman" -> "🏋️‍♀️",
  "person_biking" -> "🚴",
  "person-biking" -> "🚴",
  "person biking" -> "🚴",
  "bicyclist" -> "🚴",
  "man_biking" -> "🚴‍♂️",
  "man-biking" -> "🚴‍♂️",
  "man biking" -> "🚴‍♂️",
  "biking_man" -> "🚴‍♂️",
  "woman_biking" -> "🚴‍♀️",
  "woman-biking" -> "🚴‍♀️",
  "woman biking" -> "🚴‍♀️",
  "biking_woman" -> "🚴‍♀️",
  "person_mountain_biking" -> "🚵",
  "person-mountain-biking" -> "🚵",
  "person mountain biking" -> "🚵",
  "mountain_bicyclist" -> "🚵",
  "man_mountain_biking" -> "🚵‍♂️",
  "man-mountain-biking" -> "🚵‍♂️",
  "man mountain biking" -> "🚵‍♂️",
  "mountain_biking_man" -> "🚵‍♂️",
  "woman_mountain_biking" -> "🚵‍♀️",
  "woman-mountain-biking" -> "🚵‍♀️",
  "woman mountain biking" -> "🚵‍♀️",
  "mountain_biking_woman" -> "🚵‍♀️",
  "person_cartwheeling" -> "🤸",
  "person-cartwheeling" -> "🤸",
  "person cartwheeling" -> "🤸",
  "cartwheeling" -> "🤸",
  "man_cartwheeling" -> "🤸‍♂️",
  "man-cartwheeling" -> "🤸‍♂️",
  "man cartwheeling" -> "🤸‍♂️",
  "woman_cartwheeling" -> "🤸‍♀️",
  "woman-cartwheeling" -> "🤸‍♀️",
  "woman cartwheeling" -> "🤸‍♀️",
  "people_wrestling" -> "🤼",
  "people-wrestling" -> "🤼",
  "people wrestling" -> "🤼",
  "wrestling" -> "🤼",
  "men_wrestling" -> "🤼‍♂️",
  "men-wrestling" -> "🤼‍♂️",
  "men wrestling" -> "🤼‍♂️",
  "women_wrestling" -> "🤼‍♀️",
  "women-wrestling" -> "🤼‍♀️",
  "women wrestling" -> "🤼‍♀️",
  "person_playing_water_polo" -> "🤽",
  "person-playing-water-polo" -> "🤽",
  "person playing water polo" -> "🤽",
  "water_polo" -> "🤽",
  "man_playing_water_polo" -> "🤽‍♂️",
  "man-playing-water-polo" -> "🤽‍♂️",
  "man playing water polo" -> "🤽‍♂️",
  "woman_playing_water_polo" -> "🤽‍♀️",
  "woman-playing-water-polo" -> "🤽‍♀️",
  "woman playing water polo" -> "🤽‍♀️",
  "person_playing_handball" -> "🤾",
  "person-playing-handball" -> "🤾",
  "person playing handball" -> "🤾",
  "handball_person" -> "🤾",
  "man_playing_handball" -> "🤾‍♂️",
  "man-playing-handball" -> "🤾‍♂️",
  "man playing handball" -> "🤾‍♂️",
  "woman_playing_handball" -> "🤾‍♀️",
  "woman-playing-handball" -> "🤾‍♀️",
  "woman playing handball" -> "🤾‍♀️",
  "person_juggling" -> "🤹",
  "person-juggling" -> "🤹",
  "person juggling" -> "🤹",
  "juggling_person" -> "🤹",
  "man_juggling" -> "🤹‍♂️",
  "man-juggling" -> "🤹‍♂️",
  "man juggling" -> "🤹‍♂️",
  "woman_juggling" -> "🤹‍♀️",
  "woman-juggling" -> "🤹‍♀️",
  "woman juggling" -> "🤹‍♀️",
  "person_in_lotus_position" -> "🧘",
  "person-in-lotus-position" -> "🧘",
  "person in lotus position" -> "🧘",
  "lotus_position" -> "🧘",
  "man_in_lotus_position" -> "🧘‍♂️",
  "man-in-lotus-position" -> "🧘‍♂️",
  "man in lotus position" -> "🧘‍♂️",
  "lotus_position_man" -> "🧘‍♂️",
  "woman_in_lotus_position" -> "🧘‍♀️",
  "woman-in-lotus-position" -> "🧘‍♀️",
  "woman in lotus position" -> "🧘‍♀️",
  "lotus_position_woman" -> "🧘‍♀️",
  "person_taking_bath" -> "🛀",
  "person-taking-bath" -> "🛀",
  "person taking bath" -> "🛀",
  "bath" -> "🛀",
  "person_in_bed" -> "🛌",
  "person-in-bed" -> "🛌",
  "person in bed" -> "🛌",
  "sleeping_bed" -> "🛌",
  "people_holding_hands" -> "🧑‍🤝‍🧑",
  "people-holding-hands" -> "🧑‍🤝‍🧑",
  "people holding hands" -> "🧑‍🤝‍🧑",
  "women_holding_hands" -> "👭",
  "women-holding-hands" -> "👭",
  "women holding hands" -> "👭",
  "two_women_holding_hands" -> "👭",
  "woman_and_man_holding_hands" -> "👫",
  "woman-and-man-holding-hands" -> "👫",
  "woman and man holding hands" -> "👫",
  "couple" -> "👫",
  "men_holding_hands" -> "👬",
  "men-holding-hands" -> "👬",
  "men holding hands" -> "👬",
  "two_men_holding_hands" -> "👬",
  "kiss" -> "💏",
  "couplekiss" -> "💏",
  "kiss_woman,_man" -> "👩‍❤️‍💋‍👨",
  "kiss-woman,-man" -> "👩‍❤️‍💋‍👨",
  "kiss woman, man" -> "👩‍❤️‍💋‍👨",
  "couplekiss_man_woman" -> "👩‍❤️‍💋‍👨",
  "kiss_man,_man" -> "👨‍❤️‍💋‍👨",
  "kiss-man,-man" -> "👨‍❤️‍💋‍👨",
  "kiss man, man" -> "👨‍❤️‍💋‍👨",
  "couplekiss_man_man" -> "👨‍❤️‍💋‍👨",
  "kiss_woman,_woman" -> "👩‍❤️‍💋‍👩",
  "kiss-woman,-woman" -> "👩‍❤️‍💋‍👩",
  "kiss woman, woman" -> "👩‍❤️‍💋‍👩",
  "couplekiss_woman_woman" -> "👩‍❤️‍💋‍👩",
  "couple_with_heart" -> "💑",
  "couple-with-heart" -> "💑",
  "couple with heart" -> "💑",
  "couple_with_heart_woman,_man" -> "👩‍❤️‍👨",
  "couple-with-heart-woman,-man" -> "👩‍❤️‍👨",
  "couple with heart woman, man" -> "👩‍❤️‍👨",
  "couple_with_heart_woman_man" -> "👩‍❤️‍👨",
  "couple_with_heart_man,_man" -> "👨‍❤️‍👨",
  "couple-with-heart-man,-man" -> "👨‍❤️‍👨",
  "couple with heart man, man" -> "👨‍❤️‍👨",
  "couple_with_heart_man_man" -> "👨‍❤️‍👨",
  "couple_with_heart_woman,_woman" -> "👩‍❤️‍👩",
  "couple-with-heart-woman,-woman" -> "👩‍❤️‍👩",
  "couple with heart woman, woman" -> "👩‍❤️‍👩",
  "couple_with_heart_woman_woman" -> "👩‍❤️‍👩",
  "family" -> "👪",
  "family_man,_woman,_boy" -> "👨‍👩‍👦",
  "family-man,-woman,-boy" -> "👨‍👩‍👦",
  "family man, woman, boy" -> "👨‍👩‍👦",
  "family_man_woman_boy" -> "👨‍👩‍👦",
  "family_man,_woman,_girl" -> "👨‍👩‍👧",
  "family-man,-woman,-girl" -> "👨‍👩‍👧",
  "family man, woman, girl" -> "👨‍👩‍👧",
  "family_man_woman_girl" -> "👨‍👩‍👧",
  "family_man,_woman,_girl,_boy" -> "👨‍👩‍👧‍👦",
  "family-man,-woman,-girl,-boy" -> "👨‍👩‍👧‍👦",
  "family man, woman, girl, boy" -> "👨‍👩‍👧‍👦",
  "family_man_woman_girl_boy" -> "👨‍👩‍👧‍👦",
  "family_man,_woman,_boy,_boy" -> "👨‍👩‍👦‍👦",
  "family-man,-woman,-boy,-boy" -> "👨‍👩‍👦‍👦",
  "family man, woman, boy, boy" -> "👨‍👩‍👦‍👦",
  "family_man_woman_boy_boy" -> "👨‍👩‍👦‍👦",
  "family_man,_woman,_girl,_girl" -> "👨‍👩‍👧‍👧",
  "family-man,-woman,-girl,-girl" -> "👨‍👩‍👧‍👧",
  "family man, woman, girl, girl" -> "👨‍👩‍👧‍👧",
  "family_man_woman_girl_girl" -> "👨‍👩‍👧‍👧",
  "family_man,_man,_boy" -> "👨‍👨‍👦",
  "family-man,-man,-boy" -> "👨‍👨‍👦",
  "family man, man, boy" -> "👨‍👨‍👦",
  "family_man_man_boy" -> "👨‍👨‍👦",
  "family_man,_man,_girl" -> "👨‍👨‍👧",
  "family-man,-man,-girl" -> "👨‍👨‍👧",
  "family man, man, girl" -> "👨‍👨‍👧",
  "family_man_man_girl" -> "👨‍👨‍👧",
  "family_man,_man,_girl,_boy" -> "👨‍👨‍👧‍👦",
  "family-man,-man,-girl,-boy" -> "👨‍👨‍👧‍👦",
  "family man, man, girl, boy" -> "👨‍👨‍👧‍👦",
  "family_man_man_girl_boy" -> "👨‍👨‍👧‍👦",
  "family_man,_man,_boy,_boy" -> "👨‍👨‍👦‍👦",
  "family-man,-man,-boy,-boy" -> "👨‍👨‍👦‍👦",
  "family man, man, boy, boy" -> "👨‍👨‍👦‍👦",
  "family_man_man_boy_boy" -> "👨‍👨‍👦‍👦",
  "family_man,_man,_girl,_girl" -> "👨‍👨‍👧‍👧",
  "family-man,-man,-girl,-girl" -> "👨‍👨‍👧‍👧",
  "family man, man, girl, girl" -> "👨‍👨‍👧‍👧",
  "family_man_man_girl_girl" -> "👨‍👨‍👧‍👧",
  "family_woman,_woman,_boy" -> "👩‍👩‍👦",
  "family-woman,-woman,-boy" -> "👩‍👩‍👦",
  "family woman, woman, boy" -> "👩‍👩‍👦",
  "family_woman_woman_boy" -> "👩‍👩‍👦",
  "family_woman,_woman,_girl" -> "👩‍👩‍👧",
  "family-woman,-woman,-girl" -> "👩‍👩‍👧",
  "family woman, woman, girl" -> "👩‍👩‍👧",
  "family_woman_woman_girl" -> "👩‍👩‍👧",
  "family_woman,_woman,_girl,_boy" -> "👩‍👩‍👧‍👦",
  "family-woman,-woman,-girl,-boy" -> "👩‍👩‍👧‍👦",
  "family woman, woman, girl, boy" -> "👩‍👩‍👧‍👦",
  "family_woman_woman_girl_boy" -> "👩‍👩‍👧‍👦",
  "family_woman,_woman,_boy,_boy" -> "👩‍👩‍👦‍👦",
  "family-woman,-woman,-boy,-boy" -> "👩‍👩‍👦‍👦",
  "family woman, woman, boy, boy" -> "👩‍👩‍👦‍👦",
  "family_woman_woman_boy_boy" -> "👩‍👩‍👦‍👦",
  "family_woman,_woman,_girl,_girl" -> "👩‍👩‍👧‍👧",
  "family-woman,-woman,-girl,-girl" -> "👩‍👩‍👧‍👧",
  "family woman, woman, girl, girl" -> "👩‍👩‍👧‍👧",
  "family_woman_woman_girl_girl" -> "👩‍👩‍👧‍👧",
  "family_man,_boy" -> "👨‍👦",
  "family-man,-boy" -> "👨‍👦",
  "family man, boy" -> "👨‍👦",
  "family_man_boy" -> "👨‍👦",
  "family_man,_boy,_boy" -> "👨‍👦‍👦",
  "family-man,-boy,-boy" -> "👨‍👦‍👦",
  "family man, boy, boy" -> "👨‍👦‍👦",
  "family_man_boy_boy" -> "👨‍👦‍👦",
  "family_man,_girl" -> "👨‍👧",
  "family-man,-girl" -> "👨‍👧",
  "family man, girl" -> "👨‍👧",
  "family_man_girl" -> "👨‍👧",
  "family_man,_girl,_boy" -> "👨‍👧‍👦",
  "family-man,-girl,-boy" -> "👨‍👧‍👦",
  "family man, girl, boy" -> "👨‍👧‍👦",
  "family_man_girl_boy" -> "👨‍👧‍👦",
  "family_man,_girl,_girl" -> "👨‍👧‍👧",
  "family-man,-girl,-girl" -> "👨‍👧‍👧",
  "family man, girl, girl" -> "👨‍👧‍👧",
  "family_man_girl_girl" -> "👨‍👧‍👧",
  "family_woman,_boy" -> "👩‍👦",
  "family-woman,-boy" -> "👩‍👦",
  "family woman, boy" -> "👩‍👦",
  "family_woman_boy" -> "👩‍👦",
  "family_woman,_boy,_boy" -> "👩‍👦‍👦",
  "family-woman,-boy,-boy" -> "👩‍👦‍👦",
  "family woman, boy, boy" -> "👩‍👦‍👦",
  "family_woman_boy_boy" -> "👩‍👦‍👦",
  "family_woman,_girl" -> "👩‍👧",
  "family-woman,-girl" -> "👩‍👧",
  "family woman, girl" -> "👩‍👧",
  "family_woman_girl" -> "👩‍👧",
  "family_woman,_girl,_boy" -> "👩‍👧‍👦",
  "family-woman,-girl,-boy" -> "👩‍👧‍👦",
  "family woman, girl, boy" -> "👩‍👧‍👦",
  "family_woman_girl_boy" -> "👩‍👧‍👦",
  "family_woman,_girl,_girl" -> "👩‍👧‍👧",
  "family-woman,-girl,-girl" -> "👩‍👧‍👧",
  "family woman, girl, girl" -> "👩‍👧‍👧",
  "family_woman_girl_girl" -> "👩‍👧‍👧",
  "speaking_head" -> "🗣️",
  "speaking-head" -> "🗣️",
  "speaking head" -> "🗣️",
  "bust_in_silhouette" -> "👤",
  "bust-in-silhouette" -> "👤",
  "bust in silhouette" -> "👤",
  "busts_in_silhouette" -> "👥",
  "busts-in-silhouette" -> "👥",
  "busts in silhouette" -> "👥",
  "people_hugging" -> "🫂",
  "people-hugging" -> "🫂",
  "people hugging" -> "🫂",
  "footprints" -> "👣",
  "monkey_face" -> "🐵",
  "monkey-face" -> "🐵",
  "monkey face" -> "🐵",
  "monkey" -> "🐒",
  "gorilla" -> "🦍",
  "orangutan" -> "🦧",
  "dog_face" -> "🐶",
  "dog-face" -> "🐶",
  "dog face" -> "🐶",
  "dog" -> "🐶",
  "dog" -> "🐕",
  "dog2" -> "🐕",
  "guide_dog" -> "🦮",
  "guide-dog" -> "🦮",
  "guide dog" -> "🦮",
  "service_dog" -> "🐕‍🦺",
  "service-dog" -> "🐕‍🦺",
  "service dog" -> "🐕‍🦺",
  "poodle" -> "🐩",
  "wolf" -> "🐺",
  "fox" -> "🦊",
  "fox_face" -> "🦊",
  "raccoon" -> "🦝",
  "cat_face" -> "🐱",
  "cat-face" -> "🐱",
  "cat face" -> "🐱",
  "cat" -> "🐱",
  "cat" -> "🐈",
  "cat2" -> "🐈",
  "black_cat" -> "🐈‍⬛",
  "black-cat" -> "🐈‍⬛",
  "black cat" -> "🐈‍⬛",
  "lion" -> "🦁",
)
