package io.github.edadma.markdown

val emojiBlock7 = List(
  "tiger_face" -> "🐯",
  "tiger-face" -> "🐯",
  "tiger face" -> "🐯",
  "tiger" -> "🐯",
  "tiger" -> "🐅",
  "tiger2" -> "🐅",
  "leopard" -> "🐆",
  "horse_face" -> "🐴",
  "horse-face" -> "🐴",
  "horse face" -> "🐴",
  "horse" -> "🐴",
  "moose" -> "🫎",
  "donkey" -> "🫏",
  "horse" -> "🐎",
  "racehorse" -> "🐎",
  "unicorn" -> "🦄",
  "zebra" -> "🦓",
  "deer" -> "🦌",
  "bison" -> "🦬",
  "cow_face" -> "🐮",
  "cow-face" -> "🐮",
  "cow face" -> "🐮",
  "cow" -> "🐮",
  "ox" -> "🐂",
  "water_buffalo" -> "🐃",
  "water-buffalo" -> "🐃",
  "water buffalo" -> "🐃",
  "cow" -> "🐄",
  "cow2" -> "🐄",
  "pig_face" -> "🐷",
  "pig-face" -> "🐷",
  "pig face" -> "🐷",
  "pig" -> "🐷",
  "pig" -> "🐖",
  "pig2" -> "🐖",
  "boar" -> "🐗",
  "pig_nose" -> "🐽",
  "pig-nose" -> "🐽",
  "pig nose" -> "🐽",
  "ram" -> "🐏",
  "ewe" -> "🐑",
  "sheep" -> "🐑",
  "goat" -> "🐐",
  "camel" -> "🐪",
  "dromedary_camel" -> "🐪",
  "two-hump_camel" -> "🐫",
  "two-hump-camel" -> "🐫",
  "two-hump camel" -> "🐫",
  "camel" -> "🐫",
  "llama" -> "🦙",
  "giraffe" -> "🦒",
  "elephant" -> "🐘",
  "mammoth" -> "🦣",
  "rhinoceros" -> "🦏",
  "hippopotamus" -> "🦛",
  "mouse_face" -> "🐭",
  "mouse-face" -> "🐭",
  "mouse face" -> "🐭",
  "mouse" -> "🐭",
  "mouse" -> "🐁",
  "mouse2" -> "🐁",
  "rat" -> "🐀",
  "hamster" -> "🐹",
  "rabbit_face" -> "🐰",
  "rabbit-face" -> "🐰",
  "rabbit face" -> "🐰",
  "rabbit" -> "🐰",
  "rabbit" -> "🐇",
  "rabbit2" -> "🐇",
  "chipmunk" -> "🐿️",
  "beaver" -> "🦫",
  "hedgehog" -> "🦔",
  "bat" -> "🦇",
  "bear" -> "🐻",
  "polar_bear" -> "🐻‍❄️",
  "polar-bear" -> "🐻‍❄️",
  "polar bear" -> "🐻‍❄️",
  "koala" -> "🐨",
  "panda" -> "🐼",
  "panda_face" -> "🐼",
  "sloth" -> "🦥",
  "otter" -> "🦦",
  "skunk" -> "🦨",
  "kangaroo" -> "🦘",
  "badger" -> "🦡",
  "paw_prints" -> "🐾",
  "paw-prints" -> "🐾",
  "paw prints" -> "🐾",
  "feet" -> "🐾",
  "turkey" -> "🦃",
  "chicken" -> "🐔",
  "rooster" -> "🐓",
  "hatching_chick" -> "🐣",
  "hatching-chick" -> "🐣",
  "hatching chick" -> "🐣",
  "baby_chick" -> "🐤",
  "baby-chick" -> "🐤",
  "baby chick" -> "🐤",
  "front-facing_baby_chick" -> "🐥",
  "front-facing-baby-chick" -> "🐥",
  "front-facing baby chick" -> "🐥",
  "hatched_chick" -> "🐥",
  "bird" -> "🐦",
  "penguin" -> "🐧",
  "dove" -> "🕊️",
  "eagle" -> "🦅",
  "duck" -> "🦆",
  "swan" -> "🦢",
  "owl" -> "🦉",
  "dodo" -> "🦤",
  "feather" -> "🪶",
  "flamingo" -> "🦩",
  "peacock" -> "🦚",
  "parrot" -> "🦜",
  "wing" -> "🪽",
  "black_bird" -> "🐦‍⬛",
  "black-bird" -> "🐦‍⬛",
  "black bird" -> "🐦‍⬛",
  "goose" -> "🪿",
  "frog" -> "🐸",
  "crocodile" -> "🐊",
  "turtle" -> "🐢",
  "lizard" -> "🦎",
  "snake" -> "🐍",
  "dragon_face" -> "🐲",
  "dragon-face" -> "🐲",
  "dragon face" -> "🐲",
  "dragon" -> "🐉",
  "sauropod" -> "🦕",
  "T-Rex" -> "🦖",
  "t-rex" -> "🦖",
  "spouting_whale" -> "🐳",
  "spouting-whale" -> "🐳",
  "spouting whale" -> "🐳",
  "whale" -> "🐳",
  "whale" -> "🐋",
  "whale2" -> "🐋",
  "dolphin" -> "🐬",
  "flipper" -> "🐬",
  "seal" -> "🦭",
  "fish" -> "🐟",
  "tropical_fish" -> "🐠",
  "tropical-fish" -> "🐠",
  "tropical fish" -> "🐠",
  "blowfish" -> "🐡",
  "shark" -> "🦈",
  "octopus" -> "🐙",
  "spiral_shell" -> "🐚",
  "spiral-shell" -> "🐚",
  "spiral shell" -> "🐚",
  "shell" -> "🐚",
  "coral" -> "🪸",
  "jellyfish" -> "🪼",
  "snail" -> "🐌",
  "butterfly" -> "🦋",
  "bug" -> "🐛",
  "ant" -> "🐜",
  "honeybee" -> "🐝",
  "bee" -> "🐝",
  "beetle" -> "🪲",
  "lady_beetle" -> "🐞",
  "lady-beetle" -> "🐞",
  "lady beetle" -> "🐞",
  "cricket" -> "🦗",
  "cockroach" -> "🪳",
  "spider" -> "🕷️",
  "spider_web" -> "🕸️",
  "spider-web" -> "🕸️",
  "spider web" -> "🕸️",
  "scorpion" -> "🦂",
  "mosquito" -> "🦟",
  "fly" -> "🪰",
  "worm" -> "🪱",
  "microbe" -> "🦠",
  "bouquet" -> "💐",
  "cherry_blossom" -> "🌸",
  "cherry-blossom" -> "🌸",
  "cherry blossom" -> "🌸",
  "white_flower" -> "💮",
  "white-flower" -> "💮",
  "white flower" -> "💮",
  "lotus" -> "🪷",
  "rosette" -> "🏵️",
  "rose" -> "🌹",
  "wilted_flower" -> "🥀",
  "wilted-flower" -> "🥀",
  "wilted flower" -> "🥀",
  "hibiscus" -> "🌺",
  "sunflower" -> "🌻",
  "blossom" -> "🌼",
  "tulip" -> "🌷",
  "hyacinth" -> "🪻",
  "seedling" -> "🌱",
  "potted_plant" -> "🪴",
  "potted-plant" -> "🪴",
  "potted plant" -> "🪴",
  "evergreen_tree" -> "🌲",
  "evergreen-tree" -> "🌲",
  "evergreen tree" -> "🌲",
  "deciduous_tree" -> "🌳",
  "deciduous-tree" -> "🌳",
  "deciduous tree" -> "🌳",
  "palm_tree" -> "🌴",
  "palm-tree" -> "🌴",
  "palm tree" -> "🌴",
  "cactus" -> "🌵",
  "sheaf_of_rice" -> "🌾",
  "sheaf-of-rice" -> "🌾",
  "sheaf of rice" -> "🌾",
  "ear_of_rice" -> "🌾",
  "herb" -> "🌿",
  "shamrock" -> "☘️",
  "four_leaf_clover" -> "🍀",
  "four-leaf-clover" -> "🍀",
  "four leaf clover" -> "🍀",
  "maple_leaf" -> "🍁",
  "maple-leaf" -> "🍁",
  "maple leaf" -> "🍁",
  "fallen_leaf" -> "🍂",
  "fallen-leaf" -> "🍂",
  "fallen leaf" -> "🍂",
  "leaf_fluttering_in_wind" -> "🍃",
  "leaf-fluttering-in-wind" -> "🍃",
  "leaf fluttering in wind" -> "🍃",
  "leaves" -> "🍃",
  "empty_nest" -> "🪹",
  "empty-nest" -> "🪹",
  "empty nest" -> "🪹",
  "nest_with_eggs" -> "🪺",
  "nest-with-eggs" -> "🪺",
  "nest with eggs" -> "🪺",
  "mushroom" -> "🍄",
  "grapes" -> "🍇",
  "melon" -> "🍈",
  "watermelon" -> "🍉",
  "tangerine" -> "🍊",
  "orange" -> "🍊",
  "mandarin" -> "🍊",
  "lemon" -> "🍋",
  "banana" -> "🍌",
  "pineapple" -> "🍍",
  "mango" -> "🥭",
  "red_apple" -> "🍎",
  "red-apple" -> "🍎",
  "red apple" -> "🍎",
  "apple" -> "🍎",
  "green_apple" -> "🍏",
  "green-apple" -> "🍏",
  "green apple" -> "🍏",
  "pear" -> "🍐",
  "peach" -> "🍑",
  "cherries" -> "🍒",
  "strawberry" -> "🍓",
  "blueberries" -> "🫐",
  "kiwi_fruit" -> "🥝",
  "kiwi-fruit" -> "🥝",
  "kiwi fruit" -> "🥝",
  "tomato" -> "🍅",
  "olive" -> "🫒",
  "coconut" -> "🥥",
  "avocado" -> "🥑",
  "eggplant" -> "🍆",
  "potato" -> "🥔",
  "carrot" -> "🥕",
  "ear_of_corn" -> "🌽",
  "ear-of-corn" -> "🌽",
  "ear of corn" -> "🌽",
  "corn" -> "🌽",
  "hot_pepper" -> "🌶️",
  "hot-pepper" -> "🌶️",
  "hot pepper" -> "🌶️",
  "bell_pepper" -> "🫑",
  "bell-pepper" -> "🫑",
  "bell pepper" -> "🫑",
  "cucumber" -> "🥒",
  "leafy_green" -> "🥬",
  "leafy-green" -> "🥬",
  "leafy green" -> "🥬",
  "broccoli" -> "🥦",
  "garlic" -> "🧄",
  "onion" -> "🧅",
  "peanuts" -> "🥜",
  "beans" -> "🫘",
  "chestnut" -> "🌰",
  "ginger_root" -> "🫚",
  "ginger-root" -> "🫚",
  "ginger root" -> "🫚",
  "pea_pod" -> "🫛",
  "pea-pod" -> "🫛",
  "pea pod" -> "🫛",
  "bread" -> "🍞",
  "croissant" -> "🥐",
  "baguette_bread" -> "🥖",
  "baguette-bread" -> "🥖",
  "baguette bread" -> "🥖",
  "flatbread" -> "🫓",
  "pretzel" -> "🥨",
  "bagel" -> "🥯",
  "pancakes" -> "🥞",
  "waffle" -> "🧇",
)
