package io.github.edadma.markdown

val emojiBlock17 = List(
  "flag_Georgia" -> "🇬🇪",
  "flag-Georgia" -> "🇬🇪",
  "flag Georgia" -> "🇬🇪",
  "georgia" -> "🇬🇪",
  "flag_French_Guiana" -> "🇬🇫",
  "flag-French-Guiana" -> "🇬🇫",
  "flag French Guiana" -> "🇬🇫",
  "french_guiana" -> "🇬🇫",
  "flag_Guernsey" -> "🇬🇬",
  "flag-Guernsey" -> "🇬🇬",
  "flag Guernsey" -> "🇬🇬",
  "guernsey" -> "🇬🇬",
  "flag_Ghana" -> "🇬🇭",
  "flag-Ghana" -> "🇬🇭",
  "flag Ghana" -> "🇬🇭",
  "ghana" -> "🇬🇭",
  "flag_Gibraltar" -> "🇬🇮",
  "flag-Gibraltar" -> "🇬🇮",
  "flag Gibraltar" -> "🇬🇮",
  "gibraltar" -> "🇬🇮",
  "flag_Greenland" -> "🇬🇱",
  "flag-Greenland" -> "🇬🇱",
  "flag Greenland" -> "🇬🇱",
  "greenland" -> "🇬🇱",
  "flag_Gambia" -> "🇬🇲",
  "flag-Gambia" -> "🇬🇲",
  "flag Gambia" -> "🇬🇲",
  "gambia" -> "🇬🇲",
  "flag_Guinea" -> "🇬🇳",
  "flag-Guinea" -> "🇬🇳",
  "flag Guinea" -> "🇬🇳",
  "guinea" -> "🇬🇳",
  "flag_Guadeloupe" -> "🇬🇵",
  "flag-Guadeloupe" -> "🇬🇵",
  "flag Guadeloupe" -> "🇬🇵",
  "guadeloupe" -> "🇬🇵",
  "flag_Equatorial_Guinea" -> "🇬🇶",
  "flag-Equatorial-Guinea" -> "🇬🇶",
  "flag Equatorial Guinea" -> "🇬🇶",
  "equatorial_guinea" -> "🇬🇶",
  "flag_Greece" -> "🇬🇷",
  "flag-Greece" -> "🇬🇷",
  "flag Greece" -> "🇬🇷",
  "greece" -> "🇬🇷",
  "flag_South_Georgia_&_South_Sandwich_Islands" -> "🇬🇸",
  "flag-South-Georgia-&-South-Sandwich-Islands" -> "🇬🇸",
  "flag South Georgia & South Sandwich Islands" -> "🇬🇸",
  "south_georgia_south_sandwich_islands" -> "🇬🇸",
  "flag_Guatemala" -> "🇬🇹",
  "flag-Guatemala" -> "🇬🇹",
  "flag Guatemala" -> "🇬🇹",
  "guatemala" -> "🇬🇹",
  "flag_Guam" -> "🇬🇺",
  "flag-Guam" -> "🇬🇺",
  "flag Guam" -> "🇬🇺",
  "guam" -> "🇬🇺",
  "flag_Guinea-Bissau" -> "🇬🇼",
  "flag-Guinea-Bissau" -> "🇬🇼",
  "flag Guinea-Bissau" -> "🇬🇼",
  "guinea_bissau" -> "🇬🇼",
  "flag_Guyana" -> "🇬🇾",
  "flag-Guyana" -> "🇬🇾",
  "flag Guyana" -> "🇬🇾",
  "guyana" -> "🇬🇾",
  "flag_Hong_Kong_SAR_China" -> "🇭🇰",
  "flag-Hong-Kong-SAR-China" -> "🇭🇰",
  "flag Hong Kong SAR China" -> "🇭🇰",
  "hong_kong" -> "🇭🇰",
  "flag_Heard_&_McDonald_Islands" -> "🇭🇲",
  "flag-Heard-&-McDonald-Islands" -> "🇭🇲",
  "flag Heard & McDonald Islands" -> "🇭🇲",
  "heard_mcdonald_islands" -> "🇭🇲",
  "flag_Honduras" -> "🇭🇳",
  "flag-Honduras" -> "🇭🇳",
  "flag Honduras" -> "🇭🇳",
  "honduras" -> "🇭🇳",
  "flag_Croatia" -> "🇭🇷",
  "flag-Croatia" -> "🇭🇷",
  "flag Croatia" -> "🇭🇷",
  "croatia" -> "🇭🇷",
  "flag_Haiti" -> "🇭🇹",
  "flag-Haiti" -> "🇭🇹",
  "flag Haiti" -> "🇭🇹",
  "haiti" -> "🇭🇹",
  "flag_Hungary" -> "🇭🇺",
  "flag-Hungary" -> "🇭🇺",
  "flag Hungary" -> "🇭🇺",
  "hungary" -> "🇭🇺",
  "flag_Canary_Islands" -> "🇮🇨",
  "flag-Canary-Islands" -> "🇮🇨",
  "flag Canary Islands" -> "🇮🇨",
  "canary_islands" -> "🇮🇨",
  "flag_Indonesia" -> "🇮🇩",
  "flag-Indonesia" -> "🇮🇩",
  "flag Indonesia" -> "🇮🇩",
  "indonesia" -> "🇮🇩",
  "flag_Ireland" -> "🇮🇪",
  "flag-Ireland" -> "🇮🇪",
  "flag Ireland" -> "🇮🇪",
  "ireland" -> "🇮🇪",
  "flag_Israel" -> "🇮🇱",
  "flag-Israel" -> "🇮🇱",
  "flag Israel" -> "🇮🇱",
  "israel" -> "🇮🇱",
  "flag_Isle_of_Man" -> "🇮🇲",
  "flag-Isle-of-Man" -> "🇮🇲",
  "flag Isle of Man" -> "🇮🇲",
  "isle_of_man" -> "🇮🇲",
  "flag_India" -> "🇮🇳",
  "flag-India" -> "🇮🇳",
  "flag India" -> "🇮🇳",
  "india" -> "🇮🇳",
  "flag_British_Indian_Ocean_Territory" -> "🇮🇴",
  "flag-British-Indian-Ocean-Territory" -> "🇮🇴",
  "flag British Indian Ocean Territory" -> "🇮🇴",
  "british_indian_ocean_territory" -> "🇮🇴",
  "flag_Iraq" -> "🇮🇶",
  "flag-Iraq" -> "🇮🇶",
  "flag Iraq" -> "🇮🇶",
  "iraq" -> "🇮🇶",
  "flag_Iran" -> "🇮🇷",
  "flag-Iran" -> "🇮🇷",
  "flag Iran" -> "🇮🇷",
  "iran" -> "🇮🇷",
  "flag_Iceland" -> "🇮🇸",
  "flag-Iceland" -> "🇮🇸",
  "flag Iceland" -> "🇮🇸",
  "iceland" -> "🇮🇸",
  "flag_Italy" -> "🇮🇹",
  "flag-Italy" -> "🇮🇹",
  "flag Italy" -> "🇮🇹",
  "it" -> "🇮🇹",
  "flag_Jersey" -> "🇯🇪",
  "flag-Jersey" -> "🇯🇪",
  "flag Jersey" -> "🇯🇪",
  "jersey" -> "🇯🇪",
  "flag_Jamaica" -> "🇯🇲",
  "flag-Jamaica" -> "🇯🇲",
  "flag Jamaica" -> "🇯🇲",
  "jamaica" -> "🇯🇲",
  "flag_Jordan" -> "🇯🇴",
  "flag-Jordan" -> "🇯🇴",
  "flag Jordan" -> "🇯🇴",
  "jordan" -> "🇯🇴",
  "flag_Japan" -> "🇯🇵",
  "flag-Japan" -> "🇯🇵",
  "flag Japan" -> "🇯🇵",
  "jp" -> "🇯🇵",
  "flag_Kenya" -> "🇰🇪",
  "flag-Kenya" -> "🇰🇪",
  "flag Kenya" -> "🇰🇪",
  "kenya" -> "🇰🇪",
  "flag_Kyrgyzstan" -> "🇰🇬",
  "flag-Kyrgyzstan" -> "🇰🇬",
  "flag Kyrgyzstan" -> "🇰🇬",
  "kyrgyzstan" -> "🇰🇬",
  "flag_Cambodia" -> "🇰🇭",
  "flag-Cambodia" -> "🇰🇭",
  "flag Cambodia" -> "🇰🇭",
  "cambodia" -> "🇰🇭",
  "flag_Kiribati" -> "🇰🇮",
  "flag-Kiribati" -> "🇰🇮",
  "flag Kiribati" -> "🇰🇮",
  "kiribati" -> "🇰🇮",
  "flag_Comoros" -> "🇰🇲",
  "flag-Comoros" -> "🇰🇲",
  "flag Comoros" -> "🇰🇲",
  "comoros" -> "🇰🇲",
  "flag_St._Kitts_&_Nevis" -> "🇰🇳",
  "flag-St.-Kitts-&-Nevis" -> "🇰🇳",
  "flag St. Kitts & Nevis" -> "🇰🇳",
  "st_kitts_nevis" -> "🇰🇳",
  "flag_North_Korea" -> "🇰🇵",
  "flag-North-Korea" -> "🇰🇵",
  "flag North Korea" -> "🇰🇵",
  "north_korea" -> "🇰🇵",
  "flag_South_Korea" -> "🇰🇷",
  "flag-South-Korea" -> "🇰🇷",
  "flag South Korea" -> "🇰🇷",
  "kr" -> "🇰🇷",
  "flag_Kuwait" -> "🇰🇼",
  "flag-Kuwait" -> "🇰🇼",
  "flag Kuwait" -> "🇰🇼",
  "kuwait" -> "🇰🇼",
  "flag_Cayman_Islands" -> "🇰🇾",
  "flag-Cayman-Islands" -> "🇰🇾",
  "flag Cayman Islands" -> "🇰🇾",
  "cayman_islands" -> "🇰🇾",
  "flag_Kazakhstan" -> "🇰🇿",
  "flag-Kazakhstan" -> "🇰🇿",
  "flag Kazakhstan" -> "🇰🇿",
  "kazakhstan" -> "🇰🇿",
  "flag_Laos" -> "🇱🇦",
  "flag-Laos" -> "🇱🇦",
  "flag Laos" -> "🇱🇦",
  "laos" -> "🇱🇦",
  "flag_Lebanon" -> "🇱🇧",
  "flag-Lebanon" -> "🇱🇧",
  "flag Lebanon" -> "🇱🇧",
  "lebanon" -> "🇱🇧",
  "flag_St._Lucia" -> "🇱🇨",
  "flag-St.-Lucia" -> "🇱🇨",
  "flag St. Lucia" -> "🇱🇨",
  "st_lucia" -> "🇱🇨",
  "flag_Liechtenstein" -> "🇱🇮",
  "flag-Liechtenstein" -> "🇱🇮",
  "flag Liechtenstein" -> "🇱🇮",
  "liechtenstein" -> "🇱🇮",
  "flag_Sri_Lanka" -> "🇱🇰",
  "flag-Sri-Lanka" -> "🇱🇰",
  "flag Sri Lanka" -> "🇱🇰",
  "sri_lanka" -> "🇱🇰",
  "flag_Liberia" -> "🇱🇷",
  "flag-Liberia" -> "🇱🇷",
  "flag Liberia" -> "🇱🇷",
  "liberia" -> "🇱🇷",
  "flag_Lesotho" -> "🇱🇸",
  "flag-Lesotho" -> "🇱🇸",
  "flag Lesotho" -> "🇱🇸",
  "lesotho" -> "🇱🇸",
  "flag_Lithuania" -> "🇱🇹",
  "flag-Lithuania" -> "🇱🇹",
  "flag Lithuania" -> "🇱🇹",
  "lithuania" -> "🇱🇹",
  "flag_Luxembourg" -> "🇱🇺",
  "flag-Luxembourg" -> "🇱🇺",
  "flag Luxembourg" -> "🇱🇺",
  "luxembourg" -> "🇱🇺",
  "flag_Latvia" -> "🇱🇻",
  "flag-Latvia" -> "🇱🇻",
  "flag Latvia" -> "🇱🇻",
  "latvia" -> "🇱🇻",
  "flag_Libya" -> "🇱🇾",
  "flag-Libya" -> "🇱🇾",
  "flag Libya" -> "🇱🇾",
  "libya" -> "🇱🇾",
  "flag_Morocco" -> "🇲🇦",
  "flag-Morocco" -> "🇲🇦",
  "flag Morocco" -> "🇲🇦",
  "morocco" -> "🇲🇦",
  "flag_Monaco" -> "🇲🇨",
  "flag-Monaco" -> "🇲🇨",
  "flag Monaco" -> "🇲🇨",
  "monaco" -> "🇲🇨",
  "flag_Moldova" -> "🇲🇩",
  "flag-Moldova" -> "🇲🇩",
  "flag Moldova" -> "🇲🇩",
  "moldova" -> "🇲🇩",
  "flag_Montenegro" -> "🇲🇪",
  "flag-Montenegro" -> "🇲🇪",
  "flag Montenegro" -> "🇲🇪",
  "montenegro" -> "🇲🇪",
  "flag_St._Martin" -> "🇲🇫",
  "flag-St.-Martin" -> "🇲🇫",
  "flag St. Martin" -> "🇲🇫",
  "st_martin" -> "🇲🇫",
  "flag_Madagascar" -> "🇲🇬",
  "flag-Madagascar" -> "🇲🇬",
  "flag Madagascar" -> "🇲🇬",
  "madagascar" -> "🇲🇬",
  "flag_Marshall_Islands" -> "🇲🇭",
  "flag-Marshall-Islands" -> "🇲🇭",
  "flag Marshall Islands" -> "🇲🇭",
  "marshall_islands" -> "🇲🇭",
  "flag_North_Macedonia" -> "🇲🇰",
  "flag-North-Macedonia" -> "🇲🇰",
  "flag North Macedonia" -> "🇲🇰",
  "macedonia" -> "🇲🇰",
  "flag_Mali" -> "🇲🇱",
  "flag-Mali" -> "🇲🇱",
  "flag Mali" -> "🇲🇱",
  "mali" -> "🇲🇱",
  "flag_Myanmar_(Burma)" -> "🇲🇲",
  "flag-Myanmar-(Burma)" -> "🇲🇲",
  "flag Myanmar (Burma)" -> "🇲🇲",
  "myanmar" -> "🇲🇲",
  "flag_Mongolia" -> "🇲🇳",
  "flag-Mongolia" -> "🇲🇳",
  "flag Mongolia" -> "🇲🇳",
  "mongolia" -> "🇲🇳",
  "flag_Macao_SAR_China" -> "🇲🇴",
  "flag-Macao-SAR-China" -> "🇲🇴",
  "flag Macao SAR China" -> "🇲🇴",
  "macau" -> "🇲🇴",
  "flag_Northern_Mariana_Islands" -> "🇲🇵",
  "flag-Northern-Mariana-Islands" -> "🇲🇵",
  "flag Northern Mariana Islands" -> "🇲🇵",
  "northern_mariana_islands" -> "🇲🇵",
  "flag_Martinique" -> "🇲🇶",
  "flag-Martinique" -> "🇲🇶",
  "flag Martinique" -> "🇲🇶",
  "martinique" -> "🇲🇶",
  "flag_Mauritania" -> "🇲🇷",
  "flag-Mauritania" -> "🇲🇷",
  "flag Mauritania" -> "🇲🇷",
  "mauritania" -> "🇲🇷",
  "flag_Montserrat" -> "🇲🇸",
  "flag-Montserrat" -> "🇲🇸",
  "flag Montserrat" -> "🇲🇸",
  "montserrat" -> "🇲🇸",
)
