package io.github.edadma.markdown

val emojiBlock2 = List(
  "face_holding_back_tears" -> "🥹",
  "face-holding-back-tears" -> "🥹",
  "face holding back tears" -> "🥹",
  "frowning_face_with_open_mouth" -> "😦",
  "frowning-face-with-open-mouth" -> "😦",
  "frowning face with open mouth" -> "😦",
  "frowning" -> "😦",
  "anguished_face" -> "😧",
  "anguished-face" -> "😧",
  "anguished face" -> "😧",
  "anguished" -> "😧",
  "fearful_face" -> "😨",
  "fearful-face" -> "😨",
  "fearful face" -> "😨",
  "fearful" -> "😨",
  "anxious_face_with_sweat" -> "😰",
  "anxious-face-with-sweat" -> "😰",
  "anxious face with sweat" -> "😰",
  "cold_sweat" -> "😰",
  "sad_but_relieved_face" -> "😥",
  "sad-but-relieved-face" -> "😥",
  "sad but relieved face" -> "😥",
  "disappointed_relieved" -> "😥",
  "crying_face" -> "😢",
  "crying-face" -> "😢",
  "crying face" -> "😢",
  "cry" -> "😢",
  "loudly_crying_face" -> "😭",
  "loudly-crying-face" -> "😭",
  "loudly crying face" -> "😭",
  "sob" -> "😭",
  "face_screaming_in_fear" -> "😱",
  "face-screaming-in-fear" -> "😱",
  "face screaming in fear" -> "😱",
  "scream" -> "😱",
  "confounded_face" -> "😖",
  "confounded-face" -> "😖",
  "confounded face" -> "😖",
  "confounded" -> "😖",
  "persevering_face" -> "😣",
  "persevering-face" -> "😣",
  "persevering face" -> "😣",
  "persevere" -> "😣",
  "disappointed_face" -> "😞",
  "disappointed-face" -> "😞",
  "disappointed face" -> "😞",
  "disappointed" -> "😞",
  "downcast_face_with_sweat" -> "😓",
  "downcast-face-with-sweat" -> "😓",
  "downcast face with sweat" -> "😓",
  "sweat" -> "😓",
  "weary_face" -> "😩",
  "weary-face" -> "😩",
  "weary face" -> "😩",
  "weary" -> "😩",
  "tired_face" -> "😫",
  "tired-face" -> "😫",
  "tired face" -> "😫",
  "yawning_face" -> "🥱",
  "yawning-face" -> "🥱",
  "yawning face" -> "🥱",
  "face_with_steam_from_nose" -> "😤",
  "face-with-steam-from-nose" -> "😤",
  "face with steam from nose" -> "😤",
  "triumph" -> "😤",
  "enraged_face" -> "😡",
  "enraged-face" -> "😡",
  "enraged face" -> "😡",
  "rage" -> "😡",
  "pout" -> "😡",
  "angry_face" -> "😠",
  "angry-face" -> "😠",
  "angry face" -> "😠",
  "angry" -> "😠",
  "face_with_symbols_on_mouth" -> "🤬",
  "face-with-symbols-on-mouth" -> "🤬",
  "face with symbols on mouth" -> "🤬",
  "cursing_face" -> "🤬",
  "smiling_face_with_horns" -> "😈",
  "smiling-face-with-horns" -> "😈",
  "smiling face with horns" -> "😈",
  "smiling_imp" -> "😈",
  "angry_face_with_horns" -> "👿",
  "angry-face-with-horns" -> "👿",
  "angry face with horns" -> "👿",
  "imp" -> "👿",
  "skull" -> "💀",
  "skull_and_crossbones" -> "☠️",
  "skull-and-crossbones" -> "☠️",
  "skull and crossbones" -> "☠️",
  "pile_of_poo" -> "💩",
  "pile-of-poo" -> "💩",
  "pile of poo" -> "💩",
  "hankey" -> "💩",
  "poop" -> "💩",
  "shit" -> "💩",
  "clown_face" -> "🤡",
  "clown-face" -> "🤡",
  "clown face" -> "🤡",
  "ogre" -> "👹",
  "japanese_ogre" -> "👹",
  "goblin" -> "👺",
  "japanese_goblin" -> "👺",
  "ghost" -> "👻",
  "alien" -> "👽",
  "alien_monster" -> "👾",
  "alien-monster" -> "👾",
  "alien monster" -> "👾",
  "space_invader" -> "👾",
  "robot" -> "🤖",
  "grinning_cat" -> "😺",
  "grinning-cat" -> "😺",
  "grinning cat" -> "😺",
  "smiley_cat" -> "😺",
  "grinning_cat_with_smiling_eyes" -> "😸",
  "grinning-cat-with-smiling-eyes" -> "😸",
  "grinning cat with smiling eyes" -> "😸",
  "smile_cat" -> "😸",
  "cat_with_tears_of_joy" -> "😹",
  "cat-with-tears-of-joy" -> "😹",
  "cat with tears of joy" -> "😹",
  "joy_cat" -> "😹",
  "smiling_cat_with_heart-eyes" -> "😻",
  "smiling-cat-with-heart-eyes" -> "😻",
  "smiling cat with heart-eyes" -> "😻",
  "heart_eyes_cat" -> "😻",
  "cat_with_wry_smile" -> "😼",
  "cat-with-wry-smile" -> "😼",
  "cat with wry smile" -> "😼",
  "smirk_cat" -> "😼",
  "kissing_cat" -> "😽",
  "kissing-cat" -> "😽",
  "kissing cat" -> "😽",
  "weary_cat" -> "🙀",
  "weary-cat" -> "🙀",
  "weary cat" -> "🙀",
  "scream_cat" -> "🙀",
  "crying_cat" -> "😿",
  "crying-cat" -> "😿",
  "crying cat" -> "😿",
  "crying_cat_face" -> "😿",
  "pouting_cat" -> "😾",
  "pouting-cat" -> "😾",
  "pouting cat" -> "😾",
  "see-no-evil_monkey" -> "🙈",
  "see-no-evil-monkey" -> "🙈",
  "see-no-evil monkey" -> "🙈",
  "see_no_evil" -> "🙈",
  "hear-no-evil_monkey" -> "🙉",
  "hear-no-evil-monkey" -> "🙉",
  "hear-no-evil monkey" -> "🙉",
  "hear_no_evil" -> "🙉",
  "speak-no-evil_monkey" -> "🙊",
  "speak-no-evil-monkey" -> "🙊",
  "speak-no-evil monkey" -> "🙊",
  "speak_no_evil" -> "🙊",
  "love_letter" -> "💌",
  "love-letter" -> "💌",
  "love letter" -> "💌",
  "heart_with_arrow" -> "💘",
  "heart-with-arrow" -> "💘",
  "heart with arrow" -> "💘",
  "cupid" -> "💘",
  "heart_with_ribbon" -> "💝",
  "heart-with-ribbon" -> "💝",
  "heart with ribbon" -> "💝",
  "gift_heart" -> "💝",
  "sparkling_heart" -> "💖",
  "sparkling-heart" -> "💖",
  "sparkling heart" -> "💖",
  "growing_heart" -> "💗",
  "growing-heart" -> "💗",
  "growing heart" -> "💗",
  "heartpulse" -> "💗",
  "beating_heart" -> "💓",
  "beating-heart" -> "💓",
  "beating heart" -> "💓",
  "heartbeat" -> "💓",
  "revolving_hearts" -> "💞",
  "revolving-hearts" -> "💞",
  "revolving hearts" -> "💞",
  "two_hearts" -> "💕",
  "two-hearts" -> "💕",
  "two hearts" -> "💕",
  "heart_decoration" -> "💟",
  "heart-decoration" -> "💟",
  "heart decoration" -> "💟",
  "heart_exclamation" -> "❣️",
  "heart-exclamation" -> "❣️",
  "heart exclamation" -> "❣️",
  "heavy_heart_exclamation" -> "❣️",
  "broken_heart" -> "💔",
  "broken-heart" -> "💔",
  "broken heart" -> "💔",
  "heart_on_fire" -> "❤️‍🔥",
  "heart-on-fire" -> "❤️‍🔥",
  "heart on fire" -> "❤️‍🔥",
  "mending_heart" -> "❤️‍🩹",
  "mending-heart" -> "❤️‍🩹",
  "mending heart" -> "❤️‍🩹",
  "red_heart" -> "❤️",
  "red-heart" -> "❤️",
  "red heart" -> "❤️",
  "heart" -> "❤️",
  "pink_heart" -> "🩷",
  "pink-heart" -> "🩷",
  "pink heart" -> "🩷",
  "orange_heart" -> "🧡",
  "orange-heart" -> "🧡",
  "orange heart" -> "🧡",
  "yellow_heart" -> "💛",
  "yellow-heart" -> "💛",
  "yellow heart" -> "💛",
  "green_heart" -> "💚",
  "green-heart" -> "💚",
  "green heart" -> "💚",
  "blue_heart" -> "💙",
  "blue-heart" -> "💙",
  "blue heart" -> "💙",
  "light_blue_heart" -> "🩵",
  "light-blue-heart" -> "🩵",
  "light blue heart" -> "🩵",
  "purple_heart" -> "💜",
  "purple-heart" -> "💜",
  "purple heart" -> "💜",
  "brown_heart" -> "🤎",
  "brown-heart" -> "🤎",
  "brown heart" -> "🤎",
  "black_heart" -> "🖤",
  "black-heart" -> "🖤",
  "black heart" -> "🖤",
  "grey_heart" -> "🩶",
  "grey-heart" -> "🩶",
  "grey heart" -> "🩶",
  "white_heart" -> "🤍",
  "white-heart" -> "🤍",
  "white heart" -> "🤍",
  "kiss_mark" -> "💋",
  "kiss-mark" -> "💋",
  "kiss mark" -> "💋",
  "kiss" -> "💋",
  "hundred_points" -> "💯",
  "hundred-points" -> "💯",
  "hundred points" -> "💯",
  "100" -> "💯",
  "anger_symbol" -> "💢",
  "anger-symbol" -> "💢",
  "anger symbol" -> "💢",
  "anger" -> "💢",
  "collision" -> "💥",
  "boom" -> "💥",
  "dizzy" -> "💫",
  "sweat_droplets" -> "💦",
  "sweat-droplets" -> "💦",
  "sweat droplets" -> "💦",
  "sweat_drops" -> "💦",
  "dashing_away" -> "💨",
  "dashing-away" -> "💨",
  "dashing away" -> "💨",
  "dash" -> "💨",
  "hole" -> "🕳️",
  "speech_balloon" -> "💬",
  "speech-balloon" -> "💬",
  "speech balloon" -> "💬",
  "eye_in_speech_bubble" -> "👁️‍🗨️",
  "eye-in-speech-bubble" -> "👁️‍🗨️",
  "eye in speech bubble" -> "👁️‍🗨️",
  "eye_speech_bubble" -> "👁️‍🗨️",
  "left_speech_bubble" -> "🗨️",
  "left-speech-bubble" -> "🗨️",
  "left speech bubble" -> "🗨️",
  "right_anger_bubble" -> "🗯️",
  "right-anger-bubble" -> "🗯️",
  "right anger bubble" -> "🗯️",
  "thought_balloon" -> "💭",
  "thought-balloon" -> "💭",
  "thought balloon" -> "💭",
  "ZZZ" -> "💤",
  "zzz" -> "💤",
  "waving_hand" -> "👋",
  "waving-hand" -> "👋",
  "waving hand" -> "👋",
  "wave" -> "👋",
  "raised_back_of_hand" -> "🤚",
  "raised-back-of-hand" -> "🤚",
  "raised back of hand" -> "🤚",
  "hand_with_fingers_splayed" -> "🖐️",
  "hand-with-fingers-splayed" -> "🖐️",
  "hand with fingers splayed" -> "🖐️",
  "raised_hand_with_fingers_splayed" -> "🖐️",
  "raised_hand" -> "✋",
  "raised-hand" -> "✋",
  "raised hand" -> "✋",
  "hand" -> "✋",
  "vulcan_salute" -> "🖖",
  "vulcan-salute" -> "🖖",
  "vulcan salute" -> "🖖",
  "rightwards_hand" -> "🫱",
  "rightwards-hand" -> "🫱",
  "rightwards hand" -> "🫱",
)
