package io.github.edadma.markdown

val emojiBlock18 = List(
  "flag_Malta" -> "🇲🇹",
  "flag-Malta" -> "🇲🇹",
  "flag Malta" -> "🇲🇹",
  "malta" -> "🇲🇹",
  "flag_Mauritius" -> "🇲🇺",
  "flag-Mauritius" -> "🇲🇺",
  "flag Mauritius" -> "🇲🇺",
  "mauritius" -> "🇲🇺",
  "flag_Maldives" -> "🇲🇻",
  "flag-Maldives" -> "🇲🇻",
  "flag Maldives" -> "🇲🇻",
  "maldives" -> "🇲🇻",
  "flag_Malawi" -> "🇲🇼",
  "flag-Malawi" -> "🇲🇼",
  "flag Malawi" -> "🇲🇼",
  "malawi" -> "🇲🇼",
  "flag_Mexico" -> "🇲🇽",
  "flag-Mexico" -> "🇲🇽",
  "flag Mexico" -> "🇲🇽",
  "mexico" -> "🇲🇽",
  "flag_Malaysia" -> "🇲🇾",
  "flag-Malaysia" -> "🇲🇾",
  "flag Malaysia" -> "🇲🇾",
  "malaysia" -> "🇲🇾",
  "flag_Mozambique" -> "🇲🇿",
  "flag-Mozambique" -> "🇲🇿",
  "flag Mozambique" -> "🇲🇿",
  "mozambique" -> "🇲🇿",
  "flag_Namibia" -> "🇳🇦",
  "flag-Namibia" -> "🇳🇦",
  "flag Namibia" -> "🇳🇦",
  "namibia" -> "🇳🇦",
  "flag_New_Caledonia" -> "🇳🇨",
  "flag-New-Caledonia" -> "🇳🇨",
  "flag New Caledonia" -> "🇳🇨",
  "new_caledonia" -> "🇳🇨",
  "flag_Niger" -> "🇳🇪",
  "flag-Niger" -> "🇳🇪",
  "flag Niger" -> "🇳🇪",
  "niger" -> "🇳🇪",
  "flag_Norfolk_Island" -> "🇳🇫",
  "flag-Norfolk-Island" -> "🇳🇫",
  "flag Norfolk Island" -> "🇳🇫",
  "norfolk_island" -> "🇳🇫",
  "flag_Nigeria" -> "🇳🇬",
  "flag-Nigeria" -> "🇳🇬",
  "flag Nigeria" -> "🇳🇬",
  "nigeria" -> "🇳🇬",
  "flag_Nicaragua" -> "🇳🇮",
  "flag-Nicaragua" -> "🇳🇮",
  "flag Nicaragua" -> "🇳🇮",
  "nicaragua" -> "🇳🇮",
  "flag_Netherlands" -> "🇳🇱",
  "flag-Netherlands" -> "🇳🇱",
  "flag Netherlands" -> "🇳🇱",
  "netherlands" -> "🇳🇱",
  "flag_Norway" -> "🇳🇴",
  "flag-Norway" -> "🇳🇴",
  "flag Norway" -> "🇳🇴",
  "norway" -> "🇳🇴",
  "flag_Nepal" -> "🇳🇵",
  "flag-Nepal" -> "🇳🇵",
  "flag Nepal" -> "🇳🇵",
  "nepal" -> "🇳🇵",
  "flag_Nauru" -> "🇳🇷",
  "flag-Nauru" -> "🇳🇷",
  "flag Nauru" -> "🇳🇷",
  "nauru" -> "🇳🇷",
  "flag_Niue" -> "🇳🇺",
  "flag-Niue" -> "🇳🇺",
  "flag Niue" -> "🇳🇺",
  "niue" -> "🇳🇺",
  "flag_New_Zealand" -> "🇳🇿",
  "flag-New-Zealand" -> "🇳🇿",
  "flag New Zealand" -> "🇳🇿",
  "new_zealand" -> "🇳🇿",
  "flag_Oman" -> "🇴🇲",
  "flag-Oman" -> "🇴🇲",
  "flag Oman" -> "🇴🇲",
  "oman" -> "🇴🇲",
  "flag_Panama" -> "🇵🇦",
  "flag-Panama" -> "🇵🇦",
  "flag Panama" -> "🇵🇦",
  "panama" -> "🇵🇦",
  "flag_Peru" -> "🇵🇪",
  "flag-Peru" -> "🇵🇪",
  "flag Peru" -> "🇵🇪",
  "peru" -> "🇵🇪",
  "flag_French_Polynesia" -> "🇵🇫",
  "flag-French-Polynesia" -> "🇵🇫",
  "flag French Polynesia" -> "🇵🇫",
  "french_polynesia" -> "🇵🇫",
  "flag_Papua_New_Guinea" -> "🇵🇬",
  "flag-Papua-New-Guinea" -> "🇵🇬",
  "flag Papua New Guinea" -> "🇵🇬",
  "papua_new_guinea" -> "🇵🇬",
  "flag_Philippines" -> "🇵🇭",
  "flag-Philippines" -> "🇵🇭",
  "flag Philippines" -> "🇵🇭",
  "philippines" -> "🇵🇭",
  "flag_Pakistan" -> "🇵🇰",
  "flag-Pakistan" -> "🇵🇰",
  "flag Pakistan" -> "🇵🇰",
  "pakistan" -> "🇵🇰",
  "flag_Poland" -> "🇵🇱",
  "flag-Poland" -> "🇵🇱",
  "flag Poland" -> "🇵🇱",
  "poland" -> "🇵🇱",
  "flag_St._Pierre_&_Miquelon" -> "🇵🇲",
  "flag-St.-Pierre-&-Miquelon" -> "🇵🇲",
  "flag St. Pierre & Miquelon" -> "🇵🇲",
  "st_pierre_miquelon" -> "🇵🇲",
  "flag_Pitcairn_Islands" -> "🇵🇳",
  "flag-Pitcairn-Islands" -> "🇵🇳",
  "flag Pitcairn Islands" -> "🇵🇳",
  "pitcairn_islands" -> "🇵🇳",
  "flag_Puerto_Rico" -> "🇵🇷",
  "flag-Puerto-Rico" -> "🇵🇷",
  "flag Puerto Rico" -> "🇵🇷",
  "puerto_rico" -> "🇵🇷",
  "flag_Palestinian_Territories" -> "🇵🇸",
  "flag-Palestinian-Territories" -> "🇵🇸",
  "flag Palestinian Territories" -> "🇵🇸",
  "palestinian_territories" -> "🇵🇸",
  "flag_Portugal" -> "🇵🇹",
  "flag-Portugal" -> "🇵🇹",
  "flag Portugal" -> "🇵🇹",
  "portugal" -> "🇵🇹",
  "flag_Palau" -> "🇵🇼",
  "flag-Palau" -> "🇵🇼",
  "flag Palau" -> "🇵🇼",
  "palau" -> "🇵🇼",
  "flag_Paraguay" -> "🇵🇾",
  "flag-Paraguay" -> "🇵🇾",
  "flag Paraguay" -> "🇵🇾",
  "paraguay" -> "🇵🇾",
  "flag_Qatar" -> "🇶🇦",
  "flag-Qatar" -> "🇶🇦",
  "flag Qatar" -> "🇶🇦",
  "qatar" -> "🇶🇦",
  "flag_Réunion" -> "🇷🇪",
  "flag-Réunion" -> "🇷🇪",
  "flag Réunion" -> "🇷🇪",
  "reunion" -> "🇷🇪",
  "flag_Romania" -> "🇷🇴",
  "flag-Romania" -> "🇷🇴",
  "flag Romania" -> "🇷🇴",
  "romania" -> "🇷🇴",
  "flag_Serbia" -> "🇷🇸",
  "flag-Serbia" -> "🇷🇸",
  "flag Serbia" -> "🇷🇸",
  "serbia" -> "🇷🇸",
  "flag_Russia" -> "🇷🇺",
  "flag-Russia" -> "🇷🇺",
  "flag Russia" -> "🇷🇺",
  "ru" -> "🇷🇺",
  "flag_Rwanda" -> "🇷🇼",
  "flag-Rwanda" -> "🇷🇼",
  "flag Rwanda" -> "🇷🇼",
  "rwanda" -> "🇷🇼",
  "flag_Saudi_Arabia" -> "🇸🇦",
  "flag-Saudi-Arabia" -> "🇸🇦",
  "flag Saudi Arabia" -> "🇸🇦",
  "saudi_arabia" -> "🇸🇦",
  "flag_Solomon_Islands" -> "🇸🇧",
  "flag-Solomon-Islands" -> "🇸🇧",
  "flag Solomon Islands" -> "🇸🇧",
  "solomon_islands" -> "🇸🇧",
  "flag_Seychelles" -> "🇸🇨",
  "flag-Seychelles" -> "🇸🇨",
  "flag Seychelles" -> "🇸🇨",
  "seychelles" -> "🇸🇨",
  "flag_Sudan" -> "🇸🇩",
  "flag-Sudan" -> "🇸🇩",
  "flag Sudan" -> "🇸🇩",
  "sudan" -> "🇸🇩",
  "flag_Sweden" -> "🇸🇪",
  "flag-Sweden" -> "🇸🇪",
  "flag Sweden" -> "🇸🇪",
  "sweden" -> "🇸🇪",
  "flag_Singapore" -> "🇸🇬",
  "flag-Singapore" -> "🇸🇬",
  "flag Singapore" -> "🇸🇬",
  "singapore" -> "🇸🇬",
  "flag_St._Helena" -> "🇸🇭",
  "flag-St.-Helena" -> "🇸🇭",
  "flag St. Helena" -> "🇸🇭",
  "st_helena" -> "🇸🇭",
  "flag_Slovenia" -> "🇸🇮",
  "flag-Slovenia" -> "🇸🇮",
  "flag Slovenia" -> "🇸🇮",
  "slovenia" -> "🇸🇮",
  "flag_Svalbard_&_Jan_Mayen" -> "🇸🇯",
  "flag-Svalbard-&-Jan-Mayen" -> "🇸🇯",
  "flag Svalbard & Jan Mayen" -> "🇸🇯",
  "svalbard_jan_mayen" -> "🇸🇯",
  "flag_Slovakia" -> "🇸🇰",
  "flag-Slovakia" -> "🇸🇰",
  "flag Slovakia" -> "🇸🇰",
  "slovakia" -> "🇸🇰",
  "flag_Sierra_Leone" -> "🇸🇱",
  "flag-Sierra-Leone" -> "🇸🇱",
  "flag Sierra Leone" -> "🇸🇱",
  "sierra_leone" -> "🇸🇱",
  "flag_San_Marino" -> "🇸🇲",
  "flag-San-Marino" -> "🇸🇲",
  "flag San Marino" -> "🇸🇲",
  "san_marino" -> "🇸🇲",
  "flag_Senegal" -> "🇸🇳",
  "flag-Senegal" -> "🇸🇳",
  "flag Senegal" -> "🇸🇳",
  "senegal" -> "🇸🇳",
  "flag_Somalia" -> "🇸🇴",
  "flag-Somalia" -> "🇸🇴",
  "flag Somalia" -> "🇸🇴",
  "somalia" -> "🇸🇴",
  "flag_Suriname" -> "🇸🇷",
  "flag-Suriname" -> "🇸🇷",
  "flag Suriname" -> "🇸🇷",
  "suriname" -> "🇸🇷",
  "flag_South_Sudan" -> "🇸🇸",
  "flag-South-Sudan" -> "🇸🇸",
  "flag South Sudan" -> "🇸🇸",
  "south_sudan" -> "🇸🇸",
  "flag_São_Tomé_&_Príncipe" -> "🇸🇹",
  "flag-São-Tomé-&-Príncipe" -> "🇸🇹",
  "flag São Tomé & Príncipe" -> "🇸🇹",
  "sao_tome_principe" -> "🇸🇹",
  "flag_El_Salvador" -> "🇸🇻",
  "flag-El-Salvador" -> "🇸🇻",
  "flag El Salvador" -> "🇸🇻",
  "el_salvador" -> "🇸🇻",
  "flag_Sint_Maarten" -> "🇸🇽",
  "flag-Sint-Maarten" -> "🇸🇽",
  "flag Sint Maarten" -> "🇸🇽",
  "sint_maarten" -> "🇸🇽",
  "flag_Syria" -> "🇸🇾",
  "flag-Syria" -> "🇸🇾",
  "flag Syria" -> "🇸🇾",
  "syria" -> "🇸🇾",
  "flag_Eswatini" -> "🇸🇿",
  "flag-Eswatini" -> "🇸🇿",
  "flag Eswatini" -> "🇸🇿",
  "swaziland" -> "🇸🇿",
  "flag_Tristan_da_Cunha" -> "🇹🇦",
  "flag-Tristan-da-Cunha" -> "🇹🇦",
  "flag Tristan da Cunha" -> "🇹🇦",
  "tristan_da_cunha" -> "🇹🇦",
  "flag_Turks_&_Caicos_Islands" -> "🇹🇨",
  "flag-Turks-&-Caicos-Islands" -> "🇹🇨",
  "flag Turks & Caicos Islands" -> "🇹🇨",
  "turks_caicos_islands" -> "🇹🇨",
  "flag_Chad" -> "🇹🇩",
  "flag-Chad" -> "🇹🇩",
  "flag Chad" -> "🇹🇩",
  "chad" -> "🇹🇩",
  "flag_French_Southern_Territories" -> "🇹🇫",
  "flag-French-Southern-Territories" -> "🇹🇫",
  "flag French Southern Territories" -> "🇹🇫",
  "french_southern_territories" -> "🇹🇫",
  "flag_Togo" -> "🇹🇬",
  "flag-Togo" -> "🇹🇬",
  "flag Togo" -> "🇹🇬",
  "togo" -> "🇹🇬",
  "flag_Thailand" -> "🇹🇭",
  "flag-Thailand" -> "🇹🇭",
  "flag Thailand" -> "🇹🇭",
  "thailand" -> "🇹🇭",
  "flag_Tajikistan" -> "🇹🇯",
  "flag-Tajikistan" -> "🇹🇯",
  "flag Tajikistan" -> "🇹🇯",
  "tajikistan" -> "🇹🇯",
  "flag_Tokelau" -> "🇹🇰",
  "flag-Tokelau" -> "🇹🇰",
  "flag Tokelau" -> "🇹🇰",
  "tokelau" -> "🇹🇰",
  "flag_Timor-Leste" -> "🇹🇱",
  "flag-Timor-Leste" -> "🇹🇱",
  "flag Timor-Leste" -> "🇹🇱",
  "timor_leste" -> "🇹🇱",
  "flag_Turkmenistan" -> "🇹🇲",
  "flag-Turkmenistan" -> "🇹🇲",
  "flag Turkmenistan" -> "🇹🇲",
  "turkmenistan" -> "🇹🇲",
  "flag_Tunisia" -> "🇹🇳",
  "flag-Tunisia" -> "🇹🇳",
  "flag Tunisia" -> "🇹🇳",
  "tunisia" -> "🇹🇳",
  "flag_Tonga" -> "🇹🇴",
  "flag-Tonga" -> "🇹🇴",
  "flag Tonga" -> "🇹🇴",
  "tonga" -> "🇹🇴",
  "flag_Turkey" -> "🇹🇷",
  "flag-Turkey" -> "🇹🇷",
  "flag Turkey" -> "🇹🇷",
  "tr" -> "🇹🇷",
  "flag_Trinidad_&_Tobago" -> "🇹🇹",
  "flag-Trinidad-&-Tobago" -> "🇹🇹",
  "flag Trinidad & Tobago" -> "🇹🇹",
  "trinidad_tobago" -> "🇹🇹",
)
