package io.github.edadma.markdown

val emojiBlock19 = List(
  "flag_Tuvalu" -> "🇹🇻",
  "flag-Tuvalu" -> "🇹🇻",
  "flag Tuvalu" -> "🇹🇻",
  "tuvalu" -> "🇹🇻",
  "flag_Taiwan" -> "🇹🇼",
  "flag-Taiwan" -> "🇹🇼",
  "flag Taiwan" -> "🇹🇼",
  "taiwan" -> "🇹🇼",
  "flag_Tanzania" -> "🇹🇿",
  "flag-Tanzania" -> "🇹🇿",
  "flag Tanzania" -> "🇹🇿",
  "tanzania" -> "🇹🇿",
  "flag_Ukraine" -> "🇺🇦",
  "flag-Ukraine" -> "🇺🇦",
  "flag Ukraine" -> "🇺🇦",
  "ukraine" -> "🇺🇦",
  "flag_Uganda" -> "🇺🇬",
  "flag-Uganda" -> "🇺🇬",
  "flag Uganda" -> "🇺🇬",
  "uganda" -> "🇺🇬",
  "flag_U.S._Outlying_Islands" -> "🇺🇲",
  "flag-U.S.-Outlying-Islands" -> "🇺🇲",
  "flag U.S. Outlying Islands" -> "🇺🇲",
  "us_outlying_islands" -> "🇺🇲",
  "flag_United_Nations" -> "🇺🇳",
  "flag-United-Nations" -> "🇺🇳",
  "flag United Nations" -> "🇺🇳",
  "united_nations" -> "🇺🇳",
  "flag_United_States" -> "🇺🇸",
  "flag-United-States" -> "🇺🇸",
  "flag United States" -> "🇺🇸",
  "us" -> "🇺🇸",
  "flag_Uruguay" -> "🇺🇾",
  "flag-Uruguay" -> "🇺🇾",
  "flag Uruguay" -> "🇺🇾",
  "uruguay" -> "🇺🇾",
  "flag_Uzbekistan" -> "🇺🇿",
  "flag-Uzbekistan" -> "🇺🇿",
  "flag Uzbekistan" -> "🇺🇿",
  "uzbekistan" -> "🇺🇿",
  "flag_Vatican_City" -> "🇻🇦",
  "flag-Vatican-City" -> "🇻🇦",
  "flag Vatican City" -> "🇻🇦",
  "vatican_city" -> "🇻🇦",
  "flag_St._Vincent_&_Grenadines" -> "🇻🇨",
  "flag-St.-Vincent-&-Grenadines" -> "🇻🇨",
  "flag St. Vincent & Grenadines" -> "🇻🇨",
  "st_vincent_grenadines" -> "🇻🇨",
  "flag_Venezuela" -> "🇻🇪",
  "flag-Venezuela" -> "🇻🇪",
  "flag Venezuela" -> "🇻🇪",
  "venezuela" -> "🇻🇪",
  "flag_British_Virgin_Islands" -> "🇻🇬",
  "flag-British-Virgin-Islands" -> "🇻🇬",
  "flag British Virgin Islands" -> "🇻🇬",
  "british_virgin_islands" -> "🇻🇬",
  "flag_U.S._Virgin_Islands" -> "🇻🇮",
  "flag-U.S.-Virgin-Islands" -> "🇻🇮",
  "flag U.S. Virgin Islands" -> "🇻🇮",
  "us_virgin_islands" -> "🇻🇮",
  "flag_Vietnam" -> "🇻🇳",
  "flag-Vietnam" -> "🇻🇳",
  "flag Vietnam" -> "🇻🇳",
  "vietnam" -> "🇻🇳",
  "flag_Vanuatu" -> "🇻🇺",
  "flag-Vanuatu" -> "🇻🇺",
  "flag Vanuatu" -> "🇻🇺",
  "vanuatu" -> "🇻🇺",
  "flag_Wallis_&_Futuna" -> "🇼🇫",
  "flag-Wallis-&-Futuna" -> "🇼🇫",
  "flag Wallis & Futuna" -> "🇼🇫",
  "wallis_futuna" -> "🇼🇫",
  "flag_Samoa" -> "🇼🇸",
  "flag-Samoa" -> "🇼🇸",
  "flag Samoa" -> "🇼🇸",
  "samoa" -> "🇼🇸",
  "flag_Kosovo" -> "🇽🇰",
  "flag-Kosovo" -> "🇽🇰",
  "flag Kosovo" -> "🇽🇰",
  "kosovo" -> "🇽🇰",
  "flag_Yemen" -> "🇾🇪",
  "flag-Yemen" -> "🇾🇪",
  "flag Yemen" -> "🇾🇪",
  "yemen" -> "🇾🇪",
  "flag_Mayotte" -> "🇾🇹",
  "flag-Mayotte" -> "🇾🇹",
  "flag Mayotte" -> "🇾🇹",
  "mayotte" -> "🇾🇹",
  "flag_South_Africa" -> "🇿🇦",
  "flag-South-Africa" -> "🇿🇦",
  "flag South Africa" -> "🇿🇦",
  "south_africa" -> "🇿🇦",
  "flag_Zambia" -> "🇿🇲",
  "flag-Zambia" -> "🇿🇲",
  "flag Zambia" -> "🇿🇲",
  "zambia" -> "🇿🇲",
  "flag_Zimbabwe" -> "🇿🇼",
  "flag-Zimbabwe" -> "🇿🇼",
  "flag Zimbabwe" -> "🇿🇼",
  "zimbabwe" -> "🇿🇼",
  "flag_England" -> "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "flag-England" -> "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "flag England" -> "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "england" -> "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "flag_Scotland" -> "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "flag-Scotland" -> "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "flag Scotland" -> "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "scotland" -> "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "flag_Wales" -> "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "flag-Wales" -> "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "flag Wales" -> "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "wales" -> "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
)
