package io.github.edadma.markdown

val emojiBlock12 = List(
  "electric_plug" -> "🔌",
  "electric-plug" -> "🔌",
  "electric plug" -> "🔌",
  "laptop" -> "💻",
  "computer" -> "💻",
  "desktop_computer" -> "🖥️",
  "desktop-computer" -> "🖥️",
  "desktop computer" -> "🖥️",
  "printer" -> "🖨️",
  "keyboard" -> "⌨️",
  "computer_mouse" -> "🖱️",
  "computer-mouse" -> "🖱️",
  "computer mouse" -> "🖱️",
  "trackball" -> "🖲️",
  "computer_disk" -> "💽",
  "computer-disk" -> "💽",
  "computer disk" -> "💽",
  "minidisc" -> "💽",
  "floppy_disk" -> "💾",
  "floppy-disk" -> "💾",
  "floppy disk" -> "💾",
  "optical_disk" -> "💿",
  "optical-disk" -> "💿",
  "optical disk" -> "💿",
  "cd" -> "💿",
  "dvd" -> "📀",
  "abacus" -> "🧮",
  "movie_camera" -> "🎥",
  "movie-camera" -> "🎥",
  "movie camera" -> "🎥",
  "film_frames" -> "🎞️",
  "film-frames" -> "🎞️",
  "film frames" -> "🎞️",
  "film_strip" -> "🎞️",
  "film_projector" -> "📽️",
  "film-projector" -> "📽️",
  "film projector" -> "📽️",
  "clapper_board" -> "🎬",
  "clapper-board" -> "🎬",
  "clapper board" -> "🎬",
  "clapper" -> "🎬",
  "television" -> "📺",
  "tv" -> "📺",
  "camera" -> "📷",
  "camera_with_flash" -> "📸",
  "camera-with-flash" -> "📸",
  "camera with flash" -> "📸",
  "camera_flash" -> "📸",
  "video_camera" -> "📹",
  "video-camera" -> "📹",
  "video camera" -> "📹",
  "videocassette" -> "📼",
  "vhs" -> "📼",
  "magnifying_glass_tilted_left" -> "🔍",
  "magnifying-glass-tilted-left" -> "🔍",
  "magnifying glass tilted left" -> "🔍",
  "mag" -> "🔍",
  "magnifying_glass_tilted_right" -> "🔎",
  "magnifying-glass-tilted-right" -> "🔎",
  "magnifying glass tilted right" -> "🔎",
  "mag_right" -> "🔎",
  "candle" -> "🕯️",
  "light_bulb" -> "💡",
  "light-bulb" -> "💡",
  "light bulb" -> "💡",
  "bulb" -> "💡",
  "flashlight" -> "🔦",
  "red_paper_lantern" -> "🏮",
  "red-paper-lantern" -> "🏮",
  "red paper lantern" -> "🏮",
  "izakaya_lantern" -> "🏮",
  "lantern" -> "🏮",
  "diya_lamp" -> "🪔",
  "diya-lamp" -> "🪔",
  "diya lamp" -> "🪔",
  "notebook_with_decorative_cover" -> "📔",
  "notebook-with-decorative-cover" -> "📔",
  "notebook with decorative cover" -> "📔",
  "closed_book" -> "📕",
  "closed-book" -> "📕",
  "closed book" -> "📕",
  "open_book" -> "📖",
  "open-book" -> "📖",
  "open book" -> "📖",
  "book" -> "📖",
  "green_book" -> "📗",
  "green-book" -> "📗",
  "green book" -> "📗",
  "blue_book" -> "📘",
  "blue-book" -> "📘",
  "blue book" -> "📘",
  "orange_book" -> "📙",
  "orange-book" -> "📙",
  "orange book" -> "📙",
  "books" -> "📚",
  "notebook" -> "📓",
  "ledger" -> "📒",
  "page_with_curl" -> "📃",
  "page-with-curl" -> "📃",
  "page with curl" -> "📃",
  "scroll" -> "📜",
  "page_facing_up" -> "📄",
  "page-facing-up" -> "📄",
  "page facing up" -> "📄",
  "newspaper" -> "📰",
  "rolled-up_newspaper" -> "🗞️",
  "rolled-up-newspaper" -> "🗞️",
  "rolled-up newspaper" -> "🗞️",
  "newspaper_roll" -> "🗞️",
  "bookmark_tabs" -> "📑",
  "bookmark-tabs" -> "📑",
  "bookmark tabs" -> "📑",
  "bookmark" -> "🔖",
  "label" -> "🏷️",
  "money_bag" -> "💰",
  "money-bag" -> "💰",
  "money bag" -> "💰",
  "moneybag" -> "💰",
  "coin" -> "🪙",
  "yen_banknote" -> "💴",
  "yen-banknote" -> "💴",
  "yen banknote" -> "💴",
  "yen" -> "💴",
  "dollar_banknote" -> "💵",
  "dollar-banknote" -> "💵",
  "dollar banknote" -> "💵",
  "dollar" -> "💵",
  "euro_banknote" -> "💶",
  "euro-banknote" -> "💶",
  "euro banknote" -> "💶",
  "euro" -> "💶",
  "pound_banknote" -> "💷",
  "pound-banknote" -> "💷",
  "pound banknote" -> "💷",
  "pound" -> "💷",
  "money_with_wings" -> "💸",
  "money-with-wings" -> "💸",
  "money with wings" -> "💸",
  "credit_card" -> "💳",
  "credit-card" -> "💳",
  "credit card" -> "💳",
  "receipt" -> "🧾",
  "chart_increasing_with_yen" -> "💹",
  "chart-increasing-with-yen" -> "💹",
  "chart increasing with yen" -> "💹",
  "chart" -> "💹",
  "envelope" -> "✉️",
  "e-mail" -> "📧",
  "email" -> "📧",
  "incoming_envelope" -> "📨",
  "incoming-envelope" -> "📨",
  "incoming envelope" -> "📨",
  "envelope_with_arrow" -> "📩",
  "envelope-with-arrow" -> "📩",
  "envelope with arrow" -> "📩",
  "outbox_tray" -> "📤",
  "outbox-tray" -> "📤",
  "outbox tray" -> "📤",
  "inbox_tray" -> "📥",
  "inbox-tray" -> "📥",
  "inbox tray" -> "📥",
  "package" -> "📦",
  "closed_mailbox_with_raised_flag" -> "📫",
  "closed-mailbox-with-raised-flag" -> "📫",
  "closed mailbox with raised flag" -> "📫",
  "mailbox" -> "📫",
  "closed_mailbox_with_lowered_flag" -> "📪",
  "closed-mailbox-with-lowered-flag" -> "📪",
  "closed mailbox with lowered flag" -> "📪",
  "mailbox_closed" -> "📪",
  "open_mailbox_with_raised_flag" -> "📬",
  "open-mailbox-with-raised-flag" -> "📬",
  "open mailbox with raised flag" -> "📬",
  "mailbox_with_mail" -> "📬",
  "open_mailbox_with_lowered_flag" -> "📭",
  "open-mailbox-with-lowered-flag" -> "📭",
  "open mailbox with lowered flag" -> "📭",
  "mailbox_with_no_mail" -> "📭",
  "postbox" -> "📮",
  "ballot_box_with_ballot" -> "🗳️",
  "ballot-box-with-ballot" -> "🗳️",
  "ballot box with ballot" -> "🗳️",
  "ballot_box" -> "🗳️",
  "pencil" -> "✏️",
  "pencil2" -> "✏️",
  "black_nib" -> "✒️",
  "black-nib" -> "✒️",
  "black nib" -> "✒️",
  "fountain_pen" -> "🖋️",
  "fountain-pen" -> "🖋️",
  "fountain pen" -> "🖋️",
  "pen" -> "🖊️",
  "paintbrush" -> "🖌️",
  "crayon" -> "🖍️",
  "memo" -> "📝",
  "pencil" -> "📝",
  "briefcase" -> "💼",
  "file_folder" -> "📁",
  "file-folder" -> "📁",
  "file folder" -> "📁",
  "open_file_folder" -> "📂",
  "open-file-folder" -> "📂",
  "open file folder" -> "📂",
  "card_index_dividers" -> "🗂️",
  "card-index-dividers" -> "🗂️",
  "card index dividers" -> "🗂️",
  "calendar" -> "📅",
  "date" -> "📅",
  "tear-off_calendar" -> "📆",
  "tear-off-calendar" -> "📆",
  "tear-off calendar" -> "📆",
  "calendar" -> "📆",
  "spiral_notepad" -> "🗒️",
  "spiral-notepad" -> "🗒️",
  "spiral notepad" -> "🗒️",
  "spiral_calendar" -> "🗓️",
  "spiral-calendar" -> "🗓️",
  "spiral calendar" -> "🗓️",
  "card_index" -> "📇",
  "card-index" -> "📇",
  "card index" -> "📇",
  "chart_increasing" -> "📈",
  "chart-increasing" -> "📈",
  "chart increasing" -> "📈",
  "chart_with_upwards_trend" -> "📈",
  "chart_decreasing" -> "📉",
  "chart-decreasing" -> "📉",
  "chart decreasing" -> "📉",
  "chart_with_downwards_trend" -> "📉",
  "bar_chart" -> "📊",
  "bar-chart" -> "📊",
  "bar chart" -> "📊",
  "clipboard" -> "📋",
  "pushpin" -> "📌",
  "round_pushpin" -> "📍",
  "round-pushpin" -> "📍",
  "round pushpin" -> "📍",
  "paperclip" -> "📎",
  "linked_paperclips" -> "🖇️",
  "linked-paperclips" -> "🖇️",
  "linked paperclips" -> "🖇️",
  "paperclips" -> "🖇️",
  "straight_ruler" -> "📏",
  "straight-ruler" -> "📏",
  "straight ruler" -> "📏",
  "triangular_ruler" -> "📐",
  "triangular-ruler" -> "📐",
  "triangular ruler" -> "📐",
  "scissors" -> "✂️",
  "card_file_box" -> "🗃️",
  "card-file-box" -> "🗃️",
  "card file box" -> "🗃️",
  "file_cabinet" -> "🗄️",
  "file-cabinet" -> "🗄️",
  "file cabinet" -> "🗄️",
  "wastebasket" -> "🗑️",
  "locked" -> "🔒",
  "lock" -> "🔒",
  "unlocked" -> "🔓",
  "unlock" -> "🔓",
  "locked_with_pen" -> "🔏",
  "locked-with-pen" -> "🔏",
  "locked with pen" -> "🔏",
  "lock_with_ink_pen" -> "🔏",
  "locked_with_key" -> "🔐",
  "locked-with-key" -> "🔐",
  "locked with key" -> "🔐",
  "closed_lock_with_key" -> "🔐",
  "key" -> "🔑",
  "old_key" -> "🗝️",
  "old-key" -> "🗝️",
  "old key" -> "🗝️",
  "hammer" -> "🔨",
  "axe" -> "🪓",
  "pick" -> "⛏️",
  "hammer_and_pick" -> "⚒️",
  "hammer-and-pick" -> "⚒️",
  "hammer and pick" -> "⚒️",
  "hammer_and_wrench" -> "🛠️",
  "hammer-and-wrench" -> "🛠️",
  "hammer and wrench" -> "🛠️",
  "dagger" -> "🗡️",
  "crossed_swords" -> "⚔️",
  "crossed-swords" -> "⚔️",
  "crossed swords" -> "⚔️",
  "bomb" -> "💣",
  "boomerang" -> "🪃",
  "bow_and_arrow" -> "🏹",
  "bow-and-arrow" -> "🏹",
  "bow and arrow" -> "🏹",
  "shield" -> "🛡️",
  "carpentry_saw" -> "🪚",
  "carpentry-saw" -> "🪚",
  "carpentry saw" -> "🪚",
  "wrench" -> "🔧",
  "screwdriver" -> "🪛",
  "nut_and_bolt" -> "🔩",
  "nut-and-bolt" -> "🔩",
  "nut and bolt" -> "🔩",
  "gear" -> "⚙️",
)
