package io.github.edadma.markdown

val emojiBlock16 = List(
  "flag Angola" -> "🇦🇴",
  "angola" -> "🇦🇴",
  "flag_Antarctica" -> "🇦🇶",
  "flag-Antarctica" -> "🇦🇶",
  "flag Antarctica" -> "🇦🇶",
  "antarctica" -> "🇦🇶",
  "flag_Argentina" -> "🇦🇷",
  "flag-Argentina" -> "🇦🇷",
  "flag Argentina" -> "🇦🇷",
  "argentina" -> "🇦🇷",
  "flag_American_Samoa" -> "🇦🇸",
  "flag-American-Samoa" -> "🇦🇸",
  "flag American Samoa" -> "🇦🇸",
  "american_samoa" -> "🇦🇸",
  "flag_Austria" -> "🇦🇹",
  "flag-Austria" -> "🇦🇹",
  "flag Austria" -> "🇦🇹",
  "austria" -> "🇦🇹",
  "flag_Australia" -> "🇦🇺",
  "flag-Australia" -> "🇦🇺",
  "flag Australia" -> "🇦🇺",
  "australia" -> "🇦🇺",
  "flag_Aruba" -> "🇦🇼",
  "flag-Aruba" -> "🇦🇼",
  "flag Aruba" -> "🇦🇼",
  "aruba" -> "🇦🇼",
  "flag_Åland_Islands" -> "🇦🇽",
  "flag-Åland-Islands" -> "🇦🇽",
  "flag Åland Islands" -> "🇦🇽",
  "aland_islands" -> "🇦🇽",
  "flag_Azerbaijan" -> "🇦🇿",
  "flag-Azerbaijan" -> "🇦🇿",
  "flag Azerbaijan" -> "🇦🇿",
  "azerbaijan" -> "🇦🇿",
  "flag_Bosnia_&_Herzegovina" -> "🇧🇦",
  "flag-Bosnia-&-Herzegovina" -> "🇧🇦",
  "flag Bosnia & Herzegovina" -> "🇧🇦",
  "bosnia_herzegovina" -> "🇧🇦",
  "flag_Barbados" -> "🇧🇧",
  "flag-Barbados" -> "🇧🇧",
  "flag Barbados" -> "🇧🇧",
  "barbados" -> "🇧🇧",
  "flag_Bangladesh" -> "🇧🇩",
  "flag-Bangladesh" -> "🇧🇩",
  "flag Bangladesh" -> "🇧🇩",
  "bangladesh" -> "🇧🇩",
  "flag_Belgium" -> "🇧🇪",
  "flag-Belgium" -> "🇧🇪",
  "flag Belgium" -> "🇧🇪",
  "belgium" -> "🇧🇪",
  "flag_Burkina_Faso" -> "🇧🇫",
  "flag-Burkina-Faso" -> "🇧🇫",
  "flag Burkina Faso" -> "🇧🇫",
  "burkina_faso" -> "🇧🇫",
  "flag_Bulgaria" -> "🇧🇬",
  "flag-Bulgaria" -> "🇧🇬",
  "flag Bulgaria" -> "🇧🇬",
  "bulgaria" -> "🇧🇬",
  "flag_Bahrain" -> "🇧🇭",
  "flag-Bahrain" -> "🇧🇭",
  "flag Bahrain" -> "🇧🇭",
  "bahrain" -> "🇧🇭",
  "flag_Burundi" -> "🇧🇮",
  "flag-Burundi" -> "🇧🇮",
  "flag Burundi" -> "🇧🇮",
  "burundi" -> "🇧🇮",
  "flag_Benin" -> "🇧🇯",
  "flag-Benin" -> "🇧🇯",
  "flag Benin" -> "🇧🇯",
  "benin" -> "🇧🇯",
  "flag_St._Barthélemy" -> "🇧🇱",
  "flag-St.-Barthélemy" -> "🇧🇱",
  "flag St. Barthélemy" -> "🇧🇱",
  "st_barthelemy" -> "🇧🇱",
  "flag_Bermuda" -> "🇧🇲",
  "flag-Bermuda" -> "🇧🇲",
  "flag Bermuda" -> "🇧🇲",
  "bermuda" -> "🇧🇲",
  "flag_Brunei" -> "🇧🇳",
  "flag-Brunei" -> "🇧🇳",
  "flag Brunei" -> "🇧🇳",
  "brunei" -> "🇧🇳",
  "flag_Bolivia" -> "🇧🇴",
  "flag-Bolivia" -> "🇧🇴",
  "flag Bolivia" -> "🇧🇴",
  "bolivia" -> "🇧🇴",
  "flag_Caribbean_Netherlands" -> "🇧🇶",
  "flag-Caribbean-Netherlands" -> "🇧🇶",
  "flag Caribbean Netherlands" -> "🇧🇶",
  "caribbean_netherlands" -> "🇧🇶",
  "flag_Brazil" -> "🇧🇷",
  "flag-Brazil" -> "🇧🇷",
  "flag Brazil" -> "🇧🇷",
  "brazil" -> "🇧🇷",
  "flag_Bahamas" -> "🇧🇸",
  "flag-Bahamas" -> "🇧🇸",
  "flag Bahamas" -> "🇧🇸",
  "bahamas" -> "🇧🇸",
  "flag_Bhutan" -> "🇧🇹",
  "flag-Bhutan" -> "🇧🇹",
  "flag Bhutan" -> "🇧🇹",
  "bhutan" -> "🇧🇹",
  "flag_Bouvet_Island" -> "🇧🇻",
  "flag-Bouvet-Island" -> "🇧🇻",
  "flag Bouvet Island" -> "🇧🇻",
  "bouvet_island" -> "🇧🇻",
  "flag_Botswana" -> "🇧🇼",
  "flag-Botswana" -> "🇧🇼",
  "flag Botswana" -> "🇧🇼",
  "botswana" -> "🇧🇼",
  "flag_Belarus" -> "🇧🇾",
  "flag-Belarus" -> "🇧🇾",
  "flag Belarus" -> "🇧🇾",
  "belarus" -> "🇧🇾",
  "flag_Belize" -> "🇧🇿",
  "flag-Belize" -> "🇧🇿",
  "flag Belize" -> "🇧🇿",
  "belize" -> "🇧🇿",
  "flag_Canada" -> "🇨🇦",
  "flag-Canada" -> "🇨🇦",
  "flag Canada" -> "🇨🇦",
  "canada" -> "🇨🇦",
  "flag_Cocos_(Keeling)_Islands" -> "🇨🇨",
  "flag-Cocos-(Keeling)-Islands" -> "🇨🇨",
  "flag Cocos (Keeling) Islands" -> "🇨🇨",
  "cocos_islands" -> "🇨🇨",
  "flag_Congo_-_Kinshasa" -> "🇨🇩",
  "flag-Congo---Kinshasa" -> "🇨🇩",
  "flag Congo - Kinshasa" -> "🇨🇩",
  "congo_kinshasa" -> "🇨🇩",
  "flag_Central_African_Republic" -> "🇨🇫",
  "flag-Central-African-Republic" -> "🇨🇫",
  "flag Central African Republic" -> "🇨🇫",
  "central_african_republic" -> "🇨🇫",
  "flag_Congo_-_Brazzaville" -> "🇨🇬",
  "flag-Congo---Brazzaville" -> "🇨🇬",
  "flag Congo - Brazzaville" -> "🇨🇬",
  "congo_brazzaville" -> "🇨🇬",
  "flag_Switzerland" -> "🇨🇭",
  "flag-Switzerland" -> "🇨🇭",
  "flag Switzerland" -> "🇨🇭",
  "switzerland" -> "🇨🇭",
  "flag_Côte_d’Ivoire" -> "🇨🇮",
  "flag-Côte-d’Ivoire" -> "🇨🇮",
  "flag Côte d’Ivoire" -> "🇨🇮",
  "cote_divoire" -> "🇨🇮",
  "flag_Cook_Islands" -> "🇨🇰",
  "flag-Cook-Islands" -> "🇨🇰",
  "flag Cook Islands" -> "🇨🇰",
  "cook_islands" -> "🇨🇰",
  "flag_Chile" -> "🇨🇱",
  "flag-Chile" -> "🇨🇱",
  "flag Chile" -> "🇨🇱",
  "chile" -> "🇨🇱",
  "flag_Cameroon" -> "🇨🇲",
  "flag-Cameroon" -> "🇨🇲",
  "flag Cameroon" -> "🇨🇲",
  "cameroon" -> "🇨🇲",
  "flag_China" -> "🇨🇳",
  "flag-China" -> "🇨🇳",
  "flag China" -> "🇨🇳",
  "cn" -> "🇨🇳",
  "flag_Colombia" -> "🇨🇴",
  "flag-Colombia" -> "🇨🇴",
  "flag Colombia" -> "🇨🇴",
  "colombia" -> "🇨🇴",
  "flag_Clipperton_Island" -> "🇨🇵",
  "flag-Clipperton-Island" -> "🇨🇵",
  "flag Clipperton Island" -> "🇨🇵",
  "clipperton_island" -> "🇨🇵",
  "flag_Costa_Rica" -> "🇨🇷",
  "flag-Costa-Rica" -> "🇨🇷",
  "flag Costa Rica" -> "🇨🇷",
  "costa_rica" -> "🇨🇷",
  "flag_Cuba" -> "🇨🇺",
  "flag-Cuba" -> "🇨🇺",
  "flag Cuba" -> "🇨🇺",
  "cuba" -> "🇨🇺",
  "flag_Cape_Verde" -> "🇨🇻",
  "flag-Cape-Verde" -> "🇨🇻",
  "flag Cape Verde" -> "🇨🇻",
  "cape_verde" -> "🇨🇻",
  "flag_Curaçao" -> "🇨🇼",
  "flag-Curaçao" -> "🇨🇼",
  "flag Curaçao" -> "🇨🇼",
  "curacao" -> "🇨🇼",
  "flag_Christmas_Island" -> "🇨🇽",
  "flag-Christmas-Island" -> "🇨🇽",
  "flag Christmas Island" -> "🇨🇽",
  "christmas_island" -> "🇨🇽",
  "flag_Cyprus" -> "🇨🇾",
  "flag-Cyprus" -> "🇨🇾",
  "flag Cyprus" -> "🇨🇾",
  "cyprus" -> "🇨🇾",
  "flag_Czechia" -> "🇨🇿",
  "flag-Czechia" -> "🇨🇿",
  "flag Czechia" -> "🇨🇿",
  "czech_republic" -> "🇨🇿",
  "flag_Germany" -> "🇩🇪",
  "flag-Germany" -> "🇩🇪",
  "flag Germany" -> "🇩🇪",
  "de" -> "🇩🇪",
  "flag_Diego_Garcia" -> "🇩🇬",
  "flag-Diego-Garcia" -> "🇩🇬",
  "flag Diego Garcia" -> "🇩🇬",
  "diego_garcia" -> "🇩🇬",
  "flag_Djibouti" -> "🇩🇯",
  "flag-Djibouti" -> "🇩🇯",
  "flag Djibouti" -> "🇩🇯",
  "djibouti" -> "🇩🇯",
  "flag_Denmark" -> "🇩🇰",
  "flag-Denmark" -> "🇩🇰",
  "flag Denmark" -> "🇩🇰",
  "denmark" -> "🇩🇰",
  "flag_Dominica" -> "🇩🇲",
  "flag-Dominica" -> "🇩🇲",
  "flag Dominica" -> "🇩🇲",
  "dominica" -> "🇩🇲",
  "flag_Dominican_Republic" -> "🇩🇴",
  "flag-Dominican-Republic" -> "🇩🇴",
  "flag Dominican Republic" -> "🇩🇴",
  "dominican_republic" -> "🇩🇴",
  "flag_Algeria" -> "🇩🇿",
  "flag-Algeria" -> "🇩🇿",
  "flag Algeria" -> "🇩🇿",
  "algeria" -> "🇩🇿",
  "flag_Ceuta_&_Melilla" -> "🇪🇦",
  "flag-Ceuta-&-Melilla" -> "🇪🇦",
  "flag Ceuta & Melilla" -> "🇪🇦",
  "ceuta_melilla" -> "🇪🇦",
  "flag_Ecuador" -> "🇪🇨",
  "flag-Ecuador" -> "🇪🇨",
  "flag Ecuador" -> "🇪🇨",
  "ecuador" -> "🇪🇨",
  "flag_Estonia" -> "🇪🇪",
  "flag-Estonia" -> "🇪🇪",
  "flag Estonia" -> "🇪🇪",
  "estonia" -> "🇪🇪",
  "flag_Egypt" -> "🇪🇬",
  "flag-Egypt" -> "🇪🇬",
  "flag Egypt" -> "🇪🇬",
  "egypt" -> "🇪🇬",
  "flag_Western_Sahara" -> "🇪🇭",
  "flag-Western-Sahara" -> "🇪🇭",
  "flag Western Sahara" -> "🇪🇭",
  "western_sahara" -> "🇪🇭",
  "flag_Eritrea" -> "🇪🇷",
  "flag-Eritrea" -> "🇪🇷",
  "flag Eritrea" -> "🇪🇷",
  "eritrea" -> "🇪🇷",
  "flag_Spain" -> "🇪🇸",
  "flag-Spain" -> "🇪🇸",
  "flag Spain" -> "🇪🇸",
  "es" -> "🇪🇸",
  "flag_Ethiopia" -> "🇪🇹",
  "flag-Ethiopia" -> "🇪🇹",
  "flag Ethiopia" -> "🇪🇹",
  "ethiopia" -> "🇪🇹",
  "flag_European_Union" -> "🇪🇺",
  "flag-European-Union" -> "🇪🇺",
  "flag European Union" -> "🇪🇺",
  "eu" -> "🇪🇺",
  "european_union" -> "🇪🇺",
  "flag_Finland" -> "🇫🇮",
  "flag-Finland" -> "🇫🇮",
  "flag Finland" -> "🇫🇮",
  "finland" -> "🇫🇮",
  "flag_Fiji" -> "🇫🇯",
  "flag-Fiji" -> "🇫🇯",
  "flag Fiji" -> "🇫🇯",
  "fiji" -> "🇫🇯",
  "flag_Falkland_Islands" -> "🇫🇰",
  "flag-Falkland-Islands" -> "🇫🇰",
  "flag Falkland Islands" -> "🇫🇰",
  "falkland_islands" -> "🇫🇰",
  "flag_Micronesia" -> "🇫🇲",
  "flag-Micronesia" -> "🇫🇲",
  "flag Micronesia" -> "🇫🇲",
  "micronesia" -> "🇫🇲",
  "flag_Faroe_Islands" -> "🇫🇴",
  "flag-Faroe-Islands" -> "🇫🇴",
  "flag Faroe Islands" -> "🇫🇴",
  "faroe_islands" -> "🇫🇴",
  "flag_France" -> "🇫🇷",
  "flag-France" -> "🇫🇷",
  "flag France" -> "🇫🇷",
  "fr" -> "🇫🇷",
  "flag_Gabon" -> "🇬🇦",
  "flag-Gabon" -> "🇬🇦",
  "flag Gabon" -> "🇬🇦",
  "gabon" -> "🇬🇦",
  "flag_United_Kingdom" -> "🇬🇧",
  "flag-United-Kingdom" -> "🇬🇧",
  "flag United Kingdom" -> "🇬🇧",
  "gb" -> "🇬🇧",
  "uk" -> "🇬🇧",
  "flag_Grenada" -> "🇬🇩",
  "flag-Grenada" -> "🇬🇩",
  "flag Grenada" -> "🇬🇩",
  "grenada" -> "🇬🇩",
)
