package io.github.edadma.markdown

val emojiBlock11 = List(
  "running_shirt_with_sash" -> "🎽",
  "skis" -> "🎿",
  "ski" -> "🎿",
  "sled" -> "🛷",
  "curling_stone" -> "🥌",
  "curling-stone" -> "🥌",
  "curling stone" -> "🥌",
  "bullseye" -> "🎯",
  "dart" -> "🎯",
  "yo-yo" -> "🪀",
  "yo_yo" -> "🪀",
  "kite" -> "🪁",
  "water_pistol" -> "🔫",
  "water-pistol" -> "🔫",
  "water pistol" -> "🔫",
  "gun" -> "🔫",
  "pool_8_ball" -> "🎱",
  "pool-8-ball" -> "🎱",
  "pool 8 ball" -> "🎱",
  "8ball" -> "🎱",
  "crystal_ball" -> "🔮",
  "crystal-ball" -> "🔮",
  "crystal ball" -> "🔮",
  "magic_wand" -> "🪄",
  "magic-wand" -> "🪄",
  "magic wand" -> "🪄",
  "video_game" -> "🎮",
  "video-game" -> "🎮",
  "video game" -> "🎮",
  "joystick" -> "🕹️",
  "slot_machine" -> "🎰",
  "slot-machine" -> "🎰",
  "slot machine" -> "🎰",
  "game_die" -> "🎲",
  "game-die" -> "🎲",
  "game die" -> "🎲",
  "puzzle_piece" -> "🧩",
  "puzzle-piece" -> "🧩",
  "puzzle piece" -> "🧩",
  "jigsaw" -> "🧩",
  "teddy_bear" -> "🧸",
  "teddy-bear" -> "🧸",
  "teddy bear" -> "🧸",
  "piñata" -> "🪅",
  "pinata" -> "🪅",
  "mirror_ball" -> "🪩",
  "mirror-ball" -> "🪩",
  "mirror ball" -> "🪩",
  "nesting_dolls" -> "🪆",
  "nesting-dolls" -> "🪆",
  "nesting dolls" -> "🪆",
  "spade_suit" -> "♠️",
  "spade-suit" -> "♠️",
  "spade suit" -> "♠️",
  "spades" -> "♠️",
  "heart_suit" -> "♥️",
  "heart-suit" -> "♥️",
  "heart suit" -> "♥️",
  "hearts" -> "♥️",
  "diamond_suit" -> "♦️",
  "diamond-suit" -> "♦️",
  "diamond suit" -> "♦️",
  "diamonds" -> "♦️",
  "club_suit" -> "♣️",
  "club-suit" -> "♣️",
  "club suit" -> "♣️",
  "clubs" -> "♣️",
  "chess_pawn" -> "♟️",
  "chess-pawn" -> "♟️",
  "chess pawn" -> "♟️",
  "joker" -> "🃏",
  "black_joker" -> "🃏",
  "mahjong_red_dragon" -> "🀄",
  "mahjong-red-dragon" -> "🀄",
  "mahjong red dragon" -> "🀄",
  "mahjong" -> "🀄",
  "flower_playing_cards" -> "🎴",
  "flower-playing-cards" -> "🎴",
  "flower playing cards" -> "🎴",
  "performing_arts" -> "🎭",
  "performing-arts" -> "🎭",
  "performing arts" -> "🎭",
  "framed_picture" -> "🖼️",
  "framed-picture" -> "🖼️",
  "framed picture" -> "🖼️",
  "artist_palette" -> "🎨",
  "artist-palette" -> "🎨",
  "artist palette" -> "🎨",
  "art" -> "🎨",
  "thread" -> "🧵",
  "sewing_needle" -> "🪡",
  "sewing-needle" -> "🪡",
  "sewing needle" -> "🪡",
  "yarn" -> "🧶",
  "knot" -> "🪢",
  "glasses" -> "👓",
  "eyeglasses" -> "👓",
  "sunglasses" -> "🕶️",
  "dark_sunglasses" -> "🕶️",
  "goggles" -> "🥽",
  "lab_coat" -> "🥼",
  "lab-coat" -> "🥼",
  "lab coat" -> "🥼",
  "safety_vest" -> "🦺",
  "safety-vest" -> "🦺",
  "safety vest" -> "🦺",
  "necktie" -> "👔",
  "t-shirt" -> "👕",
  "shirt" -> "👕",
  "tshirt" -> "👕",
  "jeans" -> "👖",
  "scarf" -> "🧣",
  "gloves" -> "🧤",
  "coat" -> "🧥",
  "socks" -> "🧦",
  "dress" -> "👗",
  "kimono" -> "👘",
  "sari" -> "🥻",
  "one-piece_swimsuit" -> "🩱",
  "one-piece-swimsuit" -> "🩱",
  "one-piece swimsuit" -> "🩱",
  "one_piece_swimsuit" -> "🩱",
  "briefs" -> "🩲",
  "swim_brief" -> "🩲",
  "shorts" -> "🩳",
  "bikini" -> "👙",
  "woman’s_clothes" -> "👚",
  "woman’s-clothes" -> "👚",
  "woman’s clothes" -> "👚",
  "womans_clothes" -> "👚",
  "folding_hand_fan" -> "🪭",
  "folding-hand-fan" -> "🪭",
  "folding hand fan" -> "🪭",
  "purse" -> "👛",
  "handbag" -> "👜",
  "clutch_bag" -> "👝",
  "clutch-bag" -> "👝",
  "clutch bag" -> "👝",
  "pouch" -> "👝",
  "shopping_bags" -> "🛍️",
  "shopping-bags" -> "🛍️",
  "shopping bags" -> "🛍️",
  "shopping" -> "🛍️",
  "backpack" -> "🎒",
  "school_satchel" -> "🎒",
  "thong_sandal" -> "🩴",
  "thong-sandal" -> "🩴",
  "thong sandal" -> "🩴",
  "man’s_shoe" -> "👞",
  "man’s-shoe" -> "👞",
  "man’s shoe" -> "👞",
  "mans_shoe" -> "👞",
  "shoe" -> "👞",
  "running_shoe" -> "👟",
  "running-shoe" -> "👟",
  "running shoe" -> "👟",
  "athletic_shoe" -> "👟",
  "hiking_boot" -> "🥾",
  "hiking-boot" -> "🥾",
  "hiking boot" -> "🥾",
  "flat_shoe" -> "🥿",
  "flat-shoe" -> "🥿",
  "flat shoe" -> "🥿",
  "high-heeled_shoe" -> "👠",
  "high-heeled-shoe" -> "👠",
  "high-heeled shoe" -> "👠",
  "high_heel" -> "👠",
  "woman’s_sandal" -> "👡",
  "woman’s-sandal" -> "👡",
  "woman’s sandal" -> "👡",
  "sandal" -> "👡",
  "ballet_shoes" -> "🩰",
  "ballet-shoes" -> "🩰",
  "ballet shoes" -> "🩰",
  "woman’s_boot" -> "👢",
  "woman’s-boot" -> "👢",
  "woman’s boot" -> "👢",
  "boot" -> "👢",
  "hair_pick" -> "🪮",
  "hair-pick" -> "🪮",
  "hair pick" -> "🪮",
  "crown" -> "👑",
  "woman’s_hat" -> "👒",
  "woman’s-hat" -> "👒",
  "woman’s hat" -> "👒",
  "womans_hat" -> "👒",
  "top_hat" -> "🎩",
  "top-hat" -> "🎩",
  "top hat" -> "🎩",
  "tophat" -> "🎩",
  "graduation_cap" -> "🎓",
  "graduation-cap" -> "🎓",
  "graduation cap" -> "🎓",
  "mortar_board" -> "🎓",
  "billed_cap" -> "🧢",
  "billed-cap" -> "🧢",
  "billed cap" -> "🧢",
  "military_helmet" -> "🪖",
  "military-helmet" -> "🪖",
  "military helmet" -> "🪖",
  "rescue_worker’s_helmet" -> "⛑️",
  "rescue-worker’s-helmet" -> "⛑️",
  "rescue worker’s helmet" -> "⛑️",
  "rescue_worker_helmet" -> "⛑️",
  "prayer_beads" -> "📿",
  "prayer-beads" -> "📿",
  "prayer beads" -> "📿",
  "lipstick" -> "💄",
  "ring" -> "💍",
  "gem_stone" -> "💎",
  "gem-stone" -> "💎",
  "gem stone" -> "💎",
  "gem" -> "💎",
  "muted_speaker" -> "🔇",
  "muted-speaker" -> "🔇",
  "muted speaker" -> "🔇",
  "mute" -> "🔇",
  "speaker_low_volume" -> "🔈",
  "speaker-low-volume" -> "🔈",
  "speaker low volume" -> "🔈",
  "speaker" -> "🔈",
  "speaker_medium_volume" -> "🔉",
  "speaker-medium-volume" -> "🔉",
  "speaker medium volume" -> "🔉",
  "sound" -> "🔉",
  "speaker_high_volume" -> "🔊",
  "speaker-high-volume" -> "🔊",
  "speaker high volume" -> "🔊",
  "loud_sound" -> "🔊",
  "loudspeaker" -> "📢",
  "megaphone" -> "📣",
  "mega" -> "📣",
  "postal_horn" -> "📯",
  "postal-horn" -> "📯",
  "postal horn" -> "📯",
  "bell" -> "🔔",
  "bell_with_slash" -> "🔕",
  "bell-with-slash" -> "🔕",
  "bell with slash" -> "🔕",
  "no_bell" -> "🔕",
  "musical_score" -> "🎼",
  "musical-score" -> "🎼",
  "musical score" -> "🎼",
  "musical_note" -> "🎵",
  "musical-note" -> "🎵",
  "musical note" -> "🎵",
  "musical_notes" -> "🎶",
  "musical-notes" -> "🎶",
  "musical notes" -> "🎶",
  "notes" -> "🎶",
  "studio_microphone" -> "🎙️",
  "studio-microphone" -> "🎙️",
  "studio microphone" -> "🎙️",
  "level_slider" -> "🎚️",
  "level-slider" -> "🎚️",
  "level slider" -> "🎚️",
  "control_knobs" -> "🎛️",
  "control-knobs" -> "🎛️",
  "control knobs" -> "🎛️",
  "microphone" -> "🎤",
  "headphone" -> "🎧",
  "headphones" -> "🎧",
  "radio" -> "📻",
  "saxophone" -> "🎷",
  "accordion" -> "🪗",
  "guitar" -> "🎸",
  "musical_keyboard" -> "🎹",
  "musical-keyboard" -> "🎹",
  "musical keyboard" -> "🎹",
  "trumpet" -> "🎺",
  "violin" -> "🎻",
  "banjo" -> "🪕",
  "drum" -> "🥁",
  "long_drum" -> "🪘",
  "long-drum" -> "🪘",
  "long drum" -> "🪘",
  "maracas" -> "🪇",
  "flute" -> "🪈",
  "mobile_phone" -> "📱",
  "mobile-phone" -> "📱",
  "mobile phone" -> "📱",
  "iphone" -> "📱",
  "mobile_phone_with_arrow" -> "📲",
  "mobile-phone-with-arrow" -> "📲",
  "mobile phone with arrow" -> "📲",
  "calling" -> "📲",
  "telephone" -> "☎️",
  "phone" -> "☎️",
  "telephone_receiver" -> "📞",
  "telephone-receiver" -> "📞",
  "telephone receiver" -> "📞",
  "pager" -> "📟",
  "fax_machine" -> "📠",
  "fax-machine" -> "📠",
  "fax machine" -> "📠",
  "fax" -> "📠",
  "battery" -> "🔋",
  "low_battery" -> "🪫",
  "low-battery" -> "🪫",
  "low battery" -> "🪫",
)
