package io.github.edadma.markdown

val emojiBlock14 = List(
  "Virgo" -> "♍",
  "virgo" -> "♍",
  "Libra" -> "♎",
  "libra" -> "♎",
  "Scorpio" -> "♏",
  "scorpius" -> "♏",
  "Sagittarius" -> "♐",
  "sagittarius" -> "♐",
  "Capricorn" -> "♑",
  "capricorn" -> "♑",
  "Aquarius" -> "♒",
  "aquarius" -> "♒",
  "Pisces" -> "♓",
  "pisces" -> "♓",
  "Ophiuchus" -> "⛎",
  "ophiuchus" -> "⛎",
  "shuffle_tracks_button" -> "🔀",
  "shuffle-tracks-button" -> "🔀",
  "shuffle tracks button" -> "🔀",
  "twisted_rightwards_arrows" -> "🔀",
  "repeat_button" -> "🔁",
  "repeat-button" -> "🔁",
  "repeat button" -> "🔁",
  "repeat" -> "🔁",
  "repeat_single_button" -> "🔂",
  "repeat-single-button" -> "🔂",
  "repeat single button" -> "🔂",
  "repeat_one" -> "🔂",
  "play_button" -> "▶️",
  "play-button" -> "▶️",
  "play button" -> "▶️",
  "arrow_forward" -> "▶️",
  "fast-forward_button" -> "⏩",
  "fast-forward-button" -> "⏩",
  "fast-forward button" -> "⏩",
  "fast_forward" -> "⏩",
  "next_track_button" -> "⏭️",
  "next-track-button" -> "⏭️",
  "next track button" -> "⏭️",
  "play_or_pause_button" -> "⏯️",
  "play-or-pause-button" -> "⏯️",
  "play or pause button" -> "⏯️",
  "reverse_button" -> "◀️",
  "reverse-button" -> "◀️",
  "reverse button" -> "◀️",
  "arrow_backward" -> "◀️",
  "fast_reverse_button" -> "⏪",
  "fast-reverse-button" -> "⏪",
  "fast reverse button" -> "⏪",
  "rewind" -> "⏪",
  "last_track_button" -> "⏮️",
  "last-track-button" -> "⏮️",
  "last track button" -> "⏮️",
  "previous_track_button" -> "⏮️",
  "upwards_button" -> "🔼",
  "upwards-button" -> "🔼",
  "upwards button" -> "🔼",
  "arrow_up_small" -> "🔼",
  "fast_up_button" -> "⏫",
  "fast-up-button" -> "⏫",
  "fast up button" -> "⏫",
  "arrow_double_up" -> "⏫",
  "downwards_button" -> "🔽",
  "downwards-button" -> "🔽",
  "downwards button" -> "🔽",
  "arrow_down_small" -> "🔽",
  "fast_down_button" -> "⏬",
  "fast-down-button" -> "⏬",
  "fast down button" -> "⏬",
  "arrow_double_down" -> "⏬",
  "pause_button" -> "⏸️",
  "pause-button" -> "⏸️",
  "pause button" -> "⏸️",
  "stop_button" -> "⏹️",
  "stop-button" -> "⏹️",
  "stop button" -> "⏹️",
  "record_button" -> "⏺️",
  "record-button" -> "⏺️",
  "record button" -> "⏺️",
  "eject_button" -> "⏏️",
  "eject-button" -> "⏏️",
  "eject button" -> "⏏️",
  "cinema" -> "🎦",
  "dim_button" -> "🔅",
  "dim-button" -> "🔅",
  "dim button" -> "🔅",
  "low_brightness" -> "🔅",
  "bright_button" -> "🔆",
  "bright-button" -> "🔆",
  "bright button" -> "🔆",
  "high_brightness" -> "🔆",
  "antenna_bars" -> "📶",
  "antenna-bars" -> "📶",
  "antenna bars" -> "📶",
  "signal_strength" -> "📶",
  "wireless" -> "🛜",
  "vibration_mode" -> "📳",
  "vibration-mode" -> "📳",
  "vibration mode" -> "📳",
  "mobile_phone_off" -> "📴",
  "mobile-phone-off" -> "📴",
  "mobile phone off" -> "📴",
  "female_sign" -> "♀️",
  "female-sign" -> "♀️",
  "female sign" -> "♀️",
  "male_sign" -> "♂️",
  "male-sign" -> "♂️",
  "male sign" -> "♂️",
  "transgender_symbol" -> "⚧️",
  "transgender-symbol" -> "⚧️",
  "transgender symbol" -> "⚧️",
  "multiply" -> "✖️",
  "heavy_multiplication_x" -> "✖️",
  "plus" -> "➕",
  "heavy_plus_sign" -> "➕",
  "minus" -> "➖",
  "heavy_minus_sign" -> "➖",
  "divide" -> "➗",
  "heavy_division_sign" -> "➗",
  "heavy_equals_sign" -> "🟰",
  "heavy-equals-sign" -> "🟰",
  "heavy equals sign" -> "🟰",
  "infinity" -> "♾️",
  "double_exclamation_mark" -> "‼️",
  "double-exclamation-mark" -> "‼️",
  "double exclamation mark" -> "‼️",
  "bangbang" -> "‼️",
  "exclamation_question_mark" -> "⁉️",
  "exclamation-question-mark" -> "⁉️",
  "exclamation question mark" -> "⁉️",
  "interrobang" -> "⁉️",
  "red_question_mark" -> "❓",
  "red-question-mark" -> "❓",
  "red question mark" -> "❓",
  "question" -> "❓",
  "white_question_mark" -> "❔",
  "white-question-mark" -> "❔",
  "white question mark" -> "❔",
  "grey_question" -> "❔",
  "white_exclamation_mark" -> "❕",
  "white-exclamation-mark" -> "❕",
  "white exclamation mark" -> "❕",
  "grey_exclamation" -> "❕",
  "red_exclamation_mark" -> "❗",
  "red-exclamation-mark" -> "❗",
  "red exclamation mark" -> "❗",
  "exclamation" -> "❗",
  "heavy_exclamation_mark" -> "❗",
  "wavy_dash" -> "〰️",
  "wavy-dash" -> "〰️",
  "wavy dash" -> "〰️",
  "currency_exchange" -> "💱",
  "currency-exchange" -> "💱",
  "currency exchange" -> "💱",
  "heavy_dollar_sign" -> "💲",
  "heavy-dollar-sign" -> "💲",
  "heavy dollar sign" -> "💲",
  "medical_symbol" -> "⚕️",
  "medical-symbol" -> "⚕️",
  "medical symbol" -> "⚕️",
  "recycling_symbol" -> "♻️",
  "recycling-symbol" -> "♻️",
  "recycling symbol" -> "♻️",
  "recycle" -> "♻️",
  "fleur-de-lis" -> "⚜️",
  "fleur_de_lis" -> "⚜️",
  "trident_emblem" -> "🔱",
  "trident-emblem" -> "🔱",
  "trident emblem" -> "🔱",
  "trident" -> "🔱",
  "name_badge" -> "📛",
  "name-badge" -> "📛",
  "name badge" -> "📛",
  "Japanese_symbol_for_beginner" -> "🔰",
  "Japanese-symbol-for-beginner" -> "🔰",
  "Japanese symbol for beginner" -> "🔰",
  "beginner" -> "🔰",
  "hollow_red_circle" -> "⭕",
  "hollow-red-circle" -> "⭕",
  "hollow red circle" -> "⭕",
  "o" -> "⭕",
  "check_mark_button" -> "✅",
  "check-mark-button" -> "✅",
  "check mark button" -> "✅",
  "white_check_mark" -> "✅",
  "check_box_with_check" -> "☑️",
  "check-box-with-check" -> "☑️",
  "check box with check" -> "☑️",
  "ballot_box_with_check" -> "☑️",
  "check_mark" -> "✔️",
  "check-mark" -> "✔️",
  "check mark" -> "✔️",
  "heavy_check_mark" -> "✔️",
  "cross_mark" -> "❌",
  "cross-mark" -> "❌",
  "cross mark" -> "❌",
  "x" -> "❌",
  "cross_mark_button" -> "❎",
  "cross-mark-button" -> "❎",
  "cross mark button" -> "❎",
  "negative_squared_cross_mark" -> "❎",
  "curly_loop" -> "➰",
  "curly-loop" -> "➰",
  "curly loop" -> "➰",
  "double_curly_loop" -> "➿",
  "double-curly-loop" -> "➿",
  "double curly loop" -> "➿",
  "loop" -> "➿",
  "part_alternation_mark" -> "〽️",
  "part-alternation-mark" -> "〽️",
  "part alternation mark" -> "〽️",
  "eight-spoked_asterisk" -> "✳️",
  "eight-spoked-asterisk" -> "✳️",
  "eight-spoked asterisk" -> "✳️",
  "eight_spoked_asterisk" -> "✳️",
  "eight-pointed_star" -> "✴️",
  "eight-pointed-star" -> "✴️",
  "eight-pointed star" -> "✴️",
  "eight_pointed_black_star" -> "✴️",
  "sparkle" -> "❇️",
  "copyright" -> "©️",
  "registered" -> "®️",
  "trade_mark" -> "™️",
  "trade-mark" -> "™️",
  "trade mark" -> "™️",
  "tm" -> "™️",
  "keycap_#" -> "#️⃣",
  "keycap-#" -> "#️⃣",
  "keycap #" -> "#️⃣",
  "hash" -> "#️⃣",
  "keycap_*" -> "*️⃣",
  "keycap-*" -> "*️⃣",
  "keycap *" -> "*️⃣",
  "asterisk" -> "*️⃣",
  "keycap_0" -> "0️⃣",
  "keycap-0" -> "0️⃣",
  "keycap 0" -> "0️⃣",
  "zero" -> "0️⃣",
  "keycap_1" -> "1️⃣",
  "keycap-1" -> "1️⃣",
  "keycap 1" -> "1️⃣",
  "one" -> "1️⃣",
  "keycap_2" -> "2️⃣",
  "keycap-2" -> "2️⃣",
  "keycap 2" -> "2️⃣",
  "two" -> "2️⃣",
  "keycap_3" -> "3️⃣",
  "keycap-3" -> "3️⃣",
  "keycap 3" -> "3️⃣",
  "three" -> "3️⃣",
  "keycap_4" -> "4️⃣",
  "keycap-4" -> "4️⃣",
  "keycap 4" -> "4️⃣",
  "four" -> "4️⃣",
  "keycap_5" -> "5️⃣",
  "keycap-5" -> "5️⃣",
  "keycap 5" -> "5️⃣",
  "five" -> "5️⃣",
  "keycap_6" -> "6️⃣",
  "keycap-6" -> "6️⃣",
  "keycap 6" -> "6️⃣",
  "six" -> "6️⃣",
  "keycap_7" -> "7️⃣",
  "keycap-7" -> "7️⃣",
  "keycap 7" -> "7️⃣",
  "seven" -> "7️⃣",
  "keycap_8" -> "8️⃣",
  "keycap-8" -> "8️⃣",
  "keycap 8" -> "8️⃣",
  "eight" -> "8️⃣",
  "keycap_9" -> "9️⃣",
  "keycap-9" -> "9️⃣",
  "keycap 9" -> "9️⃣",
  "nine" -> "9️⃣",
  "keycap_10" -> "🔟",
  "keycap-10" -> "🔟",
  "keycap 10" -> "🔟",
  "keycap_ten" -> "🔟",
  "input_latin_uppercase" -> "🔠",
  "input-latin-uppercase" -> "🔠",
  "input latin uppercase" -> "🔠",
  "capital_abcd" -> "🔠",
  "input_latin_lowercase" -> "🔡",
  "input-latin-lowercase" -> "🔡",
  "input latin lowercase" -> "🔡",
  "abcd" -> "🔡",
  "input_numbers" -> "🔢",
  "input-numbers" -> "🔢",
  "input numbers" -> "🔢",
  "1234" -> "🔢",
  "input_symbols" -> "🔣",
  "input-symbols" -> "🔣",
  "input symbols" -> "🔣",
  "symbols" -> "🔣",
  "input_latin_letters" -> "🔤",
  "input-latin-letters" -> "🔤",
  "input latin letters" -> "🔤",
  "abc" -> "🔤",
  "A_button_(blood_type)" -> "🅰️",
  "A-button-(blood-type)" -> "🅰️",
)
