package io.github.edadma.markdown

val emojiBlock5 = List(
  "Mrs._Claus" -> "🤶",
  "Mrs.-Claus" -> "🤶",
  "Mrs. Claus" -> "🤶",
  "mrs_claus" -> "🤶",
  "mx_claus" -> "🧑‍🎄",
  "mx-claus" -> "🧑‍🎄",
  "mx claus" -> "🧑‍🎄",
  "superhero" -> "🦸",
  "man_superhero" -> "🦸‍♂️",
  "man-superhero" -> "🦸‍♂️",
  "man superhero" -> "🦸‍♂️",
  "superhero_man" -> "🦸‍♂️",
  "woman_superhero" -> "🦸‍♀️",
  "woman-superhero" -> "🦸‍♀️",
  "woman superhero" -> "🦸‍♀️",
  "superhero_woman" -> "🦸‍♀️",
  "supervillain" -> "🦹",
  "man_supervillain" -> "🦹‍♂️",
  "man-supervillain" -> "🦹‍♂️",
  "man supervillain" -> "🦹‍♂️",
  "supervillain_man" -> "🦹‍♂️",
  "woman_supervillain" -> "🦹‍♀️",
  "woman-supervillain" -> "🦹‍♀️",
  "woman supervillain" -> "🦹‍♀️",
  "supervillain_woman" -> "🦹‍♀️",
  "mage" -> "🧙",
  "man_mage" -> "🧙‍♂️",
  "man-mage" -> "🧙‍♂️",
  "man mage" -> "🧙‍♂️",
  "mage_man" -> "🧙‍♂️",
  "woman_mage" -> "🧙‍♀️",
  "woman-mage" -> "🧙‍♀️",
  "woman mage" -> "🧙‍♀️",
  "mage_woman" -> "🧙‍♀️",
  "fairy" -> "🧚",
  "man_fairy" -> "🧚‍♂️",
  "man-fairy" -> "🧚‍♂️",
  "man fairy" -> "🧚‍♂️",
  "fairy_man" -> "🧚‍♂️",
  "woman_fairy" -> "🧚‍♀️",
  "woman-fairy" -> "🧚‍♀️",
  "woman fairy" -> "🧚‍♀️",
  "fairy_woman" -> "🧚‍♀️",
  "vampire" -> "🧛",
  "man_vampire" -> "🧛‍♂️",
  "man-vampire" -> "🧛‍♂️",
  "man vampire" -> "🧛‍♂️",
  "vampire_man" -> "🧛‍♂️",
  "woman_vampire" -> "🧛‍♀️",
  "woman-vampire" -> "🧛‍♀️",
  "woman vampire" -> "🧛‍♀️",
  "vampire_woman" -> "🧛‍♀️",
  "merperson" -> "🧜",
  "merman" -> "🧜‍♂️",
  "mermaid" -> "🧜‍♀️",
  "elf" -> "🧝",
  "man_elf" -> "🧝‍♂️",
  "man-elf" -> "🧝‍♂️",
  "man elf" -> "🧝‍♂️",
  "elf_man" -> "🧝‍♂️",
  "woman_elf" -> "🧝‍♀️",
  "woman-elf" -> "🧝‍♀️",
  "woman elf" -> "🧝‍♀️",
  "elf_woman" -> "🧝‍♀️",
  "genie" -> "🧞",
  "man_genie" -> "🧞‍♂️",
  "man-genie" -> "🧞‍♂️",
  "man genie" -> "🧞‍♂️",
  "genie_man" -> "🧞‍♂️",
  "woman_genie" -> "🧞‍♀️",
  "woman-genie" -> "🧞‍♀️",
  "woman genie" -> "🧞‍♀️",
  "genie_woman" -> "🧞‍♀️",
  "zombie" -> "🧟",
  "man_zombie" -> "🧟‍♂️",
  "man-zombie" -> "🧟‍♂️",
  "man zombie" -> "🧟‍♂️",
  "zombie_man" -> "🧟‍♂️",
  "woman_zombie" -> "🧟‍♀️",
  "woman-zombie" -> "🧟‍♀️",
  "woman zombie" -> "🧟‍♀️",
  "zombie_woman" -> "🧟‍♀️",
  "troll" -> "🧌",
  "person_getting_massage" -> "💆",
  "person-getting-massage" -> "💆",
  "person getting massage" -> "💆",
  "massage" -> "💆",
  "man_getting_massage" -> "💆‍♂️",
  "man-getting-massage" -> "💆‍♂️",
  "man getting massage" -> "💆‍♂️",
  "massage_man" -> "💆‍♂️",
  "woman_getting_massage" -> "💆‍♀️",
  "woman-getting-massage" -> "💆‍♀️",
  "woman getting massage" -> "💆‍♀️",
  "massage_woman" -> "💆‍♀️",
  "person_getting_haircut" -> "💇",
  "person-getting-haircut" -> "💇",
  "person getting haircut" -> "💇",
  "haircut" -> "💇",
  "man_getting_haircut" -> "💇‍♂️",
  "man-getting-haircut" -> "💇‍♂️",
  "man getting haircut" -> "💇‍♂️",
  "haircut_man" -> "💇‍♂️",
  "woman_getting_haircut" -> "💇‍♀️",
  "woman-getting-haircut" -> "💇‍♀️",
  "woman getting haircut" -> "💇‍♀️",
  "haircut_woman" -> "💇‍♀️",
  "person_walking" -> "🚶",
  "person-walking" -> "🚶",
  "person walking" -> "🚶",
  "walking" -> "🚶",
  "man_walking" -> "🚶‍♂️",
  "man-walking" -> "🚶‍♂️",
  "man walking" -> "🚶‍♂️",
  "walking_man" -> "🚶‍♂️",
  "woman_walking" -> "🚶‍♀️",
  "woman-walking" -> "🚶‍♀️",
  "woman walking" -> "🚶‍♀️",
  "walking_woman" -> "🚶‍♀️",
  "person_standing" -> "🧍",
  "person-standing" -> "🧍",
  "person standing" -> "🧍",
  "standing_person" -> "🧍",
  "man_standing" -> "🧍‍♂️",
  "man-standing" -> "🧍‍♂️",
  "man standing" -> "🧍‍♂️",
  "standing_man" -> "🧍‍♂️",
  "woman_standing" -> "🧍‍♀️",
  "woman-standing" -> "🧍‍♀️",
  "woman standing" -> "🧍‍♀️",
  "standing_woman" -> "🧍‍♀️",
  "person_kneeling" -> "🧎",
  "person-kneeling" -> "🧎",
  "person kneeling" -> "🧎",
  "kneeling_person" -> "🧎",
  "man_kneeling" -> "🧎‍♂️",
  "man-kneeling" -> "🧎‍♂️",
  "man kneeling" -> "🧎‍♂️",
  "kneeling_man" -> "🧎‍♂️",
  "woman_kneeling" -> "🧎‍♀️",
  "woman-kneeling" -> "🧎‍♀️",
  "woman kneeling" -> "🧎‍♀️",
  "kneeling_woman" -> "🧎‍♀️",
  "person_with_white_cane" -> "🧑‍🦯",
  "person-with-white-cane" -> "🧑‍🦯",
  "person with white cane" -> "🧑‍🦯",
  "person_with_probing_cane" -> "🧑‍🦯",
  "man_with_white_cane" -> "👨‍🦯",
  "man-with-white-cane" -> "👨‍🦯",
  "man with white cane" -> "👨‍🦯",
  "man_with_probing_cane" -> "👨‍🦯",
  "woman_with_white_cane" -> "👩‍🦯",
  "woman-with-white-cane" -> "👩‍🦯",
  "woman with white cane" -> "👩‍🦯",
  "woman_with_probing_cane" -> "👩‍🦯",
  "person_in_motorized_wheelchair" -> "🧑‍🦼",
  "person-in-motorized-wheelchair" -> "🧑‍🦼",
  "person in motorized wheelchair" -> "🧑‍🦼",
  "man_in_motorized_wheelchair" -> "👨‍🦼",
  "man-in-motorized-wheelchair" -> "👨‍🦼",
  "man in motorized wheelchair" -> "👨‍🦼",
  "woman_in_motorized_wheelchair" -> "👩‍🦼",
  "woman-in-motorized-wheelchair" -> "👩‍🦼",
  "woman in motorized wheelchair" -> "👩‍🦼",
  "person_in_manual_wheelchair" -> "🧑‍🦽",
  "person-in-manual-wheelchair" -> "🧑‍🦽",
  "person in manual wheelchair" -> "🧑‍🦽",
  "man_in_manual_wheelchair" -> "👨‍🦽",
  "man-in-manual-wheelchair" -> "👨‍🦽",
  "man in manual wheelchair" -> "👨‍🦽",
  "woman_in_manual_wheelchair" -> "👩‍🦽",
  "woman-in-manual-wheelchair" -> "👩‍🦽",
  "woman in manual wheelchair" -> "👩‍🦽",
  "person_running" -> "🏃",
  "person-running" -> "🏃",
  "person running" -> "🏃",
  "runner" -> "🏃",
  "running" -> "🏃",
  "man_running" -> "🏃‍♂️",
  "man-running" -> "🏃‍♂️",
  "man running" -> "🏃‍♂️",
  "running_man" -> "🏃‍♂️",
  "woman_running" -> "🏃‍♀️",
  "woman-running" -> "🏃‍♀️",
  "woman running" -> "🏃‍♀️",
  "running_woman" -> "🏃‍♀️",
  "woman_dancing" -> "💃",
  "woman-dancing" -> "💃",
  "woman dancing" -> "💃",
  "dancer" -> "💃",
  "man_dancing" -> "🕺",
  "man-dancing" -> "🕺",
  "man dancing" -> "🕺",
  "person_in_suit_levitating" -> "🕴️",
  "person-in-suit-levitating" -> "🕴️",
  "person in suit levitating" -> "🕴️",
  "business_suit_levitating" -> "🕴️",
  "people_with_bunny_ears" -> "👯",
  "people-with-bunny-ears" -> "👯",
  "people with bunny ears" -> "👯",
  "dancers" -> "👯",
  "men_with_bunny_ears" -> "👯‍♂️",
  "men-with-bunny-ears" -> "👯‍♂️",
  "men with bunny ears" -> "👯‍♂️",
  "dancing_men" -> "👯‍♂️",
  "women_with_bunny_ears" -> "👯‍♀️",
  "women-with-bunny-ears" -> "👯‍♀️",
  "women with bunny ears" -> "👯‍♀️",
  "dancing_women" -> "👯‍♀️",
  "person_in_steamy_room" -> "🧖",
  "person-in-steamy-room" -> "🧖",
  "person in steamy room" -> "🧖",
  "sauna_person" -> "🧖",
  "man_in_steamy_room" -> "🧖‍♂️",
  "man-in-steamy-room" -> "🧖‍♂️",
  "man in steamy room" -> "🧖‍♂️",
  "sauna_man" -> "🧖‍♂️",
  "woman_in_steamy_room" -> "🧖‍♀️",
  "woman-in-steamy-room" -> "🧖‍♀️",
  "woman in steamy room" -> "🧖‍♀️",
  "sauna_woman" -> "🧖‍♀️",
  "person_climbing" -> "🧗",
  "person-climbing" -> "🧗",
  "person climbing" -> "🧗",
  "climbing" -> "🧗",
  "man_climbing" -> "🧗‍♂️",
  "man-climbing" -> "🧗‍♂️",
  "man climbing" -> "🧗‍♂️",
  "climbing_man" -> "🧗‍♂️",
  "woman_climbing" -> "🧗‍♀️",
  "woman-climbing" -> "🧗‍♀️",
  "woman climbing" -> "🧗‍♀️",
  "climbing_woman" -> "🧗‍♀️",
  "person_fencing" -> "🤺",
  "person-fencing" -> "🤺",
  "person fencing" -> "🤺",
  "horse_racing" -> "🏇",
  "horse-racing" -> "🏇",
  "horse racing" -> "🏇",
  "skier" -> "⛷️",
  "snowboarder" -> "🏂",
  "person_golfing" -> "🏌️",
  "person-golfing" -> "🏌️",
  "person golfing" -> "🏌️",
  "golfing" -> "🏌️",
  "man_golfing" -> "🏌️‍♂️",
  "man-golfing" -> "🏌️‍♂️",
  "man golfing" -> "🏌️‍♂️",
  "golfing_man" -> "🏌️‍♂️",
  "woman_golfing" -> "🏌️‍♀️",
  "woman-golfing" -> "🏌️‍♀️",
  "woman golfing" -> "🏌️‍♀️",
  "golfing_woman" -> "🏌️‍♀️",
  "person_surfing" -> "🏄",
  "person-surfing" -> "🏄",
  "person surfing" -> "🏄",
  "surfer" -> "🏄",
  "man_surfing" -> "🏄‍♂️",
  "man-surfing" -> "🏄‍♂️",
  "man surfing" -> "🏄‍♂️",
  "surfing_man" -> "🏄‍♂️",
  "woman_surfing" -> "🏄‍♀️",
  "woman-surfing" -> "🏄‍♀️",
  "woman surfing" -> "🏄‍♀️",
  "surfing_woman" -> "🏄‍♀️",
  "person_rowing_boat" -> "🚣",
  "person-rowing-boat" -> "🚣",
  "person rowing boat" -> "🚣",
  "rowboat" -> "🚣",
  "man_rowing_boat" -> "🚣‍♂️",
  "man-rowing-boat" -> "🚣‍♂️",
  "man rowing boat" -> "🚣‍♂️",
  "rowing_man" -> "🚣‍♂️",
  "woman_rowing_boat" -> "🚣‍♀️",
  "woman-rowing-boat" -> "🚣‍♀️",
  "woman rowing boat" -> "🚣‍♀️",
  "rowing_woman" -> "🚣‍♀️",
  "person_swimming" -> "🏊",
  "person-swimming" -> "🏊",
  "person swimming" -> "🏊",
  "swimmer" -> "🏊",
  "man_swimming" -> "🏊‍♂️",
  "man-swimming" -> "🏊‍♂️",
  "man swimming" -> "🏊‍♂️",
  "swimming_man" -> "🏊‍♂️",
  "woman_swimming" -> "🏊‍♀️",
  "woman-swimming" -> "🏊‍♀️",
  "woman swimming" -> "🏊‍♀️",
  "swimming_woman" -> "🏊‍♀️",
  "person_bouncing_ball" -> "⛹️",
  "person-bouncing-ball" -> "⛹️",
  "person bouncing ball" -> "⛹️",
  "bouncing_ball_person" -> "⛹️",
  "man_bouncing_ball" -> "⛹️‍♂️",
  "man-bouncing-ball" -> "⛹️‍♂️",
  "man bouncing ball" -> "⛹️‍♂️",
  "bouncing_ball_man" -> "⛹️‍♂️",
  "basketball_man" -> "⛹️‍♂️",
  "woman_bouncing_ball" -> "⛹️‍♀️",
  "woman-bouncing-ball" -> "⛹️‍♀️",
)
